= Y.A.R.I.S: Adventurer's guide to doom & destruction & stuff
:stylesheet: style.css
:doctype: article
:icons: font
:sectlinks:
:toc:
:toclevels: 1
:toc-placement!:
:experimental:
:stem:
:xrefstyle: basic

This document contains character creation and game mechanics, as well as gear,
spells, and abilities for characters of first and second level.

toc::[]

// {{{ ADVENTURERS SHEET
== ADVENTURER’S SHEET
The adventurer’s sheet has a bunch of fields for you to pencil in, and when
you’re done, you’re ready for adventure.

=== Stats
Your character has 6 primary stats:

[%unbreakable]
--
[horizontal]
Strength     :: melee attacks, jock stuff and carrying gear.
Dexterity    :: stealth, melee defense, and tricky tasks.
Constitution :: carrying gear and surviving bad trauma.
Intelligence :: initiative, magic, and managing resources.
Wisdom       :: ranged attack, ranged defense, and perception.
Charisma     :: luck, negotiation, charm magic, and selling treasure.
--

=== Extra Stuff

*Level*: your character's level is a measure of their badassity. You start at
level 1 and max out at level 10. Baddies, spells, certain items and tasks
also have levels.

*Hit points (HP)*: is your current number of hit points. Bad stuff happens if
you <<zero_hp,run out of hit points>>.

[reftext="hit point total"]
[[hit_point_total]]
*Hit point total*: is the maximum number of hit points you can have. I.e. the
number of HP you have when you're at full health. This number increases every
time you gain a new level, and wearing armor
can also increase this number.

[reftext="recovery die"]
[[recovery_die]]
*Recovery die*: is the die you roll (one or more of) to regain hit points when
you rest or receive magical healing. You start with a recovery die of d8.

*Total item slots*: is the maximum number of <<item_slots,items>> you can
carry. This number is the highest of your _strength_ and _constitution_.

*Unencumbered item slots*: is the number of items you can carry without being
encumbered. This number is the lowest of your _strength_ and _constitution_.

*Moves*: is the number of meters you can move in a round. You can also use
moves to do other interesting <<Moves,things>>.
// }}}

// {{{ CREATE YOUR ADVENTURER
== CREATE YOUR ADVENTURER
Go through the following sections, one by one, to create a new character.

=== 1. Stats
For each of your six stats in order, you roll 1d8+6 and assign the result to
that stat. Now each stat has a value between 7 and 14.

=== 2. Background & Fluff
Roll on each of the following tables to flesh out your character.

==== Ancestral Traits
First roll a d6. If it is an even number, you do not have any special ancestral
traits. If it is an odd number, roll two more d6. The lowest number is used on
the table on the left, and the highest number is used on the table on the
right.

[%header,%unbreakable,cols="^6,^6"]
|===
| Low roll  | High roll
//----------|-----------
| Hands     | Troll
| Ears      | Gnoll
| Nose      | Goblin
| Hair      | Elf
| Eyes      | Dwarf
| Teeth     | Gnome
//----------|-----------
|===

.Ancestral Traits
====
A roll of 1 and 6 would give you gnome hands, and a roll of one and one you
troll hands (claws, maybe?) and a roll of 4 and 3 would give you an elven nose.
====

==== Vice
Roll a d12. If you roll a number that isn't on the table, you don’t have a vice.

[%header,cols="^1,11"]
|===
| 1d12  | Vice
//------|--------------------------
| 1-6   | No vice
| 7     | Attention seeking
| 8     | Bar fighting
| 9     | Drinking
| 10    | Fornicating
| 11    | Gambling
| 12    | Stealing
//------|--------------------------
|===


==== Background
Roll a d6 and a d20. If the d6 rolled an even number, pick your background from
the left column, otherwise pick your background from the right column

[%header,cols=2*a]
|===
| d6 rolled 1, 3, or 5 | d6 rolled 2, 4, or 6
|
. Apothecary
. Baker
. Banker
. Bartender
. Butcher
. Carter
. Chandler
. Chef
. Clergy
. Clerk
. Companion
. Cook
. Courier
. Courtier
. Doctor
. Entertainer
. Farmer
. Fisherman
. Foreigner: roll again for original background
. Gambler
|
. Gold Smith
. Hunter
. Hustler
. Laborer
. Lazy spouse
. Magician’s apprentice
. Merchant
. Monestarian
. Musician
. Notary
. Officer
. Prisoner
. Royalty
. Sailor
. Scribe
. Smith
. Solder
. Squire
. Street urchin
. Thief
|===


=== 3. Adventuring Gear
All characters start with the following equipment:

* A backpack
* 2 × <<torch>>
* A <<light_melee_weapon>>
* Two normal <<rations,ration packs>>
* A set of common clothing
* A bedroll

*In addition to that:* Roll on each of the following tables to find out what
equipment your character starts with. 

==== Ranged weapon
Roll 1d6 on this table to find out if you have a ranged weapon.

[%header,cols="^2,10"]
|===
| d6    | Weapon
//------|-----------
| 1-3   | No Ranged Weapon
| 4     | Slingshot + Bag of stones
| 5     | Bow + Quiver of arrows
| 6     | Crossbow + Quiver of bolts
//------|-----------
|===

==== Shield
Roll 1d6. If you rolled 5 or 6, you have a light shield. Otherwise, you don’t
have a shield.

// Turn automatic section id off. We want <<Armor>> to link
// to a later section
:!sectids:
==== Armor
:sectids:
Armors give you extra hit points; you have 1d3-1 
<<light_armor_table,light armor pieces>> of your choice.

==== Utility Gear
Roll once on the <<utility_gear_1>> table.

[[utility_gear_1]]
.Utility Gear 1
[%header,%unbreakable,cols="^1,11",grid=none,frame=none,stripes=even]
|===
| 1d10 | Item
//-----|-----------
| 1    | <<iron_rations>>
| 2    | grappling hook
| 3    | <<storm_lantern>>
| 4    | rope, 10 meters
| 5    | <<kosh>>
| 6    | ball bearings
| 7    | shovel
| 8    | <<lockpicking_tools>>
| 9    | <<lantern>>
| 10   | <<purse_copper>>
//-----|-----------
|===


Roll twice on the <<utility_gear_2>> table.
If the second roll is the same as the first roll,
reroll it.

[%unbreakable]
--
[[utility_gear_2]]
.Utility Gear 2
[%header,%unbreakable,cols="^1,11",grid=none,frame=none,stripes=even]
|===
| 1d10 | Item
//-----|-----------
| 1    | 2d4 gold pieces
| 2    | <<spellbook>> with 2 <<usage_points>>
         and a spell of your choice.
| 3    | <<torch>>
| 4    | <<spikes>>
| 5    | <<tinkering_tools>>
| 6    | pole, 3m, foldable
| 7    | chalk
| 8    | <<rations,ration pack, normal>>
| 9    | <<lamp_oil,lamp oil>>
| 10   | <<map_making_tools>>
//-----|-----------
|===
--

=== All Done
Now it’s time to read about the adventurer class and then check out the
sections on dice checks and combat.

// }}}

// {{{ ADVENTURER
== ADVENTURER

[quote, Baron LeDik]
____
Adventurers are brave, eager, and dangerous
____

All characters start out with the same class: Adventurer.

=== Level 1

==== Recovery Die
Your recovery die is d8. This means that you regenerate 1d8 hit points when you
get a good long rest. Spells and potions may let you regenerate several
recovery dice at once.


[reftext="hit points"]
[[hit_points]]
==== Hit Points
At first level, your hit point total is 8, which means that, under normal
circumstances, you can’t have more than 8 hit points. When you have lost all
your hit points, you have to roll on the <<death_table>>.

[[armor_skills]]
==== Armor Skills
You  are skilled at using light shields and light armors. If you are wearing an
armor you're not skilled at using, you lose one <<Moves,move>>.
See the <<Armor>> section for more info and pay attention to what happens if you're
wearing broken armor.

[[weapon_skills]]
==== Weapon Skills
You are skilled at using light melee weapons and ranged weapons. On the
<<adventurer_damage_rolls_table,table below>> you can see how much damage you
deal with each weapon category.

[[adventurer_damage_rolls_table]]
.Adventurer Damage Rolls
[%header,cols="8,^2,^2"]
|===
| Weapon Type           | Skill level | Damage Roll
//----------------------|-------------|------------
| Light Melee Weapons   | Skilled     | 1d6
| Ranged Weapons        | Skilled     | 1d6
| Unarmed Combat        | Unskilled   | 1d3
| Heavy Melee Weapons   | Unskilled   | 1d10
//----------------------|-------------|------------
|===

.Range
[reftext="attack range"]
[[attack_range]]
****
When using ranged weapons, you can attack creatures that are up to _wisdom_
meters away. But if you go beyond the weapon's base range (which is equal to
its price in gold pieces), your attacks are <<difficult>>.
****

==== Adventurer's Blessing
Adventurers generally don't get sick from mundane illnesses, they can
generally take much more punishment than other creatures, and they are
more or less the only people who can be revived with magic.

[quote,Margot LeDik]
____
Because of the Adventurer's Blessing, many nations seek to have high-level
former adventurers in key military and governing positions, as the ability to
be revived can be vital, excuse the pun, for the continuation of the position.
____

==== Exotic Weapon Skills
You are *not skilled* at using exotic weapons such as the <<kosh>>.
Becoming skilled with such weapons require special training or abilities (such
as <<shady>>).

==== Spellcasting
You can use <<basic_spellcasting>> to cast <<basic>> spells fast and
efficiently via <<spellbook,spellbooks>>. You can also use
<<basic_ritual_casting>> to cast <<ritual,certain>> spells more slowly,
draining your spellbook less. You can also use <<basic_recharging>> to recharge
depleted spellbooks.

=== Level 2
When you reach second level, you gain more hit points, better stats, and a
special ability.

==== More Hit Points More Better
Your hit point total is increased by 1d8. Roll with advantage.

==== Better Stats
For each of your stats, you roll a d20; if the roll is higher than the stat,
that stat is increased by 1 point. And an even more betterer stat Roll a d20
and select a stat that is lower than the result of the die roll. Increase that
stat by 1 point. If no stats are lower than your die roll, nothing happens.

==== Adventurer’s Special Ability
Choose one of the abilities below. You can switch this ability at levels 4, 6,
8, and 10.

//START_SORT //KEY:

//KEY:
[reftext="armorer"]
[[armorer]]
*Armorer*: You can repair a piece of broken armor if you have
<<tinkering_tools>>.

//KEY:
[reftext="everdeen"]
[[everdeen]]
*Everdeen*: If you are without arrows during combat, you can spend 3 moves, and
make a _charisma_ check. If successful, you somehow have a single extra arrow
and you’re ready to fire. If unsuccessful, you cannot use this ability before
you have stocked up on ammunition. This ability also works with bolts,
slingshots, and darts.

//KEY:
[reftext="great weapon specialist"]
[[great_weapon_specialist]]
*Great weapon specialist*: You are skilled at using heavy melee weapons.

//KEY:
[reftext="monstrous gourmand"]
[[monstrous_gourmand]]
*Monstrous Gourmand*: You can make edible ration packs from fresh monster parts (any recently dead
creature will do) It requires sharp cutting instruments, a large pot, a bonfire
(or equivalent source of heat), one hour of work, and a successful
_intelligence_ check to create one ration pack. A medium sized creature
“contains” 2 ration packs. In addition to creating rations, you are also able
to eat fresh, uncooked, monster meat without getting sick. It requires a sharp
cutting tool, 3d6 minutes, and a successful _constitution_ check to create and
eat such a “meal”.

//KEY:
[reftext="negotiator"]
[[negotiator]]
*Negotiator*: You have advantage on checks that involve negotiation. You also
have advantage on your <<haggling_check>>.

//KEY:
[reftext="pugilist"]
[[pugilist]]
*Pugilist*: You are skilled at unarmed combat, meaning your attack checks are
normal instead of difficult. If you're not weapon a shield, and not wearing any
medium or heavy armor pieces, your unarmed damage die is increased to 1d6.

[quote]
Striking certain dangerous monsters (such as fire elementals) with
your body can have grave consequences.

//KEY:
[reftext="rider"]
[[rider]]
*Rider*: You acquire a trained horse for free (tamed wild horse, a gift, or
similar). You become proficient at riding horses. You have <<advantage>> on all
riding-related checks. You have <<advantage>> on
<<consumption_check,consumption checks>> for animal feed. When you reach level
5 your riding proficiency expands to all rideable land creatures. At level 8,
you can ride virtually any tame creature.

****
*_Your horse_* can drag a cart that can either carry you and two others, or you
and 20 <<item_slots>> of cargo. When you ride it or direct it, it can move 2
meters for every <<Moves,move>> you make, and it has the same stats and hit
points as you, except for _intelligence_, which is 2. The horse generally does
what you want when you're in the saddle, but you have to succeed a _charisma_
(with <<advantage>>) check to command it when you're not.

*Feed*: You can feed your horse animal feed, and if you can't you can feed it with
<<rations>>, but the horse eats so much that you will have to make two
<<consumption_check,consumption checks>> per day.

*Species*: In some areas horses and ponies are rare. In such areas, you'd
get the most common riding animal instead of a horse.
****


//KEY:
[reftext="shady"]
[[shady]]
*Shady*: On a successful _charisma_ check you pull out a dagger from a boot, a
sleeve or… somewhere. If your check fails, you cannot do it again for the rest
of the session. In combat, this feat requires 3 moves. You are also skilled at
using a <<kosh>>, something normal adventurers are not.

[quote]
The gods do not smile on people who use this ability to get rich by selling
daggers.

//KEY:
[reftext="spelunker"]
[[spelunker]]
*Spelunker*:
You cannot go <<dungeon_mad>>.
You always have some chalk.
You always know the cardinal directions.
One of the ropes you carry does not take up an <<item_slots,item slot>>.
You have <<advantage>> on <<consumption_check,consumption checks>> checks
for <<lamp_oil>>, <<lantern,lanterns>>, and <<torch,torches>>. You have
<<advantage>> on checks that involve navigation in caves and dungeons.

//KEY:
[reftext="thrifty"]
[[thrifty]]
*Thrifty*: You have advantage on <<consumption_check,consumption checks>> with
<<coin_purse,coin purses>>.

//KEY:
[reftext="traveler"]
[[traveler]]
*Traveler*: You have advantage on <<consumption_check,consumption checks>> for
rations and animal feed. You have advantage on geography related checks. One of
the ration packs you carry does’t take up an <<item_slots,item slot>>
//END_SORT

=== Level 3: Graduation
It is time for you to move on. You’re no longer just an adventurer, you’re a
Hero. Choose a hero class from the xref:heroes#[Hero’s Guide to doom &
destruction & stuff].

//}}}

//{{{ LEVELS
== LEVELS
You begin at level 1, and you can gain levels until you reach level 10. You
gain levels by acquiring suitable treasures. For a team of level <<X>>
adventurers to gain a new level, they must acquire <<X>> suitable treasures. This
document only deals with levels 1 and 2. Once you reach level 3, you become a
hero; see xref:heroes#[Hero’s Guide to doom & destruction & stuff] for more
info.

*Treasure*: A treasure is a big horde, often situated in one location. It is up
to the GM to decide what is an actual treasure, and what is just general loot.

*Suitable*: A _suitable_ treasure is worth at least 100 gold pieces times the
sum of the levels of all the characters in the party.

*Acquire*:
You have _acquired_ a treasure when you have transported at least two thirds of
it (by value) safely back to your base of operations. It can be necessary to
make multiple trips to recover a large treasure.

.Leveling up
====
- In order to level up, a party of 5 first level characters must acquire a
  single treasure worth _5·1·100=500_ gold pieces.

- In order to level up, a party of 4 PCs at 6th level must acquire six
  treasures in order to advance. Each treasure must be worth at least
  _4·6·100=2,400_ gold pieces.
====

// }}}

//{{{DICE
== DICE
You can make rolls and checks with your dice. A roll is any kind of roll such
as 1d6, 2d4, 3d6+3, etc. A check is a special kind of roll described below.

=== Checks
You make checks to see if your character can successfully do something
non-trivial; you roll your d20. The check is successful if you roll under a
specified *_target number_*, which is usually one of your stats.

.Target Number
====
You want to lift something really heavy, so the GM tells you to make a
_strength_ check. You roll a d20. If you rolled lower than your _strength_, the
check was successful, otherwise it was unsuccessful.
====

[reftext="1"]
[[nat1]]
*Rolling a 1*: Checks are always successful if you roll a 1 on your d20.

[reftext="20"]
[[nat20]]
*Rolling a 20*: Checks are always unsuccessful if you roll a 20 on your d20.

[reftext="easy"]
[[easy]]
*Easy checks*: are checks where the target number is 3 higher than what it
would normally be.

.Easy strength check
====
if your _strength_ is 9, making an easy _strength_ check would need to roll under 12.
====

[reftext="difficult"]
[[difficult]]
*Difficult checks*: are checks where the target number is 3 lower than what *:
normally would be.

.Difficult strength check
[example]
if your _strength_ is 9, making a difficult _strength_ check would need to roll
under 6.

*Both = Difficult*: If one or more conditions make a check <<difficult>>, it
remains difficult if there are other many other circumstances that would have
made the check
<<easy>>.

.Both = Difficult
====
You are battling an orc whose level is 2 below yours. This would normally make
the roll <<easy>>, but you're also <<encumbered>>, which makes the check
<<difficult>>, so, overall, your check remains _difficult_.
====

[reftext="adversarial"]
[[adversarial]]
=== Adversarial Checks
These are checks where the difficulty depends on the level of the adversary. In
this context, and adversary can be a baddie, a lock, a trap, a
riddle, or similar.

If the adversary is two or more levels above you, the check is
<<difficult>>, and if the adversary is two or more levels
below you, the check is <<easy>>.

.Adversarial Checks
====

A second level adventurer is trying to attack an evil orc who is level 5.
This attack is <<difficult>> because the orc is two or more levels above the
adventurer.

---

A level 3 player character is trying to haggle with a merchant to get a good
price on some loot. The PC is level 3, and the merchant is level 1, so the
check is <<easy>>.

---

You are attacking a zombie. You are level 2, and the zombie is level 1, so
your are within one level of each other, and thus your check is normal.
====

=== Advantage & Disadvantage
Certain conditions, abilities, classes, and spells can give a roll an advantage
or disadvantage, which changes the way you roll the dice.

[reftext="advantage"]
[[advantage]]
*Advantage*: If a roll has advantage, you roll the dice twice, and pick the result you like
best.

.Damage roll with advantage
====
you have advantage on a Damage Roll, you roll your damage dice twice and pick
the roll you like best.
====

[reftext="disadvantage"]
[[disadvantage]]
*Disadvantage*: If a roll has disadvantage, you roll the dice twice, and the GM picks the
result they like.

*Both = neither*: If at least one advantage and at least one disadvantage applies to the same
roll, it becomes a normal without any advantage or disadvantage roll.

//}}}

//{{{EQUIPMENT
== EQUIPMENT
This section contains info on item slots, <<usage_points>>, and
several lists of equipment. These lists are not exhaustive, and other types of
items and equipment exist.

=== Money
The weight of a few coins is negligible, but in large quantities, 100 coins
take up one <<item_slots,item slot>>.
A gold piece is equivalent to 100 silver pieces, a silver piece is 100 copper
pieces.

[reftext="item slots"]
[[item_slots]]
=== Item Slots
An average item takes up one item slot. Bulky or heavy items, such as heavy
armor, can take up multiple item slots. Your number of item slots is determined
by your _strength_ and _constitution_. The lower of these two numbers is your
number of unencumbered item slots, and the higher number is your total number
of item slots. You can use all your unencumbered item slots without any side
effects, but If you use any of your remaining item slots, you become
encumbered, which means that everything you do becomes difficult. You can never
fill/carry more than your item slots total.

.Calculating item slots
====
If your _strength_ is 7 and your _constitution_ is 16, you have 16 _item
slots_, and 7 of those are _unencumbered item slots_. This means that, if you
use 8 or more of your item slots, you become <<encumbered>>.
====

[reftext="usage points"]
[[usage_points]]
=== Usage Points
Items that can be consumed or depleted (such as <<rations>>, arrows,
<<lamp_oil>>) have usage points. When you have used such an item you make a
consumption check to see if it loses a usage point. If the item run out of
<<usage_points>>, it is completely used up: no more arrows in the quiver, and
no more food in the ration pack.

[reftext="consumption check"]
[[consumption_check]]
=== Consumption & Consumption Checks
You are sometimes asked to spend a _consumption_ of a given consumable item.
When making a _consumption_ of an item, you first roll a _consumption check_,
which is a <<Checks,check>> with a target number of 11, and if the check wasn't
successful, the item in question loses a <<usage_points,usage point>>.

*Rations*:
You must spend one _consumption_ of <<rations>> every day if you don't want to
<<starving,starve>>. This means that, once a day, you must make a _consumption
check_, and if it fails, one of your ration packs loses a <<usage_points,usage
point>>.

*Consumable Projectiles*:
You do not roll a _consumption check_ every time you fire an arrow, bolt, or
slingshot during combat. Instead you make one consumption check after the
combat ends (one for each type of projectile you used). When you fire a
projectile while not in combat, you make a consumption check with <<advantage>>
after each projectile fired.

*Consumable Thrown Weapons*:
Items that can be used in melee combat _and_ ranged combat, such as knives,
spears, and javelins, do not have usage points; when you have thrown them,
they cannot be used any more during that combat.

=== Gear

.General Gear
[%header,cols="10,^1,^1"]
|===
| Name                  | IS| Cost
//----------------------|---|---------
| backpack              | 1 | 1  gp
| bedroll               | 1 | 1  sp
| clothing moderate     | 1 | 3  sp
| clothing, poor        | 1 | 3  cp
| clothing, wealthy     | 1 | 3  gp
| flint and steel       | 0 | 2  cp
| ladder, 2m            | 2 | 10 cp
| pole, 3m foldable     | 2 | 5  cp
| rope, 10m             | 1 | 2  cp
| rope, 25m             | 2 | 10 cp
| shovel                | 1 | 2  cp
//----------------------|---|---------
|===


.Consumables
[%header,cols="9,^1,^1,^1"]
|===
| Name                          | IS| UP| Cost
//------------------------------|---|---|-----------
| animal feed                   | 2 | 1 | 15 cp
| bag of slingshots             | 1 | 3 |
| ball bearings                 | 1 | 2 |
| candles                       | 1 | 6 |
| chalk                         | 1 | 12|
| <<lamp_oil>>                  | 1 | 2 | 5 cp
| quiver of arrows              | 1 | 3 |
| quiver of bolts               | 1 | 3 |
| <<magic_components>>          | 1 | 2 | 1 gp
| <<iron_rations>>              | 1 | 2 | 4 sp
| <<rations>>                   | 1 | 1 | 1 sp
| <<spikes>>                    | 1 | 2 |
| <<lockpicking_tools>>         | 1 | 4 |
| <<tinkering_tools>>           | 2 | 4 |
| <<torch>>                     | 1 | 2 | 5 cp
//------------------------------|---|---|-----------
|===

////
PRICE OF ARMOR

Price of armor is typically (hp)³
////

[[light_armor_table]]
.Light Armor
[%header,cols="9,^1,^1,^1"]
|===
| Armor Piece           | IS| HP| Cost
//----------------------|---|---|-----------
| Light Shield          | 1 | 4 | 8     gp
| Light Helmet          | 1 | 3 | 8     gp
| Light Cuirass         | 2 | 4 | 27    gp
| Light Gauntlets       | 1 | 3 | 8     gp
| Light Greaves         | 1 | 3 | 8     gp
//----------------------|---|---|-----------
|===

.Medium Armor
[%header,cols="9,^1,^1,^1"]
|===
| Armor Piece           | IS| HP| Cost
//----------------------|---|---|-----------
| Medium Shield         | 2 | 5 | 64    gp
| Medium Helmet         | 2 | 5 | 64    gp
| Medium Cuirass        | 3 | 6 | 125   gp
| Medium Gauntlets      | 2 | 5 | 64    gp
| Medium Greaves        | 2 | 5 | 64    gp
//----------------------|---|---|-----------
|===


.Heavy Armor
[%header,cols="9,^1,^1,^1"]
|===
| Armor Piece           | IS| HP| Cost
//----------------------|---|---|-----------
| Heavy Shield          | 3 | 7 | 216   gp
| Heavy Helmet          | 3 | 7 | 216   gp
| Heavy Cuirass         | 4 | 8 | 343   gp
| Heavy Gauntlets       | 3 | 7 | 216   gp
| Heavy Greaves         | 3 | 7 | 216   gp
//----------------------|---|---|-----------
|===

[[lodging]]
.Food and lodging (per person per night)
[%header,cols="10,^1"]
|===
| Lodging                                   | Cost
//------------------------------------------|--------
| Opulent (luxurious rooms and food)        | 1 gp
| Middle class (small room, decent fare)    | 1 sp
| Poor (sleep in common room, cheap food)   | 1 cp
//------------------------------------------|--------
|===


[reftext="light melee weapon"]
[[light_melee_weapon]]
.Melee Weapons
[%header,cols="10,^1,^1"]
|===
| Melee Weapon                  | IS| Cost
//------------------------------|---|--------
| Light Melee Weapon            | 1 | 3 gp
| Heavy Melee Weapon            | 2 | 8 gp
//------------------------------|---|--------
|===

.Ranged Weapons
[%header,cols="9,^1,^1,^1"]
|===
| Name                          | IS| UP| Cost
//------------------------------|---|---|---------
| Dagger                        | 1 | 1 | 3  gp
| Spear                         | 1 | 1 | 3  gp
| Darts                         | 1 | 4 | 3  gp
| Bow                           | 2 | - | 7  gp
| ↳ quiver of arrows            | 1 | 10| 2  gp
| Crossbow                      | 1 | - | 12 gp
| ↳ quiver of bolts             | 1 | 10| 2  gp
| Sling                         | 0 | - | 4  gp
| ↳ bag of stones               | 1 | 10| 2  gp
//------------------------------|---|---|---------
|===

.Attack Range
[TIP]
--
See <<attack_range>> for more info on how far your
ranged attacks can reach.
--

=== Special Items
//START_SORT //KEY:

//KEY:
[reftext="bank book"]
[[bank_book]]
==== Bank Book
A bank book is a magical book that can contain money. There is a magical ritual
called <<_banking_transaction_x>>, that allows you to transfer money into and
out of the book.

This item takes up 1 item slot.

//KEY:
[reftext="coin purse"]
[[coin_purse]]
==== Coin Purse
Purses aren't real items; they are concepts that can simplify bookkeeping.
Instead of keeping track of every copper penny and doing a lot of math, you
just make consumptions whenever you buy something. You don't need to buy purses
from a merchant - you just "buy" them directly from the GM. You cannot sell
them or exchange them.

[reftext="copper purse"]
[[purse_copper]]
*Copper purse*: for 1,000 copper pieces you can buy a copper purse. It has 10
<<usage_points>>. Whenever you buy something costing less than 100 copper
pieces, you make a <<consumption_check>> for the copper purse instead.

[reftext="silver purse"]
[[purse_silver]]
*Silver purse*: for 1,000 silver pieces you can buy a silver purse. It has 10
<<usage_points>>. Whenever you buy something costing less than 100 silver
pieces, you make a <<consumption_check>> for the silver purse instead.

[reftext="gold purse"]
[[purse_gold]]
*Gold purse*: for 1,000 gold pieces you can buy a gold purse. It has 10
<<usage_points>>. Whenever you buy something costing less than 100 gold pieces,
you make a <<consumption_check>> for the gold purse instead.

//KEY:
[reftext="coins"]
[[coins]]
==== Coins

Small amounts of counts do not take up any room, but 100 coins take up 1
<<item_slots,item slot>>, and generally requires a small sack to contain.

//KEY:
[reftext="kosh"]
[[kosh]]
==== Kosh
Adventurers with the <<shady>> special ability are skilled at using koshes. To
use a target, you make an attack check; if you hit the target, it immediately
loses 1 hit point. You then roll your damage die. If your roll was higher than
the target’s remaining hit points, the target gains the <<unconscious>>
condition, which means they’ll wake up within 2d6 hours unless they're healed.

This item takes up 1 item slot.

//KEY:
[reftext="lamp oil"]
[[lamp_oil]]
=== Lamp Oil
This <<consumption_check,consumable>> item is flammable; you can use it as fuel for your
lantern or storm lantern, and you can use it to light things on fire.

You can throw lamp oil to cover an area; You first roll a _dexterity_ check. If
successful, the oil bottle (or skin or jug) lands where you want it (within
_strength_ meters), ruptures, and covers an area of 1d4 square meters.
//
At this point the oil is not on fire; you must light it yourself with torch,
a spell, or similar fashion.

This item takes up 1 item slot.

//KEY:
[reftext="lantern"]
[[lantern]]
==== Lantern
Lanterns illuminates the area around you. The lantern does not have have any
usage points itself, but it it does <<lamp_oil>>; it uses one consumption every
hour.

You can throw a lantern, using it to ignite an area. You roll a _dexterity_
check. If successful, the lantern lands where you want it to (within _strength_
meters), and covers 1d4 square meters in flaming oil. Anyone inside the affected
area is set <<on_fire>>.

[reftext="storm lantern"]
[[storm_lantern]]
*Storm Lanterns*: are a variant of the normal <<lantern>> that cannot be blown
out in normal storms and gales. But they cannot be used to ignite an area
either, as they are designed to go out when they aren't upright.


//KEY:
[reftext="lockpicking tools"]
[[lockpicking_tools]]
==== Lockpicking Tools
These tools allow you to pick various locks. They can be used up, and therefore
have <<usage_points>>. To Open a Lock, you first spend 5 minutes and one
<<consumption_check,consumption>> of lockpicking tools. Then you make both a _dexterity_- and an
_intelligence_ check.

* If both are successful, you open the lock.
* If one is successful, the lock does not open, but you get to try again.
* If none are successful, the lock becomes jammed, and can only be opened by a
  real key.

This item takes up 1 item slot.

//KEY:
[reftext="magic components"]
[[magic_components]]
==== Magic Components
Magic components are used when casting rituals and when recharging spellbooks.
A consumption of magic components means you use some unspecified amount of your
magic components and then you make a consumption check. And if the check was
unsuccessful, your magic components lose a usage point.


//KEY:
[reftext="map making tools"]
[[map_making_tools]]
==== Map Making Tools
You can use these tools to maps of dungeons, cities, and various land areas.
To do so you must make an _intelligence_ check and a _wisdom_ check.

*   If both are successful, your mapping process is accurate for the entire
    dungeon level, city, or area.
*   If just one is successful, your scales are incorrect, and using the
    map is <<difficult>>.
*   If both failed, the map is not accurate at all. Twists and turns are
    wrong, scales are wrong, the cardinal directions are wrong, and there are
    missing areas and notes.

This item takes up 1 item slot.

//KEY
[reftext="rations"]
[[rations]]
==== Rations
Rations sustain you on your adventures. You must use one
<<consumption_check,consumption>> of rations every day, otherwise you become
<<starving>>.

[reftext="iron rations"]
[[iron_rations]]
*Iron Rations* have more <<usage_points>> that normal rations, but don't
require more <<item_slots>>.

//KEY:
[reftext="spikes"]
[[spikes]]
==== Spikes
When hammered in between the door and the wall or jamb, these 30 centimeter
spikes can wedge a door shut until the spikes are removed.

//KEY:
[reftext="tinkering tools"]
[[tinkering_tools]]
==== Tinkering Tools
Tinkering tools can be used to disarm traps and repair broken items.

Repairing mechanism:: To repair a trap, mechanism, stuck door, or similar,
you spend 10 minutes and one <<consumption_check,consumption>> of tinkering tools.
Then you make a _dexterity_ check and an _intelligence_ check.

* If both are successful, you have repaired the item.
* If one is successful, the item is still damage, but you may try again.
* If both failed, you cannot fix this item until you've gained a new level.

Repairing armors:: This is like repairing mechanisms, except: only
<<armorer,armorers>> can repair armors, and only _light armor_ can be repaired
using tinkering tools alone; _medium_ and _heavy_ armor also requires a
furnace (or the <<_furnace>> spell).

Repairing weapons:: This is like repairing mechanisms, except:
only <<armorer,armorers>> can repair weapons, and it requires both tinkering
tools and a furnace (or the <<_furnace>> spell).

Disarming traps:: To disarm a trap you spend 10 minutes and one
<<consumption_check,consumption>> of tinkering tools. Then you make a _dexterity_ and
_wisdom_ check.

* If both are successful, you have disarmed the trap.
* If one is successful, you did not disarm the trap, but you may try again.
* If both failed, the trap triggers, and you are not able to dodge the effects
  (if the trap is aimed at you).

This item takes up 2 item slots.

//KEY:
[reftext="torch"]
[[torch]]
==== Torch
Aside from illuminating the area around you, torches can be used for a number
of things.

Torches have 2 <<usage_points>>, and you must make a consumption
check every hour.

Torches can be revitalized; it requires one consumption of <<lamp_oil>> to
restore 1 <<usage_points,usage point>> to a torch. This cannot be done while
the torch is lit. After revitalizing your torch, you roll a difficult _wisdom_
check. If unsuccessful, the torch is destroyed, and cannot be lit.

You can use your torch as a light melee weapon, but it is difficult. If you
roll a <<nat20>> on your melee attack check, the torch breaks and cannot be
repaired. If you roll a <<nat1>>, the target is set <<on_fire>>,
dealing 1d4 damage every round until it is put out.

You can throw a torch and use it as a ranged weapon, but it is difficult. If
you rolled a <<nat20>> on your attack check, the torch is broken and cannot be
repaired. The throwing range of a torch is 5 meters.

This item takes up 1 item slot.

//END_SORT

=== Selling and Haggling
You buy things for price listed in this guide, but you cannot sell items at
that price. When selling something trivial or cheap, you sell it for 50% of the
listed value, but if you’re selling more precious things, you must make a
_haggling check_.

[reftext="haggling check"]
[[haggling_check]]
*Haggling Check*:
If you’re selling expensive items, or if you’re selling things in bulk, you
must haggle to get a good price. You first roll a _charisma_ check, and
refer to the table below, and do what it says, even if you don't like the
result.

[cols=">1s,11",grid=none,stripes=none,frame=none]
|===
| <<nat20>> | You sell the item(s) for 25% of local list price.
| Failure   | You sell the item(s) for 50% of local list price.
| Success   | You sell the item(s) for 75% of local list price.
| <<nat1>>  | You sell the item(s) for 100% of local list price.
|===

.Negotiator Ability
TIP: If you have the <<negotiator>> ability, you have <<advantage>>
on your haggling check.

//}}}

//{{{ COMBAT
== COMBAT

This section is all about fighting 🤺

[reftext="round"]
[[round]]
=== Rounds
Combat is divided into 10-second rounds. At the beginning of every round,
the adventurers roll _initiative_, to determine in which order they get to
act.

During their turn, a combatant can do the following things in order.
. Make up to 5 moves.
. Take one action.

=== Initiative
At the beginning of every round each adventurer makes an _intelligence_ check.
If the adventurers have more failed checks than there are combat capable
baddies on the battlefield, the baddies get to go first that round.

The players act in the order in which they sit around the gaming table,
clockwise from the GM, and the baddies act in whatever order the GM wishes.

=== Moves
You have 5 moves you can take before you take your main action. You can use
them in many ways, and here's some examples.

.Moves
[%header,cols="11,^1"]
|===
| Description                                   | Moves
//----------------------------------------------|------
| Move 1 meter in good terrain                  |   1
| Ready a potion from a belt pouch              |   1
| Draw a weapon from your sheath or equivalent  |   1
| Switch to a new quiver                        |   1
| Drop a light shield                           |   1
| Open a door                                   |   2
| Mount or dismount                             |   2
| Move 1 meter in bad terrain                   |   2
| Get up from a prone position                  |   2
| Remove your gauntlets                         |   4
| Remove your helmet                            |   4
| Drop a functional heavy shield                |   5
| Ready a spellbook from your backpack          |   5
//----------------------------------------------|------
|===

.Move economy
[IMPORTANT]
====
* Moves do not carry over to the next round; use them or lose them, they're
  gone as soon as you take your <<Actions,action>>.
//
* Effects and conditions, such as being <<prone>> or wearing broken armor
  can reduce your number of moves. But they can never be reduced to less than
  zero. So you can always convert your <<Actions,action>> into moves and get
  three moves that way.
====

=== Actions
When you have made your moves, you can take your action.
Here's some examples:

* Attack with a readied weapon.
* Unarmed attack.
* Drink a readied potion.
* Cast a spell with a readied spellbook via <<basic_spellcasting>>.
* Drop an heavy shield.
* Use a special ability.
* Get three extra moves.

[[attack_and_damage]]
=== Attacks & Damage

When you attack a baddie, you make an attack check. If you're making a ranged
attack, you make an <<adversarial>> _wisdom_ check, and if you're making
a melee attack you make an <<adversarial>> _dexterity_ check.

IMPORTANT: Your attack check is <<difficult>> if you're not
<<weapon_skills,skilled>> at using your weapon.

==== Damage Roll
When you've made an attack, and your attack check succeeded, you roll damage,
and the baddie loses that many <<hit_points>>

See the <<adventurer_damage_rolls_table>> table to find your damage die.

TIP: If you have the <<great_weapon_specialist>> special ability, you are also
skilled in using heavy melee weapons.

Critical hits::
If you roll a <<nat1>> on your attack check, you get an extra action for free.
You do not get any <<moves>>, but you can use your action any way you like,
including attacking the same opponent again.

[reftext="weapon wear"]
[[weapon_wear]]
==== Weapon Wear
If you roll a <<nat20>> on your attack check, you must roll a _charisma_ check.
If it failed, your weapon becomes unusable and must be repaired before it can
be used again. It can be repaired by an <<armorer>> or a weaponsmith, a process
that takes hours of work and requires a weaponsmith workshop.


=== Defense
When a baddie tries to attack you, you make a defense check. If it was a
ranged attack, you make an <<adversarial>> _wisdom_ check, and if it was
a melee attack, you make an <<adversarial>> _dexterity_ check.

==== Armor
You can wear up to five pieces of armor: a helmet, a cuirass, a gauntlet, of
greaves, and a shield.

[[armor_hit_points]]
===== Armor Grants Hit Points
Each piece of armor you wear increases your hit point total by a number of
points. The better the armor piece, the more hit points you get.

[quote]
A shield is an armor piece.

When you don an armor piece, your <<hit_point_total>> and your current number
of hit points both increase by the number of hit points provided by the armor
piece.

When you doff armor, your <<hit_point_total>> and your current number of hit
points both decrease by the number of hit points provided by the armor piece.

[quote]
You can die if you are very low on hit points and remove a functional
armor piece.

===== Armor Requires Skill
For each piece of armor you're wearing, if you're not skilled at using it,
you lose one <<Moves,move>>.

[[armor_wear]]
===== Armor Wears Out
If you are wearing at least one functional piece of armor, and you roll a
<<nat20>> on your <<Defense,defense check>>, one of the functional
<<Armor,armor pieces>> you are wearing (your choice) breaks and becomes
nonfunctional. A broken armor piece still provides <<hit_points>>, but
wearing it reduces your number of <<Moves,moves>> by one. This is cumulative
so if you're wearing 3 pieces of broken armor, you lose 3 moves.

[quote]
If you're wearing a piece of broken armor that you're not
<<armor_skills,skilled>> at using, that piece of armor is responsible for you
losing _two_ <<Moves,moves>>; one because you're unskilled, and the other
because the armor piece is broken.

.Armor wear
====
You've just been attacked and rolled a <<nat20>> on your defense check, and you
take 5 points of damage. You must now select an armor piece that has at least
one hit point, and that armor piece will also take some damage.

You have a Light Shield (2 hp), a Light Helmet (2 hp) and a Light Cuirass (3
hp). You choose the shield, and mark it as providing only one one hit point.

On top of the 5 points of damage you've just received, your total hit point
amount goes down by one, and your current number of hit points goes down by
one due to the armor damage.
====

==== Armor can be repaired
Armor pieces can be repaired. So you should make a note of how many hit points
the armor piece initially provided.

But only an <<armorer>> can restore the armor piece to its former glory.

=== Damage and Death
When you hit a baddie, you roll a damage roll to see how many points of damage
you deal. The dice used in the damage roll depends on your class, your
abilities, and the weapon (or spell) you used in the attack. Your opponent
subtracts your damage from their current number of hit points. If a baddie is
reduced to zero hit points (or below) they die instantly.

==== Taking damage
The GM tells you what the damage die is, and you roll it, and subtract the
result from your hit points.

IMPORTANT: You can never go below zero hit points; when you have reached
0 HP, any further damage will result in <<trauma_table>>.

==== Baddies With Zero Hit Points
Baddies die when they reach 0 HP. The only way to bring them back is to revive
or resurrect them with powerful magic. If you want to stun a baddie, you can
use certain items, spells, and abilities.

[[zero_hp]]
==== Adventurers With Zero Hit Points
If you reach 0 hit points, you permanently decrease a random stat by one point,
and then you must roll on the <<death_table>>.

.Reaching zero hit points
[example]
--
You have 4 HP left, and an angry troll hits you for 12 points of damage. You're
brought down to zero HP.

You roll a d6 to find out which stat to reduce. You rolled a 2, so your
_dexterity_ is reduced by 1.

You now have to roll on the <<death_table>>: You roll a 53, meaning
you're unconscious and <<dying>>, which in turn means you will have to roll a
d20 every round from now on, and a <<nat20>> will result in your death.
--

===== Taking Damage At Zero Hit Points
If you take damage and you are already at zero hit points, you lose 1d4 points
from a random stat, and you must roll on the <<trauma_table>> and add the amount of
damage taken to your d100 roll.

.Kicking a player character while they're down
[example]
--
You’re have zero hit points, you have already rolled on the
<<death_table>> once (and survived, for now), and some dastardly baddie strikes you for
5 damage.

You first roll a d6 and a d4 to reduce one of your stats, you rolled a 6 and a
3, meaning your _charisma_ is lowered by 3 points.

You then roll on the <<trauma_table>> and add 5 to your d100 roll
(because you received 5 points of damage). You rolled _7+5=12_, meaning you did
not suffer any trauma effects, you lucky bastard.
--

==== Death Table

[reftext="death table"]
[[death_table]]
.Death Table
[%header,cols="^1,11",grid=none,frame=none,stripes=even]
|===
| d100          | Effect
//--------------|--------------------------------------------------
| 100           | You’re destroyed.
| 99            | You’re dead.
| 76-98         | You’re <<comatose>> and <<dying>>.
| 25-75         | You’re <<unconscious>> and <<dying>>.
| 02-25         | You’re <<unconscious>>.
| 1             | You’re still awake. At 1 HP, but <<prone>>.
//--------------|--------------------------------------------------
|===

*Destroyed*: You’re extremely dead; You must roll twice on the Trauma Table and
mark any temporary losses as Reversible. Only great resurrection magic,
accessible only to elites, can bring you back to life, and the costs of doing
so are grave.
+
*Dead*: You’re dead; you must roll on the <<trauma_table>> (in case
you are revived or turn into an undead).

*Dead, Dying, and Comatose*: These conditions are described in detail in the
<<CONDITIONS>> section.

==== Trauma Table
The trauma table is used when you take damage after being reduced to 0 hit
points.

[reftext="trauma table"]
[[trauma_table]]
.Trauma table
[%header,cols="^1,^2,8",stripes=even,frame=none,grid=none]
|===
| Roll      | Type          | Effect
//----------|---------------|------------------------------
| 101+      | Amputation    | Lose a random limb
| 100       | Permanent     | -1d4 to random stat
| 89-99     | Permanent     | -1d8 maximum hit points
| 90-98     | Reversible    | -1 moves
| 81-89     | Reversible    | -1 to _charisma_
| 71-80     | Reversible    | -1 unencumbered item slot
| 61-70     | Temporary     | -1 moves
| 51-60     | Temporary     | All checks are difficult
| 41-50     | Temporary     | -1d6 to random stat
| 31-40     | Temporary     | 1d8 to maximum hit points
| 21-30     | Reversible    | Battle scar
| 01-20     | -             | No trauma.
//----------|---------------|------------------------------
|===

*Amputation*: You lose an arm or a leg. Roll 1d4 to find out which. Roll
_dexterity_ or _constitution_ (your choice) if you succeed, you only lose half
the limb. Otherwise you lose all of it. Your limb can regrow if the restoration
spell is used.

*Permanent*: This trauma is permanent. There is no way to undo it or reverse it.

*Reversible*: This type of trauma can be reversed with powerful restoration magic.

*Temporary*: lasts for 1d20 days or it can be reversed with restoration magic.

[quote]
The restoration spells referred to here are not <<basic>>, and adventurers
cannot cast them themselves. You can find more info on such spells in
xref:heroes#[Hero’s Guide to doom & destruction & stuff].

=== Healing and regeneration
You can regain hit points in various ways, but you can never heal or be healed
beyond your <<hit_point_total>>.

*Resting*: Resting for 8 hours, at least six of which are spent sleeping, will
allow you to regenerate a bit; roll your <<recovery_die>>, and increase your
hit points by that number. Aside from sleeping, eating, and keeping watch, you
cannot do anything of consequence while resting.

____
You can regenerate 1d8 hit points after a meal, 6 hours of sleep,
and two hours of rest.
____

*Magical Healing*: Spells (such as <<_heal_x>>), potions, and powers often
allow you to instantly recover hit points, usually by rolling a number of
recovery dice.

== CONDITIONS

Conditions can affect characters and baddies.

//START_SORT //KEY:

//KEY:
[reftext="comatose"]
[[comatose]]
*Comatose*: You’re in a deep coma. If you receive conventional medical care,
you will wake up in a matter of hours; make a _constitution_ check every hour
to see if you wake up. If you receive magical healing, you will wake up in a
matter of minutes; make a _constitution_ check every minute to see if you wake
up.

//KEY:
[reftext="invisible"]
[[invisible]]
*invisible*: You are invisible. You cannot be targeted by creatures who rely
primarily on sight, and even so, if the creature relies partially on sight,
its <<attack_and_damage,attack checks>> against you are <<difficult>>.

//KEY:
[reftext="demoralized"]
[[demoralized]]
*Demoralized*: On your next turn you must spend all your moves (if possible)
retreating from your opponents. When you have done that, the demoralized
condition goes away.

//KEY:
[reftext="dungeon mad"]
[[dungeon_mad]]
*Dungeon Mad*: You've been in complete darkness in a dungeon or cave for too
long. Every hour you spend in total darkness in a dungeon or similar situation,
you must make a _wisdom_ check. If you fail, you lose 1 point from a random
stat. This check is <<difficult>> if you are alone in the darkness.

[reftext="encumbered"]
[[encumbered]]
*Encumbered*: All checks become <<difficult>>, meaning that you have to roll 3
points lower than you normally would to succeed.

//KEY:
[reftext="dying"]
[[dying]]
*Dying*: You’re near death; you must roll on the <<trauma_table>>. Every round,
at the beginning of your turn, you must make a d20 roll; if you roll a
<<nat1>>, you are no longer dying, but <<unconscious>>, and if you rolled a
<<nat20>>, you are dead.

//KEY:
[reftext="exhausted"]
[[exhausted]]
*Exhausted*: Same as <<encumbered>> AND your number of moves is halved, rounded
down.

//KEY:
[reftext="frightened"]
[[frightened]]
*Frightened*: You cannot move closer to what you believe is the source of
your fear. You have 2 fewer moves than normal.

//KEY:
[reftext="on fire"]
[[on_fire]]
*On Fire*: You are on fire. At the start of every round, just before you get to
act, you take 1d4 points of damage, and then you roll a _constitution_ check.
If you succeed, the fire goes out. If you failed, the fire persists, and if you
rolled a <<nat20>>, the damage die increases (for instance, from 1d4 to 1d6).

//KEY:
[reftext="poisoned"]
[[poisoned]]
*Poisoned*: You temporarily lose 1d4 points of a random stat every minute.
After rolling your stat loss, you make a _constitution_ check with
<<disadvantage>>. If successful, the poisoned condition is removed. You die if
any of your stats are reduced to zero. If you die from poison, only Greater
Revival can restore you back to life.

//KEY:
[reftext="prone"]
[[prone]]
*Prone*: You're prone on the ground, you must spend 1 <<Moves,move>> to get up.
While you are prone, you have four fewer <<Moves,moves>> than normal.

[WARNING]
If you're suffering from other effects that lower your number of <<Moves,moves>>,
you can be reduced to zero moves. Forcing you to convert your <<Actions,action>>
into more moves just to get up.

//KEY:
[reftext="restrained"]
[[restrained]]
*Restrained*: Your hands and feet are restrained. You have only one
<<Moves,move>> each round. Depending on the circumstances, the GM might allow
you to try and escape your bonds.

//KEY:
[reftext="starving"]
[[starving]]
*Starving*: Every day that you do not get at least one consumption of
<<rations>> or similar, you roll 1d20 for each of your <<Stats,stats>>. If you rolled
under a stat, that stat is reduced by 1.

//KEY:
[reftext="unconscious"]
[[unconscious]]
*Unconscious*: You are unconscious; if you receive any kind of healing, you
will wake up right away, otherwise you will wake up within 2d6 hours.

//END_SORT
//}}}

//{{{ MAGIC
== MAGIC

[reftext="spellbook"]
[[spellbook]]
=== Spellbooks
A spellbook is a magical tome, book, or scroll. It takes up one
<<item_slots,item slot>>, contains a single spell and can only be used if it
has enough magical charge.

Spellbooks need magical charge (<<usage_points>>) to work. When a spellbook
runs out of <<usage_points>>, it is depleted and unusable until it is recharged
(e.g. via <<basic_recharging>>). A spellbooks maximum <<usage_points>> depends
on the power and skill of its creator.

[quote]
Normal spellbooks only have a few usage point, and only very powerful tomes
have more.


[reftext="basic spellcasting"]
[[basic_spellcasting]]
=== Basic Spellcasting
You can cast <<basic>> spells directly from a <<spellbook>> if you
meet the requirements below. Unless otherwise specified in the spell's
description, it is an <<Actions,action>> to cast a spell.

Requirements::
* You must have a <<spellbook>> with the given spell inscribed in it.
* The spell must be <<basic>> (all spells in this document are <<basic>>),
  and it's level must not be higher than yours,
* You must not have cast any spells previously in this <<round>>.
* The <<spellbook>> must have at least one <<usage_points,usage point>>.
* You must be holding the <<spellbook>> open in both hands.
* You must be able to see, speak, read, and move your arms freely.

Procedure::
* Make an _intelligence_ check:
.. If successful, the spell takes effect, 
   and the spellbook loses one of its <<usage_points>>.
.. If unsuccessful, the spell fizzles, but no <<usage_points>> are lost.
.. If you rolled a <<nat20>>, spell fizzles and the spellbook instantly loses
   all its <<usage_points>>.


[reftext="basic ritual casting"]
[[basic_ritual_casting]]
=== Basic Ritual Casting
Some spells can be cast without exhausting the spellbook, but it takes more
time to do so.

Requirements::
* The spell must have the <<ritual>> property,
* The spellbook must have at least one <<usage_points,usage point>>.
* You must be able to see, read, speak, and move about.
* You must have the spellbook near you while the ritual is performed,
  as you will often refer to the book.
* You must have your <<magic_components>> on you, as you'll need them for your
  ritual.

Procedure::
. Spend 10 minutes chanting and reading from the spellbook. 
. Spend one <<consumption_check,consumption>> of <<magic_components>>.
. Make an _intelligence_ check:
.. If successful, you cast the spell.
.. If unsuccessful, the spell fizzles, but you can try again later. 
.. If you rolled a <<nat20>>, the spellbook loses all its <<usage_points>>.

[reftext="basic recharging"]
[[basic_recharging]]
=== Basic Recharging
Adventurers can recharge <<basic>> spellbooks, restoring them to their maximum
<<usage_points>>.

*Requirements*: The spell in the spellbook must be <<basic>>, and its level must
not be higher than yours.

*Procedure*: You start by spending one <<consumption_check,consumption>> of
magic components, followed by 30 minutes of ritualistic work. Then you make an
_intelligence_ check. If the check succeeds, you have recharged the spellbook,
back to its maximum <<usage_points>> otherwise you must try again.

==== Spell Properties
The properties of a spell is listed in bold font right underneath the spell's
name.

//START_SORT //KEY:

//KEY:
[reftext="basic"]
[[basic]]
*Basic*: All basic spells can be cast by adventurers, and all spells in this
document are <<basic>>. Higher level characters have access to more advanced
types of spells.

//KEY:
[reftext="caster level"]
[[caster_level]]
*Caster level*: The level of the caster (i.e. not the spell). The potency, duration, or
range of certain spell increases with the casters level.

//KEY:
[reftext="duration"]
[[duration]]
*Duration*: The duration of the spell.

//KEY:
[reftext="focus"]
[[focus]]
*Focus*: These spells cut their duration short and stop instantly if you cast
another spell, take damage, or stop focusing on keeping the spell going.

//KEY:
[reftext="level"]
[[spell_level]]
*Level*: The level of the spell. If the spell also has the  property,
_level_ is the level of the weakest version of the spell, meaning no versions
of the spell exists at a lower level that that.

//KEY:
[reftext="X"]
[[X]]
*X*: There are many versions of this spell, each with its own level. +
See the <<example_multilevel>> example.

//KEY:
[reftext="range"]
[[range]]
*Range*: The range of the spell.

//KEY:
[reftext="ritual"]
[[ritual]]
*Ritual*: These spells can be cast via <<basic_ritual_casting>>, but can also be
cast normally via <<basic_spellcasting>>.

//KEY:
[reftext="trance"]
[[trance]]
*Trance*: You must be seated to cast a trance spell, and you must remain seated
for its duration. +
//
The spell stops instantly if you:
    a) take damage,
    b) make a defense check,
    c) get up,
    d) make a <<Moves,move>>,
    or e) take an <<Actions,action>>. +
//
You can speak, breathe, and adjust
your position to remain comfortable, and nothing more.

//END_SORT

[[example_multilevel]]
.Multilevel spells (X)
====
<<_tragic_missile_x>> is technically not a single spell. It exists as _Tragic
Missile 1_, _Tragic Missile 2_, and so on all the way to _Tragic Missile 10_,
each level being more powerful than the last.

---
<<_ghost_mount_x>> also represents multiple spells, but since its description
says it's <<spell_level,level>> stem:[2+], there is no _Ghost Mount 1_. Only a _Ghost
Mount 2_, _Ghost Mount 3_, and so on.
====

//}}}

//{{{SPELLS
== SPELLS
All spells listed in this section are <<basic>> and can be used by adventurers.

// START_SORT ===

=== Alertness (X)
*Level 1+, <<focus>>*

Everyone within 3 meters of the caster gets <<advantage>> on checks that
involve spotting hidden things, traps, and enemies, The effect persists even if
they move further away from the caster. The spell ends when it has provided
advantage to 2·<<X>> checks in total (i.e. not to each recipient) or when the
caster stops focusing on the spell, whichever comes first.

=== Alluring Attraction (X)
*Level 1+, <<ritual>>, duration: <<X>> days*

Of the next <<X>>+1 _charisma_ checks you make, you have <<advantage>> on
checks that have a strong flirting component or involve physical attraction.

=== Animal Friendship (X)
*Level 1+, <<ritual>>, duration: <<X>>+1 hours (<<focus>>)*

You have <<advantage>> on all _intelligence_, _wisdom_, and _charisma_ checks
made to befriend or calm animals. If you meet a hostile animal, there is a
fifty percent chance that it becomes cautious instead of hostile when it sees
you

=== Armor (X)
*Level 1+, <<ritual>>*

You turn a nonmagical piece of clothing that you wear into a functional armor
piece that provides <<X>> <<armor_hit_points,hit points>>. You are skilled at
using the armor.

You can create a cuirass, gauntlets, greaves, and a helmet, but you cannot
create a shield.

The armor becomes nonmagical if it <<armor_wear,breaks>> during combat, if you
remove it, or if you sleep.

=== Banking Transaction (X)
*Level 2+, duration: 5 minutes*

You touch a magical <<bank_book>> and transfer coins into- or out of it. You
cannot bring the book’s balance below zero.

It takes <<X>> minutes to cast this spell, and it requires <<X>> gold pieces,
which are consumed by the spell (yes, you must have at least <<X>> gold pieces
on hand to withdraw your money).

The number of coins you can withdraw/deposit is 10·<<X>>·<<X>>·<<X>>
(i.e. 10·X³).

=== Bug Repellent (X)
*Level 1+, duration: <<X>> minutes*

You target a nonmagical item within <<X>> meters. The item starts emitting sounds
and odors that repel insects and other vermin. The spells area of influence is
a sphere with a radius of 2·<<X>> meters

This spell has no effects on non-vermin.

Vermin whose level is <<X>> or higher are completely unaffected.

Vermin whose level is lower than <<X>> must make a normal _wisdom_ check or move
out of the repellent area. Even if the check is successful, any other checks
made within the repellent area are <<difficult>>.

Mundane vermin, such as normal spiders, worms, ants, flies, wasps, etc. are
level 0. Supernatural vermin such as giant wasps, etc. are at least level 1.

=== Calm Animal (X)
*Level 1+*

You calm a hostile animal within 10+<<X>> meters and whose level isn't higher
than <<X>>. The animal no longer considers you and your party as threats, and
will simply wander away if possible.

____
Just because a monster may look like an animal, doesn't  mean it is affected
by this spell.
____

=== Club
*Level 1, duration: <<caster_level>>+5 rounds*

A magical wooden club appears in your hand. You are skilled at wielding this
one-handed weapon, and your damage die is 1d12 when doing so. The club
dissolves into dust after <<caster_level>>+5 rounds, or instantly if you let go
of it.

=== Instruction (X)
*Level: 1+, duration: 1 round*

You give a creature within <<X>> meters a one-word command and then make a
_charisma_ check. If you’re successful, the target will attempt to execute the
command as best it can, and as it understands the command, but only for one
round, and only if the command would not result in self harm.

This spell does not affect targets whose level is higher than <<X>>.

If the target’s level is lower than <<X>> the _charisma_ check is <<easy>>.

Any creature targeted by this spell will become hostile towards you, regardless
if they executed the command or not.

____
Commands such as »flee« and »run« are straight forward, but a command such as
»drop« can be interpreted in many ways (drop the thing you’re holding, or drop
<<prone>>, or drop the subject). Don't take for granted that the target of
this spell will fully understand the meaning or spirit your command.
____


=== Command Fire (X)
*Level 1, 
,
range: 2·<<X>> meters, 
duration: 2·<<X>> minutes (<<trance>>)*

When you've just cast the spell you select a fire. It can be as small as a
candle and as large as <<X>> square meters. You can now give the fire a
command:

*Candle*: You shrink a bonfire to the size of a candle.

*Bonfire*: You make a candle grow to the size of a bonfire, provided there is
sufficient fuel available.

*Grow*: If the fire is the size of a bonfire, it expands to take up an entire
square meter. If the fire is 1 square meter or larger, it expands a further
square meter. You can control the direction of the fire’s growth, but you can
only make it expand to areas where there is plenty of fuel.

*Reduce*: If the fire is larger than 1 square meter, it shrinks by 1 square
meter. If the fire is 1 square meter in size, it shrinks to the size of a
bonfire. If the fire is the size of a bonfire, it goes out, not producing any
additional smoke in the process.


=== Cure Exhaustion
*Level 1, <<ritual>>, range: _wisdom_ meter*

You target a willing person within range, and remove the <<exhausted>>
condition from them.

A creature that has been targeted by this spell becomes immune to it for 1
hour.


=== Danger Sense
*Level 2*

If you make a successful _charisma_ check, you get a sense, on a scale of 1 to
5, of how dangerous a given foe, group, situation, mechanism, substance, or
task.

[quote]
Context is important: a high level paladin might be dangerous to her foes, but
completely harmless to her friends.


=== Detect Magic
*Level 1, <<ritual>>, duration: _intelligence_ minutes*

You can see magical items, and items that are affected by spells, such as an
item with <<_illuminate_x>> cast on it. The item must be within _wisdom_
meters. To you, magical items start to glow after you've looked directly at
them for a bit. You need to take things slow if you want to scan everything
around you. The “glow” can penetrate clothes and paper, so a magical ring in a
pocket or a magical pen underneath a sheet of paper can be detected.

____
Items that have recently been repaired with <<_mend_x>> also glow faintly.
____


=== Detect Traps (X)
*Level 1+, <<duration>>: <<X>> hours (<<focus>>)*

You can sense if a trap is within 10+<<X>> meters, but you only know where it
is when the trap is within <<X>> meters of you.

=== Detect Undead (X)
*Level 1+, Duration: _wisdom_ hours*

You can feel when one or more undead creatures are within _wisdom_ meters of
you. You can detect undead creatures through most walls, but not it cannot
penetrate more than one meter of rock or one centimeter of lead. 

If the undead creature's level is lower than <<X>>, you are able to ascertain
its direction, otherwise you only know that the creature is present, not where
it might be.

=== Fey Flames (X)
*Level 2*

You target a point within _wisdom_ meters. Every object and creature within
<<caster_level>> meters of that point glows with a faint light as if on fire.
<<invisible,Invisible>> creatures and object can now be seen and targeted, but
attack checks against them remain <<difficult>>.

=== Fierce Fortune (X)
*Level 1, *

An ally within <<X>> meters gets <<advantage>>on their next
<<attack_and_damage,attack>> or <<Defense,defense check>>, provided it occurs
within <<X>>+1 rounds.

=== Flaming Fingers (X)
*Level 1, *

Jets of fire spew forth from your burning hands, scorching up to <<X>> adjacent
targets of your choice. If you make a successful _intelligence_ check, each
target receives 1d6+<<X>> damage, otherwise they receive 1d6 damage.

=== Friendliness (X)
*Level 1, <<focus>>

Your _charisma_ checks are <<easy>> for the next <<X>> minutes.

=== Furnace
*Level 2, <<trance>>, duration: up to 8 hours*

A bonfire within 10 meters becomes hot enough heat metal enough for forging.
The bonfire does not consume more wood that it would normally do, and
it does not radiate more heat than it normally would; it becomes hot by
keeping the heat close to the fire.

=== Ghost Mount (X)
*Level 2, <<focus>>, *

You construct a ghostly, translucent horse that only you can ride. It appears
instantly under you, so you’re instantly mounted. The horse increases your
movement rate such that, whenever you spend one move, you move up to <<X>> meters.
The mount has 2·<<X>> hit points, all its primary stats are 8+<<X>>.

A constructed being, a Ghost Mount is immune to charm, sleep, fear, illusions,
demoralization, and other mind-based spells, as well as spells where
_intelligence_, or _charisma_ checks affect the spell’s outcome.

The spell lasts up to 3·<<X>> rounds, but stops earlier if you stop focusing on it
or if you dismount.

=== Ghost Servant (X)
*Level 1, <<focus>>, *

You construct a ghostly, humanoid that only you can see, hear, or smell. You
can send it telepathic commands, and it will obey you to the best of its
abilities, and without question or hesitation.

The servant appears within 3·<<X>> meters, and must stay within 10·<<X>> meters.

* It can move up to <<X>> meters per round.
* Its primary stats are all 2·X, and its hit point total is also 2·X.
* It cannot hear, speak, read, write, or make sounds, but it does understand
  your telepathic commands. It can lift and carry <<X>> item slots.
* It cannot do difficult or demanding things such as disarming traps, but it
  can do simple tasks such as moving stuff or doing the dishes.
* It is immune to charm, sleep, fear, illusions, demoralization, and other
  mind-based spells, as well as spells where _intelligence_, or _charisma_
  checks affect the spell’s outcome.

The spell lasts 10·<<X>> minutes, until you stop focusing on it, or the servant
gets more than 10·<<X>> meters away.

=== Gills (X)
*Level 1+, <<ritual>>, duration:2+<<X>> minutes (<<focus>>)*

You and 1+<<X>> willing creatures within 4+<<X>> meters can breathe in water
(and only water).

=== Gloom (X)
*Level 1+, range: 2+<<X>> meters*

You target an object within range. The object emits a ghostly dark aura that
dulls all non-magical sources of light within 5+<<X>> meters reducing their
radius to 1 meter while they are within the effective range of the gloomy
object.

This spell also dulls magical light sources if their spell level or item level
is lower than <<X>>.

The dulled light sources cannot be seen by creatures more than 1 meter away
from them.

You cannot target an object that is currently being held, worn or touched by
another creature.

The gloomy area looks like dense fog when seen from the outside.

=== Heal (X)
*Level 1+, <<ritual>>, range: 3+<<X>> meters*

You heal a creature within range. It recovers <<X>> recovery dice.

=== Hurt (X)
*Level 1+, <<ritual>>, range: <<X>>+3 meters*

You target a creature in range that you can see. If you succeed an
<<adversarial>> _wisdom_ check, the creature loses <<X>>d8 <<hit_points>>,
otherwise it loses <<X>>d4 <<hit_points>>.

=== Illuminate (X)
*Level 1+, range: 2+<<X>> meters, duration: <<X>> hours*

You target an object within range. The object lights up with a steady and
bright light that illuminates a radius of 10+<<X>> meters.

You can attempt to cast this spell on the eyes of a creature within range,
effectively blinding it (if it uses eyes and light to see). It requires a
successful difficult _charisma_ check, and if the creature’s level is higher
than <<X>>, the spell fizzles.

You must make a successful _charisma_ check to cast this spell on an item
currently held, worn, or touched by a living creature, and if the creature’s
level is higher than <<X>>, the spell fizzles.

=== Intruder Alert
*Level 1, <<ritual>>, duration: _wisdom_ hours*

Upon casting the spell, you touch a door, tent flap, a lock, or similar
moveable object. If the object is disturbed by a creature (but not the wind), a
loud alarm will "`ring`" inside your head. The alarm is loud enough to wake you
up, but quiet enough that you don’t wake up screaming.

=== Invisibility to Stupidity (X)
*Level 1+, <<focus>>, duration: 5·<<X>> Rounds*

Creatures with an _intelligence_ lower than <<X>>+2 cannot see you, smell you, or
detect you in any way, not even by touch.

=== Jump (X)
*Level 1, *

When you cast this spell, you instantly jump <<X>>+1 meters in a direction of your
choice. You cannot reduce the length of the jump, but you can jump into a wall
or other obstacle. Doing so causes you to take 1d6 damage for each meter the
obstacle reduces your jump.

=== Lightning Touch (X)
*Level 1+, *

You touch an adjacent target, who then takes <<X>>d6 damage. After rolling
damage, you make a _wisdom_ check. If successful, the target is knocked
<<prone>>, and must spend a number of moves next round to get up.

If the target is wearing three or more pieces of metal armor, you have
advantage on the damage roll and the _wisdom_ check.

=== Mage Might (X)
*Level 1, <<focus>>, *

For the next <<X>> rounds, your _strength_ score becomes 15+<<X>>*0.5 (rounded
down).

=== Mage Torch (X)
*Level 2+, <<focus>>, range: <<X>>·5 meters*

You target a spot you can see within range. At that spot a magical ghostly
torch appears. By spending one <<Moves,move>> you can move the torch up to 5
meters to a spot you can see and that is within range.

If you move so that the torch comes out of range, the spell stops and the torch
vanishes.

The torch disappears after 8 hours.

=== Magical Reading
*Level 1, <<ritual>>, duration: 8 hours*

You cast this spell on a spellbook or mundane book. It allows you to safely
read the book without falling for any mental magical traps the text may hold.
It also allows you to decipher (but not cast) spells in spellbooks whose level
is three levels higher than yours.

=== Magical Stone
*Level 1*
You touch a nonmagical stone or slingshot no larger than your fist. It becomes
magical, and flies towards an enemy within _wisdom_ meters at great speed. The
stone automatically hits the opponent, dealing damage equal to three times your
level.

[quote]
The stone can only hit the baddie if there is a direct line between the
stone and the baddie. It cannot curve or fly around obstacles.


=== Mend (X)
*Level 1, *

You instantly repair a break, crack, scratch, or tear up to 5 + <<X>> centimeters
from an object within <<X>> meters that weighs no more than <<X>> kg. A nonmagical
<<Armor,armor piece>> can be mended, becoming fully functional, if it provides
no more than <<X>> <<armor_hit_points,hit points>>. A nonmagical weapon can be
mended, becoming fully functional, if it takes up less than <<X>>
<<item_slots>>. Once an item has been mended, it becomes slightly magical for
1 day; it cannot be mended in that period, and it will be detectable with
<<_detect_magic>>.

=== Mind Message (X)
*Level 1, *

You target a creature within 5 plus 5<<X>> meters, and telepathically send 10 plus
10<<X>> words to it. It can telepathically reply with the same number of words. If
the recipient makes a successful _charisma_ check, no one notices its distraction
while receiving and replying.

=== Mustrum’s Mundane Shroud (X)
*Level 2, <<ritual>>, duration: <<X>> days*

You select a magical item within 2 meters of you, weighing no more than <<X>> kg.

This spell completely hides the fact that the item is magical; only observers
with a level higher than <<X>> can detect the item’s magic, and that this spell
has been used to hide it.

=== Nostrum’s Magical Aura (X)
*Level 1, <<ritual>>, duration: <<X>> days*

You select a nonmagical item within 2 meters, weighing no more than <<X>> kg.

You give the item an invisible magical aura of your design. Anyone who uses
<<_detect_magic>>, identify or similar detection magic will think the item is
magical, and they will think the item has magical properties of your choosing.

Observers with a level higher than <<X>> can detect that this spell has been
cast, and that the item is nonmagical.

=== Phantasm (X)
*Level 1, <<focus>>*

You create a purely visual illusion of an object, creature, thing, or
phenomenon no bigger than <<X>> cubic meters and no longer than <<X>> meters on
a side.
You can make the phantasm appear anywhere you can see within 10·<<X>> meters,
and it must remain within that radius at all times. You can move the phantasm
<<X>> meters per round. The spell ends after 5·<<X>> minutes, if you stop
focusing on it, or if something substantial touches the phantasm (heavy smoke,
sandstorm, a creature, etc.).

Creatures that have a reason to disbelieve the phantasm (such as creatures that
rely heavily on scent and sound, or people who find the phantasm incompatible
with their sense of “what ought to be” can make an <<adversarial>> _charisma_
check to see the phantasm for what it is. The check is easy if the creature's
level is 2 or more higher than the caster's level, and difficult of the
creatures level is 2 or more lower than the caster's level.

=== Purify Rations (X)
*Level 2, <<ritual>>*

You purify 1 ration pack and 1 water skin’s worth of liquid per level of this
spell. The food and drink is completely safe to eat and drink; it does not
taste bad, and it is nourishing. This spell does not remove curses or other
magical effects that may affect the food and drink.

=== Read Script
*Level 2, <<ritual>>, duration: 10·_intelligence_ minutes*

You can read and understand any written language. This spell does not decode
cryptographic cipher text, but it does let you understand secret languages.

=== Remove Fear (X)
*Level 2+, range: _charisma_ meters*

You target an ally within _charisma_ meters of you. The spell automatically
removes <<X>> fear-based conditions such as <<demoralized>>.

If the target suffers from more than <<X>> fear effects, the GM chooses which to
remove.

[quote]
There are more fear effects than the ones described in this guide.

=== Shield (X)
*Level 1+, <<focus>>*

For the next 5·<<X>> rounds, all damage you receive is halved (rounded down).

[example]
If a baddie hits you for 5 points of damage, you only take 2 points of damage.
And if you’re hit for 1 point of damage, you take zero points of damage.

=== Slow (X)
*Level 1+, <<focus>>: _X_ rounds*

You target a baddie within 2·<<X>> meters. For the duration of
this spell, the target creature has zero <<Moves,moves>>.


=== Slow Fall (X)
*Level 1+, <<ritual>>*

You touch  a nonmagical wearable item, weighing at least one
<<item_slots,item slot>> and worth at least <<X>> silver pieces. The item
becomes a <<consumption_check,consumable>> magical item with <<X>>
<<usage_points>>. When the wearer of such an item falls more than one meter,
the magic in the item activates and the fall is slowed so the wearer does not
take any damage. When the wearer has landed, the item loses one usage point.
When all the item’s usage points have been spent, the item crumbles to dust.

=== Snooze (X)
*Level 1+*

This spell can send one or more creatures to sleep, but it can only affect
creatures that need regular sleep, and whose level isn't higher than <<X>>.

Select a baddie within 10 meters. If the target has more hit points than your
_charisma_, the spell fizzles, otherwise the baddie falls asleep.

If the spell didn't fizzle, you may make another _charisma_ check, and if it
succeeds, the spell affects <<X>> additional creatures within 5 meters of the
first target.
//
This spell affects baddies and allies alike; these extra affected creatures are
selected in order of closeness to the first target.

Creatures sleep for a number of rounds equal to your _charisma_, however a
sleeping baddie wakes up if they take damage.

=== Spenser’s levitating Bowl
*Level 1, <<ritual>>, duration: _intelligence_ · 10 minutes*

You conjure a large vaguely bowl-shape plate that can carry as many
<<item_slots>> as your _strength_ score.

It levitates about a meter above the ground, and can move half as fast as an
adventurer. It is able to “climb” stairs and hills, but cannot scale walls or
steep cliffs.

=== Spider Climb (X)
*Level 1+, <<focus>>*

This spell enables you to cling to almost any surface as long as it is not
overly wet, oily, or slippery. You can spend 3 moves to spider-move 1 meter.
The spell lasts <<X>> minutes, but ends if you stop focusing on it.

=== Spout (X)
*Level 1+ <<focus>>*

You cause 10·<<X>> liters of water to pour out of a wineskin, teapot, keg, or
similar; at a speed of about 1 liter per round (10 liters per minute)

=== Strength of Stone (X)
*Level 1+, <<focus>>, <<ritual>>*

You target a willing ally within 2·<<X>> meters, making all their _strength_ checks
easy for a 2·<<X>> rounds.

=== Taunt
*Level 1+, duration: 1 round*

You target <<X>> creatures within 10+<<X>> meters. For each target, if you can make
a successful <<adversarial>> _charisma_ check (which is difficult if the
target’s level is higher than yours), the target will rush and attack you in
melee combat on its next turn.

=== Tragic Missile (X)
*Level 1+, range: _wisdom+X_ meters*

You fire a frightening magical missile against a baddie within range. When
struck, the baddie takes <<X>> d4 damage, and then you make an
<<adversarial>> _charisma_ check; if successful the baddie
becomes <<demoralized>>.

=== Vines (X)
*Level 2, <<focus>>*

You target a point within 10+<<X>> meters. Vines and wild growth sprouts from the
ground in  a radius of <<X>> meters around that point. Each creature inside the
affected area must make a successful _strength_, _dexterity_ or _intelligence_
check (their choice) each round, or all they have zero moves that round.

=== Wizard’s Mark
*Level 1, <<ritual>>, <<focus>>*

Makes a piece of chalk magical so it makes invisible marks that only you can
see.

Other than being invisible, the marks behave as normal chalk marks, which means
they can be rubbed out or washed away with water.

The chalk stops being magical once you stop focusing on the spell, or after
_charisma_ hours. But the marks remain visible to you, and invisible to others.

=== Burial (X)
*Level 1+, <<ritual>>*

<<X>> corpses of your choice within _charisma_ meters will not automatically
become undead. This spell doesn't work if the corpse's level is higher than
yours.

//END_SORT

//}}}

//{{{DICTIONARY

== DICTIONARY

//START_SORT //KEY:

//KEY:
*Adventurer*: All PCs start out as adventurers and have to level up to level 3
before they can get their hero class.

//KEY:
*Adversarial check*: A check that is affected by the level of the opposition.
For instance, if you're attacking a baddie who is 2 or more levels higher than
you, your check is difficult.

//KEY:
*Attack check, melee*: A check to hit an opponent. It's an <<adversarial>>
_strength_ check, and it is difficult if you're not skilled at using the given
weapon.

//KEY:
*Attack check, ranged*: A check to hit an opponent. It's an <<adversarial>>
_wisdom_ check, and it is difficult if you're not skilled at using the given
weapon.

//KEY:
*Baddie*: A person, creature, or monster that is hostile or otherwise
considered to be your enemy.

//KEY:
*Check*: You roll your d20 against a given target number (usually one of your
stats). _For example: when rolling a strength check you roll a d20 and must
roll lower than your strength to succeed.

//KEY:
*Defense check, melee*: A check to avoid being hit by melee attacks. This is an
<<adversarial>> _dexterity_ check.

//KEY:
*Defense ranged, melee*: A check to avoid being hit by ranged attack. This is
an <<adversarial>> _wisdom_ check.

//KEY:
*Difficult*: Difficult checks have a target number that’s 3 lower than normal
checks.

//KEY:
*Easy*: Easy checks have a target number that's 3 higher than normal checks.

//KEY:
*GM*: The Game Master.

//KEY:
*Hit Points (HP)*: A unit of health: your character has a number of hit points,
you lose some of them when you take damage, and if you lose all of them, you
must roll on the <<death_table>>.  _Baddies and NPCs also have hit points, and
when they lose all of them, they die._

//KEY:
*Initiative*: A check made at the beginning of a combat round to see which side
gets to act first.

//KEY:
*Level (lvl)*: A character can have a level between 1 and 10. Baddies, traps,
locks, spells, and various tasks can also have a level.

//KEY:
*NPC and NPCs*: Non player character(s). These persons and creatures are played
by the GM.

//KEY:
*PC and PCs*: Player Character(s).

//KEY:
*Proficient*: It is difficult or impossible to use an armor, weapon, or
specialist tool you are not proficient with.

//KEY:
*Roll*: Rolls are generic die rolls where you roll one or more specified dice,
such as _3d6_, _1d10_, _2d8+2_, etc. The most common type of roll is the damage
roll, where you roll your damage die for the type of weapon you're using.

//KEY:
*TN*: Abbreviation of Target Number.

//KEY:
*Target number*: The number you must roll below (usually with your d20) in
order to make a successful check.

//KEY:
*Y.A.R.I.S*: It’s an acronym: Yet Another Reduced Instruction Set.
//END_SORT

//}}}
