= Adventurer's Guide to Doom & Destruction & Stuff
// {{{ VARIABLES
:stylesheet: style.css
:doctype: article
:icons: font
:sectlinks:
:toc:
:toclevels: 1
:toc-placement!:
:experimental:
:stem:
:xrefstyle: full
:author: Kim Ravn Hansen
:email: moccalotto@gmail.com


:AHP: <<armor_hit_points,Hit Points>>
:IS: <<item_slots,Item Slots>>
:UP: <<usage_points,Usage Points>>
:_up: <<usage_points,usage point>>
:_ups: <<usage_points,usage points>>
:consumable: <<consumption_checks,consumable>>
:consumption: <<consumption_checks,consumption>>
:cost: <<_money,Cost>>
:elite_book: xref:elite[Elite's Guide To Doom & Destruction & Stuff]
:hero_book: xref:hero[Hero's Guide To Doom & Destruction & Stuff]
:link: icon:link[]
:one: <<nat1,One>>
:twenty: <<nat20,Twenty>>
// VARIABLES }}}

This document contains character creation and game mechanics, as well as gear,
spells, and abilities for characters of first and second level.

The first and second level is mainly about gritty survival, you must keep
track of your consumables such as rations and ammunition.

toc::[]

// {{{ ADVENTURERS SHEET
== ADVENTURER’S SHEET
The adventurer’s sheet has a bunch of fields for you to pencil in, and when
you’re done, you’re ready for adventure.

=== Stats
Your character has 6 primary stats:

[%unbreakable]
--
*Strength*: melee attacks, lifting, carrying, jock stuff. +
*Dexterity*: stealth, melee defense, unarmed combat, tricky tasks. +
*Constitution*: carrying capacity, surviving bad trauma. +
*Intelligence*: initiative, magic, tricky tasks. +
*Wisdom*: perception, ranged attack & defense. +
*Charisma*: luck, negotiation, charm magic, selling treasure.
--

Your starting stats range from 8 through 13 and cannot ever go beyond 15.

=== Extra Stuff

*Level (L)*: your level is a measure of your badassity. You start at a level 1
and become more and more badass as you gain levels. Baddies, spells, and
certain items and challenges also have levels. You gain new levels by acquiring
treasure and notoriety. Whenever we use the letter <<L>> in this document, we
refer to your level.

*Hit Points*: this is your current number of hit points. You can die or suffer
permanent injury if you <<zero_hp,run out of hit points>>. We sometimes refer
to hit points as HP.

[[hit_point_total,hit point total]]
*Hit Point Total*: is the maximum number of hit points you can have. I.e. the
number of hit points you have when you're at full health. This number increases
every time you gain a new level, and when you're wearing armor.

*Item Slots*: is the maximum number of <<item_slots,items>> you can carry. This
number is equal to your __constitution__.

*Moves*: is the number of meters you can move in a round. You can also use
moves to do other interesting <<moves,things>>.
// }}}


// {{{ CREATE YOUR ADVENTURER
== CREATE YOUR ADVENTURER
Go through the following sections, one by one, to create a new character.

=== 1. Stats
For each of your six stats in order, you roll 1d6+7 and assign the result to
that stat. Now each stat has a value between 8 and 13.

=== 2. Background & Fluff
Roll on each of the following tables to flesh out your character.

==== Vice
Roll a d12. If you roll a number that isn't on the table, you don’t have a vice.

[%header,cols="^1,11"]
|===
| 1d12  | Vice
//------+--------------------------
| 1-5   | No vice
| 6     | Risk taking
| 7     | Attention seeking
| 8     | Bar fighting
| 9     | Drinking
| 10    | Fornicating
| 11    | Gambling
| 12    | Stealing
//------+--------------------------
|===


==== Background
Your background is what you used to do before you found out you had the
Adventurer's Blessing. Roll a d6 and a d20. If the d6 rolled an even number,
pick your background from the left column, otherwise pick your background from
the right column.

[%header,cols=2*a]
|===
//---------------------+------------------------
| d6 rolled 1, 3, or 5 | d6 rolled 2, 4, or 6
|
. Apothecary
. Baker
. Banker
. Bartender
. Butcher
. Carter
. Chandler
. Chef
. Clergy
. Clerk
. Companion
. Cook
. Courier
. Courtier
. Doctor
. Entertainer
. Farmer
. Fisherman
. Foreigner: roll again for original background
. Gambler
|
. Gold Smith
. Hunter
. Hustler
. Laborer
. Lazy spouse
. Magician’s apprentice
. Merchant
. Monestarian
. Musician
. Notary
. Officer
. Prisoner
. Royalty
. Sailor
. Scribe
. Smith
. Solder
. Squire
. Street urchin
. Thief
//---------------------+------------------------
|===

[quote]
Consult the GM when making checks that you think could be helped to your
background; you might get an <<advantage>>.


=== 3. Adventuring Gear

All characters start with the following equipment:

[%unbreakable]
--
* A backpack.
* An <<adventurers_logbook>>.
* 2 <<torch,torches>>.
* A <<melee_weapons,light melee weapon>>.
* Three normal <<rations,ration packs>>.
* A set of common clothing.
* A bedroll.
--

*In addition to that:* Roll on each of the following tables to find out what
additional equipment your character starts with.



==== Ranged weapon
Roll 1d6 on this table to find out if you have a ranged weapon.

[%unbreakable]
--
[%header,cols="^2,10"]
|===
| d6  | Weapon
//----+----------------------------
| 1-2 | No ranged weapon
| 3   | Throwing Weapon (dagger, axe, or javelin)
| 4   | Slingshot + Bag of stones
| 5   | Bow + Quiver of arrows
| 6   | Crossbow + Quiver of bolts
//----+----------------------------
|===
--


==== Shield
Roll 1d6 on this table to find out if you have a shield.

[%unbreakable]
--
[%header,cols="^2,10"]
|===
| d6    | Shield
//------+----------------------------
| 1-4   | No shield
| 5-6   | Light Shield
//------+----------------------------
|===
--


==== Armor Pieces
Roll 1d6 on this table to find out what armor you have.

[%unbreakable]
--
[%header,cols="^2,10"]
|===
| d6    | Armor
//------+----------------------------
| 1-2   | No armor
| 3-4   | Light Cuirass
| 5-6   | Light Cuirass and Helmet
//------+----------------------------
|===
--

==== Utility Gear

Roll once on <<utility_gear_1>>.

[%unbreakable]
--
[[utility_gear_1]]
.Utility Gear 1
[%header,cols="^1,11"]
|===
| 1d10 | Item
//-----+-----------------------
|   1  | <<iron_rations>>
|   2  | Grappling hook + 10 meter rope
|   3  | <<storm_lantern>>
|   4  | Rope, 25 meters
|   5  | <<kosh>>
|   6  | Ball bearings
|   7  | Shovel
|   8  | <<lockpicking_tools>>
|   9  | <<lantern>>
|   10 | <<purse_copper>>
//-----+-----------------------
|===
--

Roll twice on <<utility_gear_2>>; if the two rolls are the same, reroll both
until you have two different rolls.

[%unbreakable]
--
[[utility_gear_2]]
.Utility Gear 2
[%header,cols="^1,11"]
|===
| 1d10 | Item
//-----+-----------------------------
| 1    | 2d6 gold pieces
| 2    | <<spellbook,Spellbook>> with 2 <<usage_points>> (the <<GM>> chooses the spell)
| 3    | <<torch,Torch>>
| 4    | <<spikes,Spikes>>
| 5    | <<tinkering_tools,Tinkering tools>>
| 6    | Pole, 3m, foldable
| 7    | Chalk
| 8    | <<rations,Ration pack, normal>>
| 9    | <<lamp_oil,Lamp oil>>
| 10   | <<map_making_tools,Map making tools>>
//-----+-----------------------------
|===
--


=== All Done
Now it’s time to read about the adventurer class and then check out the
sections on dice checks and combat.

// }}}


// {{{ ADVENTURER
== ADVENTURER

[quote,Baron LeDique]
Adventurers are brave, eager, and dangerous.

All characters start out with the same class: Adventurer.

=== Level 1

[[hit_points,hit points]]
==== Hit Points
Your __hit point total__ is 8, which means that, under normal
circumstances, you can’t have more than 8 hit points. When you have lost all
your hit points, you have to roll on the <<death_table>>.

[[armor_skills]]
==== Armor Skills
You are skilled at using light armor pieces. See also <<armor_skills>>.


[[weapon_skills]]
==== Weapon Skills
You are skilled at using ranged weapons and light melee weapons. See also
<<adventurer_damage_rolls_table>>.

==== Adventurer's Blessing

An adventurer is not just someone who chooses to go on adventures, the blood in
their veins is magical, and it makes them formidable and among the only
persons who can be magically revived.

[quote,Margot LeDique]
The Adventurer's Blessing is stunningly powerful; many nations want former
adventurers of high levels in key military and governing positions, as the
ability to be revived can be, well, vital for the continuation of the position.


==== Exotic Weapon Skills
You are __not__ skilled at using any exotic weapons such as the <<kosh>>.
Becoming skilled with such weapons require special training or abilities (such
as <<shady>>).

==== Spellcasting
You can use <<basic_spellcasting>> to cast <<basic>> spells quickly directly
from a <<spellbook>>, draining it fairly fast. You can also use
<<basic_ritual_casting>> to very slowly cast <<ritual,certain spells>>,
draining your spellbook much less. You can also use <<basic_recharging>> to
recharge depleted spellbooks.


=== Level 2
When you reach second level, you gain more hit points, better stats, and a
special ability.

==== More Hit Points, More Better
Your __hit point_total__ is increased by 1d8. Roll with <<advantage>>.

==== Better Stats
Roll a d20 and select a stat that is lower than the result of the die roll.
Increase that stat by 1 point. If no stats are lower than your die roll,
increase your lowest stat by 1.

==== Adventurer’s Special Ability
Choose one of the abilities below. Your choice is not permanent; you can switch
this ability at later levels.

//START_SORT //KEY:

//KEY:
[[armorer,armorer]]
*Armorer*: You obtain a set of <<tinkering_tools>>, and you can can repair
damaged and broken weapons as well as armor pieces using those tools.


//KEY:
[[backstabber,backstabber]]
*Backstabber*:
If an adjacent baddie moves away from you, you can make a melee attack against
them with a readied melee weapon you are skilled at using. When you do so, you
have __advantage__ on the <<attack_and_damage,attack check>> and the damage roll.

//KEY:
[[everdeen,everdeen]]
*Everdeen*:
If you are without arrows during combat, you can spend 3 moves, and make a
__charisma__ check. If successful, you somehow have a single extra arrow and
you’re ready to fire. If unsuccessful, you cannot use this ability before you
have stocked up on ammunition. This ability also works with bolts, slingshot,
and darts, but not thrown weapons such as daggers and javelins.


//KEY:
[[great_weapon_specialist,great weapon specialist]]
*Heavy Weapon Specialist*: You are skilled at using heavy melee weapons, and
when doing so, your damage die is 1d12.


//KEY:
[[infantry,infantry]]
*Infantry*:
You are able to use <<polearm,polearms>>.

//KEY:
[[medic,medic]]
*Medic*: 
You can augment magical healing and natural regeneration. You spend 30 minutes
administering to a wounded individual; during that time all checks and rolls
made to heal the patient (for instance to determine how many <<hit_points>> the
patient regains) have <<advantage>>. This does not apply to "area of effect"
healing. This augmentation can apply to regeneration via <<rest,resting>>,
provided you administer to the patient right as they start the rest.

//KEY:
[[monstrous_gourmand,monstrous gourmand]]
*Monstrous Gourmand*:
You can make edible ration packs from fresh monster parts (any recently dead
creature will do) It requires sharp cutting instruments, a large pot, a bonfire
(or equivalent source of heat), one hour of work, and a successful
__intelligence__ check to create one ration pack. A medium sized creature
“contains” 3 ration packs. In addition to creating rations, you are also able
to eat fresh, uncooked, monster meat without getting sick. It requires a sharp
cutting tool, 3d6 minutes, and a successful __constitution__ check to create
and eat such a “meal”.


//KEY:
[[negotiator,negotiator]]
*Negotiator*:
You have <<advantage>> on checks that involve negotiation, including
<<haggling_check>>.


//KEY:
[[pugilist,pugilist]]
*Pugilist*:
You are skilled at unarmed combat, and your unarmed combat damage die is 1d6.


//KEY:
[[rider,rider]]
*Rider*:
You acquire a trained horse for free (tamed wild horse, a gift, or similar).
You become skilled at riding horses. You have <<advantage>> on all
riding-related checks. You have <<advantage>> on {consumption} for animal feed.
When you reach level 5 your riding skill expands to all rideable land
creatures. At level 8, you can ride virtually any willing creature.

[%collapsible]
.A Rider's Mount
====
*Your horse* can drag a cart that can either carry you and two others, or you
and 20 <<item_slots>> of cargo. When you ride it or direct it, it can move 2
meters for every <<moves,move>> you make, and it has the same stats and hit
points as you, except for __intelligence__, which is 2. The horse generally does
what you want when you're in the saddle, but you have to succeed a __charisma__
check (with <<advantage>>) to command it when you're not.

*Feed*: You can feed your horse __animal feed__, and if you can't you can feed
it with <<rations>>, but the horse eats so much that you will have to make two
<<consumption_checks>> per day.

*If you lose this ability* (by changing it at later levels), you do not lose
your mount, but your rolls are no longer made with <<advantage>>.
====


//KEY:
[[ritualist,ritualist]]
*Ritualist*:
You have <<advantage>> on <<consumption_checks>> with <<magic_components>> and
you have <<advantage>> on the __intelligence__ check used for
<<basic_ritual_casting>>.

//KEY:
[[shady,shady]]
*Shady*:
On a successful __charisma__ check you pull out a dagger from a boot, a sleeve
or… somewhere. If your check fails, you cannot do it again for the rest of the
session. In combat, this feat requires 3 moves. You are also skilled at using a
<<kosh>>, something normal adventurers are not.

[quote]
The gods do not smile on people who use this ability to get rich by selling
daggers.


//KEY:
[[spelunker,spelunker]]
*Spelunker*:
You cannot go <<dungeon_mad>>,
you always have some chalk,
you always know the cardinal directions,
and have <<advantage>> on checks that involve navigation in caves and dungeons.
//
You also have <<advantage>> on <<consumption_checks>> checks for <<lamp_oil>>,
<<lantern,lanterns>>, and <<torch,torches>>.
//
Moreover, at any time, one of the ropes you carry does not take up any
<<item_slots>>.


//KEY:
[[thrifty,thrifty]]
*Thrifty*:
You have <<advantage>> on <<consumption_checks>> with <<coin_purse,coin
purses>>.


//KEY:
[[traveler,traveler]]
*Traveler*:
You have <<advantage>> on <<consumption_checks>> for <<rations>> and animal
feed, you always know the cardinal directions, and you have <<advantage>> on
checks related to geography, travel, and navigation. Additionally, at any time,
one of the ration packs you carry does not take up any <<item_slots>>.

//END_SORT


=== Level 3: Hero
You gain your hero specialization. You can find more info about the hero
specialization classes in the {hero_book}.

*NOTE*:
Even though you gain a heroic class at 3rd level, you're still an adventurer;
you still have the <<_adventurers_special_ability>>, the
<<_adventurers_blessing>>, as well as the other abilities adventurers have,
such as <<basic_spellcasting>>. You only lose an ability if your heroic class
explicitly prevents you from having it.

//}}}


//{{{DICE
== DICE
You can make rolls and checks with your dice. A roll is any kind of roll such
as 1d6, 2d4, 3d6+3, etc. A check is a special kind of roll described below.

=== Checks
You make checks to see if your character can successfully do certain
interesting things; you roll your d20. The check is successful if you roll
__no higher__ than a specified __target number__. 

The __target number__ is usually one of your stats.

.Checks & Target Numbers
====
*BASIC EXAMPLE*:
If the target number is 10, you must roll 10 or lower to succeed.

*CONCRETE EXAMPLE*:
You want to lift something really heavy, so the GM tells you to make a
__strength__ check. Your __strength__ is 12. You must roll 12 or below to
succeed. You roll a 13, which isn't a success.
====

[[nat1,1]]
*Rolling a One*: Checks are always successful if you roll a 1 on your d20.
Furthermore, depending on the type of check, other positive effects may occur.

[[nat20,20]]
*Rolling a Twenty*: Checks are always unsuccessful if you roll a 20 on your d20.
Furthermore, depending on the type of check, other negative consequences may occur.

[[adversarial,adversarial]]
=== Adversarial Checks
These are checks where the difficulty depends on the level of the adversary. In
this context, and adversary can be any type of obstacle, such as a baddie, a
lock, a trap, a riddle, or similar.

If the adversary is two or more levels above you, your checks against them have
<<disadvantage>> and if the adversary is two or more levels below you, your
checks against them have <<advantage>>.

.Adversarial Checks
====
A second level adventurer is trying to attack an evil orc who is level 5. This
attack check has <<disadvantage>> because the orc is two or more levels above
the adventurer. Had the orc been level 3, the check would not have had
<<disadvantage>>.

---

A level 3 adventurer is trying to haggle with a level 1 merchant to get a good
price on some loot. This <<haggling_check>> has <<advantage>> because the
adventurer is two levels above the merchant. Had the merchant (or indeed the
adventurer) been level 2 the check would not have had <<advantage>>.

---

A first level adventurer is attacking a second level zombie. The attack check
is normal because the level difference is less than 2.
====


=== Advantage & Disadvantage
Certain conditions, abilities, classes, and spells can give a roll an advantage
or disadvantage, which changes the way you roll the dice.

[[advantage,advantage]]
*Advantage*: If a roll has advantage, you roll the dice twice, and pick the
result you like best. For instance, if you have advantage on a damage doll, you
roll your damage dice twice and pick the roll you like best.

[[disadvantage,disadvantage]]
*Disadvantage*: If a roll has disadvantage, you roll the dice twice, and the GM
picks the result they like. For instance, if you have disadvantage on a check,
you roll the d20 twice and let the GM chose which die to use.

*Both = Neither*: If at least one advantage and at least one disadvantage
applies to the same roll, it becomes a normal without any advantage or
disadvantage roll.

//}}}


//{{{EQUIPMENT
== EQUIPMENT

=== Money
A gold piece (__gp__) is equivalent to 100 silver pieces, a silver piece (sp)
is 100 copper pieces (__cp__).

The weight of a few coins is negligible, but 100 coins take up one
<<item_slots,item slot>>.

[[item_slots,item slots]]
=== Item Slots
An average item uses up one item slot, but bulky or heavy items can use up
more. The number of item slots you can carry without penalty is equal to your
__constitution__. If your __constitution__ changes so does the number of item
slots you can carry.

[[overburden,overburden]]
*Overburdening*: You can use up all your item slots without any adverse
effects, but can carry up to __strength__ additional item slots by
overburdening yourself and being <<exhausted>> while doing so.

[[usage_points,usage points]]
=== Usage Points
Items that can be consumed or depleted (such as <<rations>>, arrows,
<<lamp_oil>>) have usage points. When you have used such an item you make a
consumption check to see if it loses a usage point. If the item run out of
<<usage_points>>, it is completely used up: no more arrows in the quiver, and
no more food in the ration pack.

[[consumption_checks,consumption checks]]
=== Consumption & Consumption Checks
You are sometimes asked to spend a __consumption__ of a given consumable item.
When making a __consumption__ of an item, you first roll a consumption check,
which is a <<Checks,check>> with a target number of 11 (meaning you must roll
10 or lower to succeed), and if the check wasn't successful, the item in
question loses a <<usage_points,usage point>>.

*Rations & Iron Rations*:
You must spend one __consumption__ of <<rations>> every day if you don't want
to <<starving,starve>>. This means that, once a day, you must make a
__consumption{sp}check__, and if it fails, one of your ration packs loses a
<<usage_points,usage point>>.

*Projectiles*:
If you have fired a ranged weapon that uses ammunition in combat, no matter how
many times you fired it, you roll a single __consumption__ check after the
combat to see if the ammunition loses a <<usage_points,usage point>>.

If you fire a ranged weapon while not in combat (while exploring a dungeon,
hunting, during a competition, or similar) you roll __consumption__ right away.

When your ammunition (quiver of arrows, bag of stones, etc.) has lost all its
<<usage_points>> it is gone,

[[melee_and_ranged,consumable thrown weapons]]
*Consumable Thrown Weapons*:
If you have thrown a throwable weapon in combat, no matter how many times
you threw it, you roll a single __consumption{sp}check__ after the combat
to see if the weapon loses a <<usage_points,usage point>>.

Your throwable weapon can also lose <<usage_points>> right away if you roll a
<<nat20>> on your attack check.

If your throwable weapon reaches zero <<usage_points>> it is completely used up
and cannot be repaired.

=== Gear

.General Gear
[%header,cols="7,^2,^3"]
|===
| Name                  | {IS} | {cost}
//----------------------+------+---------
| Backpack              |  0   | 5  sp
| Bedroll               |  1   | 1  sp
| Clothing, common      |  1   | 3  sp
| Clothing, poor        |  1   | 3  cp
| Clothing, wealthy     |  1   | 3  gp
| Flint and steel       |  0   | 2  cp
| Ladder, 2m            |  2   | 10 cp
| Pole, 3m foldable     |  2   | 5  cp
| Rope, 10m             |  1   | 2  cp
| Rope, 25m             |  2   | 10 cp
| Shovel                |  1   | 2  cp
| Steel bottle          |  1   | 25 sp
//----------------------+------+---------
|===


.Consumables
[%header,cols="5,^2,^2,^3"]
|===
| Name                                            | {IS} | {UP} | {cost}
//------------------------------------------------+------+------+-----------
| <<adventurers_logbook,Adventurer's Logbook>>    |   1  | 10   | 20 gp
| Animal Feed                                     |   2  | 1    | 15 cp
| Ball Bearings                                   |   1  | 20   | 15 cp
| Candles                                         |   1  | 6    | 25 cp
| Chalk                                           |   1  | 12   | 3  cp
| <<lamp_oil,Lamp Oil>>                           |   1  | 2    | 5  cp
| <<magic_components,Magic Components>>           |   1  | 2    | 1  gp
| <<iron_rations,Iron Rations>>                   |   1  | 2    | 4  sp
| <<rations,Rations>>                             |   1  | 1    | 1  sp
| <<spikes,Spikes>>                               |   1  | 2    | 1  sp
| <<lockpicking_tools,Lockpicking Tools>>         |   1  | 4    | 5  gp
| <<tinkering_tools,Tinkering Tools>>             |   2  | 4    | 10 gp
| <<torch,Torch>>                                 |   1  | 2    | 5  cp
//------------------------------------------------+------+------+-----------
|===


[%unbreakable]
--
[[armor_table]]
.Armor
[%header,cols="5,^2,^2,^3"]
|===
| Armor Piece           | {IS} | {AHP} | {cost}
//----------------------+------+-------+------
| Light Shield          |  1   |  3    | 8  gp
| Light Helmet          |  1   |  3    | 8  gp
| Light Cuirass         |  2   |  6    | 27 gp
| Light Gauntlets       |  1   |  3    | 8  gp
| Light Greaves         |  1   |  3    | 8  gp
//----------------------+------+-------+------
| Medium Shield         |  2   |   6   | 64  gp
| Medium Helmet         |  2   |   6   | 64  gp
| Medium Cuirass        |  3   |   9   | 125 gp
| Medium Gauntlets      |  2   |   6   | 64  gp
| Medium Greaves        |  2   |   6   | 64  gp
//----------------------+------+-------+------
| Heavy Shield          |  3   |   9   | 216 gp
| Heavy Helmet          |  3   |   9   | 216 gp
| Heavy Cuirass         |  4   |   12  | 343 gp
| Heavy Gauntlets       |  3   |   9   | 216 gp
| Heavy Greaves         |  3   |   9   | 216 gp
//----------------------+------+-------+------
|===
--

[[lodging]]
.Food and Lodging (per person per night)
[%header,cols="10,^2"]
|===
| Lodging                                   | {cost}
//------------------------------------------+--------
| Opulent (luxury apartment, finest food)   | 5  gp
| Middle class (small room, decent fare)    | 5  sp
| Poor (sleep in common room, cheap food)   | 50 cp
//------------------------------------------+--------
|===


[[melee_weapons,melee weapons]]
.Melee Weapons
[%header,cols="9,^2,^1"]
|===
| Melee Weapon                  | {IS} | {cost}
//------------------------------+------+--------
| Light Melee Weapon            |   1  | 3 gp
| Heavy Melee Weapon            |   2  | 8 gp
| <<kosh,Kosh>>                 |   1  | 6 gp
//------------------------------+------+--------
|===


:melee_ranged: (<<melee_and_ranged,Melee & Ranged>>)
.Ranged Weapons
[%header,cols="7,^2,^2,^1"]
|===
| Name                          | {IS} | {UP} | {cost}
//------------------------------+------+------+------
| Dagger  __{melee_ranged}__    |   1  |  1   | 3  gp
| Javelin __{melee_ranged}__    |   1  |  1   | 3  gp
| Small Axe __{melee_ranged}__  |   1  |  1   | 3  gp
| Dart                          |   1  |  4   | 3  gp
| Bow                           |   2  |  -   | 7  gp
| ↳ Quiver of Arrows            |   1  |  10  | 2  gp
| Crossbow                      |   1  |  -   | 12 gp
| ↳ Quiver of Bolts             |   1  |  10  | 2  gp
| Sling                         |   0  |  -   | 4  gp
| ↳ Bag of Slingshot            |   1  |  10  | 2  gp
//------------------------------+------+------+------
|===

[quote]
See <<weapon_range>> for more info on how far your ranged attacks can reach.

=== Special Items
//START_SORT //KEY:


//KEY:
[[adventurers_logbook,adventurer's logbook]]
==== Adventurer's Logbook
This special book is made from parchment from magical creatures. It highly
resistant to fire, water, and wear and tear. You can write impossibly fast in
this book; up to ten times your normal writing speed. You can easily and
swiftly transcribe writing from this book to another __adventurer's logbook__,
writing at up to fifty times your normal writing speed. Even when writing at
full speed, anything you write in this book is very legible, but this only
applies to text; any drawings you make depend completely on your drawing
skills.


//KEY:
[[bank_book,bank book]]
==== Bank Book
A bank book is a magical book that can contain money. There is a magical ritual
called <<_banking_transaction_x>>, that allows you to transfer money into and
out of the book.


//KEY:
[[coin_purse,coin purse]]
==== Coin Purse
Purses aren't real items; they are concepts that can simplify bookkeeping.
Instead of keeping track of every copper penny and doing a lot of math, you
just make consumptions whenever you buy something. You don't need to buy purses
from a merchant - you just "buy" them directly from the GM. You cannot sell
them or exchange them.

[[purse_copper,copper purse]]
*Copper Purse*: for 1,000 copper pieces you can buy a copper purse. It has 10
<<usage_points>>. Whenever you buy something costing less than 100 copper
pieces (i.e. less than 1 silver piece), you can spend one
{consumption} of this purse instead of spending coin.

[[purse_silver,silver purse]]
*Silver Purse*: for 1,000 silver pieces you can buy a silver purse. It has 10
<<usage_points>>. Whenever you buy something costing less than 100 silver
pieces (i.e. less than 1 gold piece), you can spend one
{consumption} of this purse instead of spending coin.

[[purse_gold,gold purse]]
*Gold Purse*: for 1,000 gold pieces you can buy a gold purse. It has 10
<<usage_points>>. Whenever you buy something costing less than 100 gold pieces
you can spend one {consumption} of this purse instead of
spending coin.


//KEY:
[[healing_salve,healing salve]]
==== Healing Salve
These salves can heal minor wounds: You spend one
{consumption} of salve, and five minutes to apply it to a
willing recipient. Once applied, the recipient rolls a number of dice (usually
a few d6), and regain that many hit points.

//KEY:
[[kosh,kosh]]
==== Kosh
Adventurers with the <<shady>> special ability are <<weapon_skills,skilled>> at
using the these weapons. To use a kosh, you make an attack check against the
baddie; if you hit it, it immediately loses 1 <<hit_points,hit point>>. You
then roll your damage die for light melee weapons. The baddie does not lose any
<<hit_points>>, but if the damage roll was higher than the baddie’s remaining
hit points, it falls <<unconscious>>, which means they’ll wake up within 2d6
hours unless they're healed.

[quote]
Aside from losing a single hit point, and potentially falling unconscious,
the target suffers no other ill effects from being struck with a kosh.

//KEY:
[[lamp_oil,lamp oil]]
=== Lamp Oil
This {consumable} item is flammable; you can use it as fuel
for your lantern or storm lantern, and you can use it to light things on fire.

You can throw lamp oil to cover an area; You first roll a __dexterity__ check.

[%unbreakable]
--
[cols="^2s,10"]
|===
//----------+----------------------------------------------------
| {twenty}  | You drop the container at your feet and it ruptures.
| Failure   | The container lands where intended, but it does not rupture.
| Success   | The container lands where intended, ruptures, and covers 1d4
              square meters (<<GM,GM's>> choice) in oil.
| {one}     | The container lands where intended, ruptures, and covers up to 4
              square meters (of your choice) in oil.
//----------+----------------------------------------------------
|===
--


//KEY:
[[lantern,lantern]]
==== Lantern
Lanterns illuminates the area around you. The lantern does not have have any
usage points itself, but it it does <<lamp_oil>>; it uses one consumption every
hour.

You can throw a lantern, using it to ignite an area. You roll a __dexterity__
check. If successful, the lantern lands where you want it to (within
__strength__ meters), and covers 1d4 square meters in flaming oil. Anyone
inside the affected area is set <<on_fire>>.

[[storm_lantern,storm lantern]]
*Storm Lanterns*: are a variant of the normal <<lantern>> that cannot be blown
out in normal storms and gales. But they cannot be used to ignite an area
either, as they are designed to go out when they aren't upright.


//KEY:
[[lockpicking_tools,lockpicking tools]]
==== Lockpicking Tools
These tools allow you to pick various locks. They can be used up, and therefore
have <<usage_points>>. To Open a Lock, you first spend 5 minutes and one
{consumption} of lockpicking tools. Then you make both a __dexterity__- and an
__intelligence__ check.

* If both are successful, you open the lock.
* If one is successful, the lock does not open, but you get to try again.
* If none are successful, the lock becomes jammed, and can only be opened by a
  key or by a lockpicker who is at least two levels higher than you. You may
  try again when you have gained two levels.


//KEY:
[[magic_components,magic components]]
==== Magic Components
Magic components are used when casting rituals and when recharging spellbooks.
A consumption of magic components means you use some unspecified amount of your
magic components which costs one {consumption} of your
magic components.


//KEY:
[[map_making_tools,map making tools]]
==== Map Making Tools
You can use these tools to maps of dungeons, cities, and various land areas. To
do so you must make an __intelligence__ check and a __wisdom__ check.

* If both are successful, your mapping process is accurate for the entire
  dungeon level, city, or area.

* If just one is successful, your map is slightly incorrect, and using it gives
  your related checks <<disadvantage>>.

* If both failed, the map is not accurate at all. Twists and turns are
  wrong, scales are wrong, the cardinal directions are wrong, and there are
  missing areas and notes.


//KEY
[[rations,rations]]
==== Rations
Rations sustain you on your adventures. You must use one {consumption} of rations every day, otherwise you become <<starving>>.

[[iron_rations,iron rations]]
*Iron Rations* have twice as many <<usage_points>> as normal rations, while
still only requiring one <<item_slots,item slot>>.


//KEY:
[[polearm,polearm]]
==== Polearm
Only <<infantry,infantrymen>> can use these weapons in any way. Polearms have a
special ability: by spending three <<moves>> and one <<Actions,action>> you can
attack a baddie who is two meters away from you, i.e. there is an entire
one-meter square between you and the baddie.

[quote]
The polearms damage die follows your damage die for heavy weapons, although
it can never be lower than 1d12.

//KEY:
[[restoring_salve,restoring salve]]
==== Restoring Salve
These salves can reverse the effects of <<reversible>> trauma. You spend one
{consumption} of salve, and 30 minutes to apply it to a willing recipient. Once
applied, one <<reversible>> trauma condition is removed from the recipient.


//KEY:
[[spikes,spikes]]
==== Spikes
When hammered in between the door and the wall or jamb, these 30 centimeter
spikes can wedge a door shut until the spikes are removed.


//KEY:
[[tinkering_tools,tinkering tools]]
==== Tinkering Tools
Tinkering tools can be used to disarm traps and repair broken items.

*Repairing Mechanisms*:
To repair a trap, mechanism, stuck door, or similar, you spend 10 minutes and
one {consumption} of tinkering tools. Then you make a
__dexterity__ check and an __intelligence__ check.

* If both are successful, you have repaired the item.
* If one is successful, the item is still damage, but you may try again.
* If both failed, you cannot fix this item until you've gained a new level.

*Repairing Armors*:
This is like repairing mechanisms, except: only <<armorer,armorers>> can repair
armors, and only __light armor__ can be repaired using tinkering tools alone;
__medium__ and __heavy__ armor also requires a furnace (or the <<_furnace>>
spell).

*Repairing Weapons*:
This is like repairing mechanisms, except: only <<armorer,armorers>> can repair
weapons, and it takes twice as long if the weapon is broken rather than
damaged.

*Disarming Traps*:
To disarm a trap you spend 10 minutes and one {consumption}
of tinkering tools. Then you make a __dexterity__ and __wisdom__ check.

* If both are successful, you have disarmed the trap.
* If one is successful, you did not disarm the trap, but you may try again.
* If both failed, the trap triggers, and you are not able to dodge the
  effects (if the trap is aimed at you).


//KEY:
[[torch,torch]]
==== Torch
Aside from illuminating the area around you, torches can be used for a number
of things.

Torches have 2 <<usage_points>>, and use a {consumption} every hour.

Torches can be revitalized; it requires one consumption of <<lamp_oil>> to
restore 1 <<usage_points,usage point>> to a torch. This cannot be done while
the torch is lit. After revitalizing your torch, you roll a __wisdom__ check
with <<disadvantage>>. If unsuccessful, the torch is destroyed, and cannot be
lit.

You can use your torch as a light melee weapon with <<disadvantage>>. If you
roll a <<nat20>> on your melee attack check, the torch breaks and cannot be
repaired. If you roll a <<nat1>>, the target is set <<on_fire>>, dealing 1d4
damage every round until it is put out.

You can throw a torch and use it as a ranged weapon with <<disadvantage>>. If
you rolled a <<nat20>> on your attack check, the torch is broken and cannot be
repaired. The throwing range of a torch is 5 meters.

This item takes up 1 item slot.

//END_SORT

=== Selling and Haggling
You buy things for price listed in this guide, but you cannot sell items at
that price. When selling something trivial or cheap, you sell it for 50% of the
listed value, but if you’re selling more precious things, you must make a
__haggling check__.

[[haggling_check,haggling check]]
*Haggling Check*:
If you’re selling expensive items, or if you’re selling things in bulk, you
must haggle to get a good price. You first roll a __charisma__ check, and refer
to the table below, and do what it says, even if you don't like the result.

[%unbreakable]
--
[cols="^2s,10"]
|===
//----------+----------------------------------------------------
| {twenty}  | You sell the item(s) for 25% of local list price.
| Failure   | You sell the item(s) for 50% of local list price.
| Success   | You sell the item(s) for 75% of local list price.
| {one}     | You sell the item(s) for 100% of local list price.
//----------+----------------------------------------------------
|===
--

.Negotiators
[TIP]
<<negotiator,Negotiators>> have <<advantage>> on haggling checks.


//}}}


//{{{ COMBAT
== COMBAT

This section is all about fighting 🤺

.Attack Types
****
*Unarmed Combat*:
Requires two free hands but does not suffer from <<_weapon_wear,weapon wear>>.
Only <<pugilist,pugilists>> are skilled at unarmed combat. See also
<<weapon_skills,weapon skills>>.

*Light Melee Weapons*:
These weapons, except quarterstaves, are one-handed. Adventurers are skilled at
using these weapons. See also <<weapon_skills,weapon skills>>.

*Heavy Melee Weapons*:
Require two hands. Only <<great_weapon_specialist,great weapon specialists>>
are skilled at using these weapons.
See also <<weapon_skills,weapon skills>>.

*Ranged Weapons*:
Ranged weapons is generally split into two 

*Projectile Weapons*:
Require ammunition and two hands.

*Throwing Weapons*:
Typically one-handed; certain throwing weapons (such as daggers and javelins)
can also be used as light melee weapons. See also <<melee_and_ranged>>.

[[weapon_range,range]]
*Range*:
The range of ranged weapons is a number of meters equal to the lowest of your
__strength__, __dexterity__, and __wisdom__; you cannot target baddies beyond
this range, and you cannot shoot into areas of complete darkness.

****

[[round,round]]
=== Rounds
Combat is divided into 10-second rounds. At the beginning of every round the
adventurers roll __initiative__, to determine in which order they get to act.

[%unbreakable]
--
During their turn, a combatant can do the following things in order.

. Make up to 5 moves.
. Take one action.
--


=== Initiative
At the beginning of every round each adventurer makes an __intelligence__
check. If the adventurers have more failed checks than there are combat capable
baddies on the battlefield, the baddies get to go first that round.

The players act in the order in which they sit around the gaming table,
clockwise from the GM, and the baddies act in whatever order the GM wishes.

[[moves,moves]]
=== Moves
You have 5 moves you can take before you take your main action. You can use
them in many ways, and here's some examples.

.Moves
[%header,cols="11,^1"]
|===
| Description                                   | Moves
//----------------------------------------------+------
| Move 1 meter in good terrain                  |   1
| Ready a potion from a belt pouch              |   1
| Draw a weapon from your sheath or equivalent  |   1
| Switch to a new quiver                        |   1
| Drop a light shield                           |   1
| Open a door                                   |   2
| Mount or dismount                             |   2
| Move 1 meter in bad terrain                   |   2
| Get up from a prone position                  |   2
| Reload a projectile weapon from quiver/bag    |   2
| Remove your gauntlets                         |   4
| Remove your helmet                            |   4
| Drop a functional heavy shield                |   5
| Ready a spellbook from your backpack          |   5
| Gain an extra <<Actions,action>>              |   5
//----------------------------------------------+------
|===

.Move Economy
****
Any moves you haven't used when you take your <<Actions,action>> are lost, and
if your convert your <<Actions,action>> into moves you lose any of those moves
that you did not use before your turn ended.

Effects and conditions, such as being <<prone>>, <<exhausted>>,
<<broken_armor,wearing broken armor>>, or being affected by spells such as
<<_slow_x>> can reduce your number of moves. But they can never be reduced to
less than zero. So you can always convert your <<Actions,action>> into moves
and get three moves that way.
****

=== Actions
When you have made your moves, you can take your action.
Here's some examples:

* Attack an adjacent baddie with a readied melee weapon.
* Attack a non-adjacent baddie with a ranged weapon.
* Unarmed attack against adjacent baddie.
* Drink a readied potion.
* Cast a spell with a readied spellbook via <<basic_spellcasting>>.
* Drop an heavy shield.
* Use a special ability.
* Get three extra moves.

[[attack_and_damage]]
=== Attacks & Damage

When you attack a baddie you make a so-called __attack check__ which is an
<<adversarial>> check with a stat that depends on the type of weapon you are
using; consult <<adventurer_damage_rolls_table>> to find out which __stat__ to
use, whether or not you are skilled at using the given weapon, and what your
damage roll is.

When you have made your attack check, consult <<attack_check_results_table>> to
find out what happens. Unless you rolled poorly on your attack check it is now
to to roll the damage die and reduce your opponent's hit pints accordingly.

[[adventurer_damage_rolls_table]]
.Adventurer's Attack and Damage
[%header,cols="6,^2,^2,^2"]
|===
| Weapon                | Stat        | Skill       | Damage
//----------------------+-------------+-------------+-------------
| Light Melee Weapons   | _Strength_  | Skilled     | 1d6
| Ranged Weapons        | _Wisdom_    | Skilled     | 1d6
| Heavy Melee Weapons   | _Strength_  | Unskilled   | 1d10
| Unarmed Combat        | _Dexterity_ | Unskilled   | 1d4
//----------------------+-------------+-------------+-------------
|===

[%unbreakable]
--
:weapon_wear: <<_weapon_wear,weapon wear>>
[[attack_check_results_table]]
.Attack Check Results
[cols="^2s,10"]
|===
//---------+-------------------------------------
| {twenty} | You miss and your weapon loses a {up} (see {weapon_wear}).
| Failure  | You deal half damage (rounded down) if you are
             <<weapon_skills,skilled>> with your weapon, otherwise deal no
             damage.
| Success  | You deal normal damage.
| {one}    | You deal maximum damage. If you are <<weapon_skills,skilled>> at
             using your weapon you also get an extra <<Actions,action>>.
//---------+-------------------------------------
|===
--

==== Weapon Wear
If your weapon loses all its <<usage_points>> it is broken and almost unusable
until it has been repaired. Attempting to use a broken weapon gives you
<<disadvantage>> on your attack check _and_ your damage roll.

*Thrown Weapons*: If a throwing weapon loses all its <<usage_points>> it is
simply gone and cannot be repaired.

=== Defense
When a baddie attacks you, you make a so-called __defense check__; if the
incoming attack is ranged your __defense check__ is an <<adversarial>>
__wisdom__ check, and if it is a melee attack the __defense check__ is an
<<adversarial>> __dexterity__ check.

When you have made your __defense check__ refer to
<<defense_check_results_table>> below to find out how well you defended
yourself.


[%unbreakable]
--
[[defense_check_results_table]]
.Defense Check Results
[cols="^2s,10"]
|===
//----------+-------------------------------------
| {twenty}  | You take maximum damage and your best armor piece <<broken_armor,breaks>>.
| Failure   | You take normal damage.
| Success   | You take no damage.
| {one}     | You take no damage and the enemy's weapon <<broken_weapon,breaks>>.
//----------+-------------------------------------
|===
--


==== Armor
You can wear up to five pieces of armor: a helmet, a cuirass, a gauntlet, a set
of greaves, and a shield.

[[armor_hit_points]]
===== Armor Grants Hit Points
Each piece of armor you wear increases your <<hit_point_total>> by a number of
points. The better the armor piece, the more hit points you get; see
<<armor_table>>.

When you don an armor piece, your <<hit_point_total>> and your current number
of hit points both increase by the number of hit points provided by the armor
piece.

When you doff armor, your <<hit_point_total>> and your current number of hit
points both decrease by the number of hit points provided by the armor piece.
This means that, technically, you can reach <<zero_hp,zero hit points>> by
removing armor.

===== Armor Requires Skill
For each piece of armor you're wearing, if you're not skilled at using it,
you lose one <<moves,move>>.

[[broken_armor]]
===== Broken Armor
If you are wearing at least one functional piece of armor and you roll a
<<nat20>> on your <<Defense,defense check>>, one of the functional armor pieces
you are wearing (your choice) breaks and becomes nonfunctional. A broken armor
piece still provides <<hit_points>>, but wearing it reduces your number of
<<moves>> by one. This is cumulative so if you're wearing 3 pieces of broken
armor, you lose 3 moves.

*Repairing Armor*:
<<armorer,Armorers>> can restore an he armor piece to its former glory by 
using <<tinkering_tools>>. Magic can repair nonmagical armor pieces via the
<<repair_x>> spell, though certain restrictions apply.

*Unskilled Usage of Damaged Armor*:
If you're wearing a piece of broken armor that you're not
<<armor_skills,skilled>> at using, that single armor piece causes you to lose
_two_ <<moves>>; one because you're unskilled, and the other because the armor
piece is broken.

=== Damage and Death

When you hit a baddie, you roll a damage roll to see how many points of damage
you deal. The dice used in the damage roll depends on your class, your
abilities, and the weapon (or spell) you used in the attack. Your opponent
subtracts your damage from their current number of hit points. If a baddie is
reduced to zero hit points (or below) they die instantly.

==== Taking damage
The GM tells you what the damage die is, and you roll it, and subtract the
result from your hit points.

[quote]
You can never go below zero hit points. But taking further
<<damage_at_zero_hp,damage>> is <<_trauma_table,traumatic>>.

==== Baddies With Zero Hit Points
Baddies die when they reach 0 hit points. The only way to bring them back is to
revive or resurrect them with powerful magic. If you want to stun a baddie, you
can use certain items, spells, and abilities.

[[zero_hp]]
==== Adventurers With Zero Hit Points
If you reach 0 hit points, you permanently decrease a random stat by one point,
and then you must roll on the <<death_table>>.

.Reaching zero hit points
====
You have 4 hit points left, and an angry troll hits you for 12 points of
damage. You're brought down to zero hit points.

You roll a d6 to find out which stat to reduce. You rolled a 2, so your
__dexterity__ is reduced by 1.

You now roll on the <<death_table>>: You roll a 53, meaning you're
<<unconscious>> and <<dying>>, which in turn means you will have to roll a d20
every round from now on, and a <<nat20>> will result in your death.
====

[[damage_at_zero_hp]]
===== Taking Damage At Zero Hit Points
If you take damage and you are already at zero hit points, you lose 1d4 points
from a random stat, and you must roll on the <<trauma_table>> and add the
amount of damage taken to your d100 roll.

.Kicked while you're down
====
You’re at zero hit points, you have already rolled on the <<death_table>> (and
survived, for now), and some dastardly baddie now strikes you for 5 damage.

You first roll a d6 and a d4 to reduce one of your stats, you rolled a 6 and a
3, meaning your __charisma__ is lowered by 3 points.

You then roll on the <<trauma_table>> and add 5 to your d100 roll (because you
received 5 points of damage). You rolled __59+5=64__, meaning you lose one
<<moves,move>> for 1d20 days.
====

==== Death Table

You're sure to receive a negative __condition__ or two when rolling on the
death table. Check the <<CONDITIONS>> section for more info.

[[death_table,death table]]
.Death Table
[%header,cols="^2,10"]
|===
| d100   | Effect
//-------+--------------------------------------------------
| 100    | You’re <<destroyed>>.
| 99     | You’re <<dead>>.
| 76-98  | You’re <<comatose>> and <<dying>>.
| 25-75  | You’re <<unconscious>> and <<dying>>.
| 02-25  | You’re <<unconscious>>.
| 1      | You’re still awake, but you are <<prone>> and only have
           one <<hit_points,hit point>>.
//-------+--------------------------------------------------
|===


==== Trauma Table
The trauma table is used when you take damage after being reduced to 0 hit
points.

[%unbreakable]
--
[[trauma_table,trauma table]]
.Trauma Table
[%header,cols="^2,^2,8"]
|===
| Roll  | Type       | Effect
//------+------------+------------------------------
| 101+  | Amputation | Lose a random limb.
| 100   | Permanent  | -1d4 to random stat.
| 89-99 | Permanent  | -1d8 maximum hit points.
| 90-98 | Reversible | -1 <<moves>>.
| 81-89 | Reversible | -1 to __charisma__.
| 71-80 | Reversible | -1 <<item_slots,item slot>>.
| 61-70 | Temporary  | -1 <<moves,move>>.
| 51-60 | Temporary  | All checks have <<disadvantage>>.
| 41-50 | Temporary  | -1d6 to random stat.
| 31-40 | Temporary  | -1d8 <<hit_point_total>> and current hit points.
| 21-30 | Reversible | Battle scar.
| 01-20 | -          | No trauma.
//------+------------+------------------------------
|===
--

*Amputation*: You lose an arm or a leg. Roll 1d4 to find out which. Roll
__dexterity__ or __constitution__ (your choice) if you succeed, you only lose
half the limb. Otherwise you lose all of it. Your limb can regrow if you
use high-level <<restoration_magic>>.

*Permanent*: This trauma is permanent. There is no way to undo it or reverse
it.

[[reversible,reversible]]
*Reversible*: This type of trauma is permanent, but it can be reversed with
<<restoring_salve,restoring salves>> or by using high-level
<<restoration_magic>>.

*Temporary*: This trauma goes away after 1d20 days. It can also be reversed
with restoration magic.

.Restoration Magic
[[restoration_magic,restoration magic]]
[quote]
The {hero_book} and the {elite_book} contain restoration and rejuvenation
spells that can also restore or remove the effects of trauma.

=== Healing and Regeneration
You can regain hit points in various ways, but you can never heal or be healed
beyond your <<hit_point_total>>.

[[rest,rest]]
*Resting*: Resting for 8 hours, at least six of which are spent sleeping, will
allow you to regenerate a bit; roll 1d8, add your level,  and increase your
hit points by that number. Aside from sleeping, eating, and keeping watch, you
cannot do anything of consequence while resting.

If you have suffered temporary stat point loss, each reduced stat regains 1d4
points.

[quote]
--
You can regenerate 1d8 hit points after a meal, 6 hours of sleep, and two hours
of rest.

You can also 
--

*Magical Healing*: Spells (such as <<_heal_x>>), potions, and powers often
allow you to instantly regain hit points, usually by rolling a number of
d6.

== CONDITIONS

Conditions can affect characters and baddies.

//START_SORT //KEY:

//KEY:
[[comatose,comatose]]
*Comatose*: You’re in a deep coma. If you receive conventional medical care,
you will wake up in a matter of hours; make a __constitution__ check every hour
to see if you wake up. If you receive magical healing, you will wake up in a
matter of minutes; make a __constitution__ check every minute to see if you wake
up.

//KEY:
[[dead,dead]]
*Dead*: You're dead. You can be brought back to life with resurrection magic
(not available in this document). If you are not buried or are treated with
burial rites or the <<_burial_x>> spell you will rise as an undead within 2d6
days.

[%unbreakable]
--
.The Undead Curse
****
[quote,Sybia LeDique]
The horror of the battlefield is magnified, multiplied, and intensified when
you have to kill your foes twice followed by your late comrades.

Anyone (any intelligent, living creature) who dies will almost certainly rise
again as an undead within a few days or even hours. This can be completely
prevented by use of the <<_burial_x>> spell or by one of the following burial
rites:

.. Burn the corpse.
.. Cut off _all_ limbs.
.. Cut off the head and spike the heart.
.. Spike the heart and put silver coin in its mouth.
****
--


//KEY:
[[demoralized,demoralized]]
*Demoralized*: On your next turn you must spend all your moves (if possible)
retreating from your opponents. When you have done that, the demoralized
condition goes away.


//KEY:
[[destroyed,destroyed]]
*Destroyed*: You’re extremely dead; You must roll twice on the <<trauma_table>>
and upgrade all temporary effects to <<reversible>>. Only very powerful
resurrection magic, accessible only to xref:elite#[elite persons], can bring
you back to life, and the costs of doing so are grave for both you can the
caster.


//KEY:
[[dungeon_mad,dungeon mad]] 
*Dungeon Mad*: You've been in complete darkness in a dungeon or cave for too
long. Every hour you spend in total darkness deep inside a dungeon or similar
situation, you must make a __wisdom__ check; if you fail, you temporarily lose
1 point from a random stat. This check has <<disadvantage>> if you are alone in
the darkness. Your stats will start to regenerate as soon as you are again in
the presence of light at the rate of one stat point per hour. It goes twice as
fast if you are outside in the sunlight.

[quote]
You die if any of your stats reaches zero.

//KEY:
[[dying,dying]]
*Dying*: You’re near death; you must roll on the <<trauma_table>>. Every round,
at the beginning of your turn, you must make a d20 roll; if you roll a
<<nat1>>, you are no longer dying, but <<unconscious>>, and if you rolled a
<<nat20>>, you are dead.


//KEY:
[[encumbered,encumbered]]
*Encumbered*: All your checks have <<disadvantage>>.


//KEY:
[[exhausted,exhausted]]
*Exhausted*: You are <<encumbered>> and you lose 3 <<moves>>.


//KEY:
[[frightened,frightened]]
*Frightened*: You cannot move closer to what you believe is the source of
your fear. You have 2 fewer moves than normal.


//KEY:
[[invisible,invisible]]
*Invisible*: You are invisible. You cannot be targeted by creatures who rely
primarily on sight. Even so, if a creature relies just partially on sight, its
<<attack_and_damage,attack checks>> against you have <<disadvantage>>.
Attacking you with spells is also difficult, but it is up to the GM to decide
such effects on a case by case basis.


//KEY:
[[on_fire,on fire]]
*On Fire*: You are on fire. At the start of every round, just before you get to
act, you take 1d4 points of damage, and then you roll a __constitution__ check.
If you succeed, the fire goes out. If you failed, the fire persists, and if you
rolled a <<nat20>>, the damage die increases (for instance, from 1d4 to 1d6).


//KEY:
[[poisoned,poisoned]]
*Poisoned*: You temporarily lose 1d4 points of a random stat every minute.
After rolling your stat loss, you make a __constitution__ check with
<<disadvantage>>. If successful, the poisoned condition is removed. You die if
any of your stats are reduced to zero. If you die from poison, only Greater
Revival can restore you back to life.


//KEY:
[[prone,prone]]
*Prone*: You're prone on the ground, you must spend 1 <<moves,move>> to get up.
While you are prone, you have four fewer <<moves>> than normal.

[quote]
If you're suffering from other effects that lower your number of <<moves>>,
you can be reduced to zero moves. Forcing you to convert your <<Actions,action>>
into more moves just to get up.


//KEY:
[[restrained,restrained]]
*Restrained*: Your hands and feet are restrained. You can make no more than one
<<moves,move>> each round. Depending on the circumstances, the GM might allow
you to try and escape your bonds.


//KEY:
[[starving,starving]]
*Starving*: Every day that you do not get at least one
{consumption} of <<rations>> or similar, you roll 1d20 for
each of your <<Stats,stats>>. If you rolled under a stat, that stat is reduced
by 1 until you get food and <<rest>>.


//KEY:
[[unconscious,unconscious]]
*Unconscious*: You are unconscious; if you receive any kind of healing, you
will wake up right away, otherwise you will wake up within 2d6 hours.


//END_SORT
//}}}


//{{{ MAGIC
== MAGIC

[[spellbook,spellbook]]
=== Spellbooks
A spellbook is a magical tome, book, or scroll. It takes up one
<<item_slots,item slot>>, contains a single spell and can only be used if it
has enough magical charge.

Spellbooks need magical charge (<<usage_points>>) to work. When a spellbook
runs out of <<usage_points>>, it is depleted and unusable until it is recharged
(e.g. via <<basic_recharging>>). A spellbooks maximum <<usage_points>> depends
on the power and skill of its creator.

[quote]
Normal spellbooks only have a few usage point, and only very powerful tomes
have more.


[[basic_spellcasting,basic spellcasting]]
=== Basic Spellcasting
You can cast <<basic>> spells directly from a <<spellbook>> if you meet the
requirements below. It is an <<Actions,action>> to cast a spell (unless
otherwise specified in the spell's description).

*Requirements*:

* You must have a <<spellbook>> with a <<basic>> spell inscribed in it.
* The spell's level must not be higher than yours,
* You must not have cast any spells previously in this <<round>>.
* The <<spellbook>> must have at least one <<usage_points,usage point>>.
* You must be holding the <<spellbook>> open in both hands.
* You must be able to see, speak, read, and move your arms, hands, and fingers.
* You must not be <<encumbered>>, <<exhausted>>, <<on_fire>>, <<prone>>,
  <<restrained>>, <<prone>>, or similar.

*Procedure*: When you have the book open in your hands, you loudly read
the spell's incantation. Then you make an __intelligence__ check and refer
to this table:

[%unbreakable]
--
[cols="^2s,10"]
|===
//----------+----------------------------------------------------
| {twenty}  | The spell fizzles and the book loses __all__ its {_ups}.
| Failure   | The spell takes effect and the book loses __all__ its {_ups}.
| Success   | The spell takes effect and the book looses a {_up}.
| {one}     | The spell takes effect and no {_ups} are spent.
//----------+----------------------------------------------------
|===
--

[[cancelling_spell]]
.Cancelling a Spell
****
You cannot cancel spells cast by others, and you cannot cancel a spell with a
<<duration>> unless it has the <<focus>> or <<trance>> property, or if
cancellation is allowed in the spell's description.
**** 

[[targeting_spell]]
.Targeting a Spell
****
Unless specifically allowed in the spell's description, you cannot target
baddies or things you can't see. Spells that create projectiles, beams, or
similar effects travel in a direct line, completely unable to avoid obstacles.
****



[[basic_ritual_casting,basic ritual casting]]
=== Basic Ritual Casting
Some spells can be cast without exhausting the spellbook, but it takes more
time to do so.

*Requirements*:

* You must have a <<spellbook>> with a <<basic>> spell inscribed in it.
* The spell must have the <<ritual>> property,
* The spell's level must not be higher than yours,
* The spellbook must have at least one <<usage_points,usage point>>.
* You must be able to see, read, speak, and move about.
* You must have the <<spellbook>> near you while the ritual is performed,
  as you will often refer to the book.
* You must have your <<magic_components>> on you, as you'll need them for your
  ritual.


*Procedure*:
You spend 15 minutes and one {consumption} of <<magic_components>>, and then
you make an __intelligence__ check and refer to this table:

[%unbreakable]
--
[cols="^2s,10"]
|===
//---------+----------------------------------------------------
| {twenty} | The spell fizzles and the book loses all its <<usage_points>>.
| Failure  | The spell fizzles.
| Success  | The spell takes effect.
| {one}    | The spell takes effect.
//---------+----------------------------------------------------
|===
--


[[basic_recharging,basic recharging]]
=== Basic Recharging
Adventurers can recharge spellbooks, restoring them to their maximum
<<usage_points>>.

*Requirements*: The spell in the spellbook must contain a <<basic>> spell with
a level no higher than yours.

*Procedure*: You start by spending one {consumption} of <<magic_components>>,
followed by 30 minutes of ritualistic work. Then you make an __intelligence__
check. If the check succeeds, you have recharged the spellbook, back to its
maximum <<usage_points>> otherwise you must try again.

*Rushed Recharging*: You can partially recharge a spellbook on the go; you must
hold the book in both hands and spend an <<Action,action>> You roll an
__intelligence__ check, and if it succeeds you add one {_up} to the book, but
you also temporarily lose 1d4 points of __intelligence__, some or all of which
can be regained by <<rest,resting>>.

==== Spell Properties
The properties of a spell is listed in bold font right underneath the spell's
name.

//START_SORT //KEY:

//KEY:
[[X,_X_]]
*X*: There are many versions of this spell, each with its own level.
See also <<example_multilevel>>.

//KEY:
[[basic,basic]]
*Basic*: All basic spells can be cast by adventurers, and all spells in this
document are <<basic>>. Higher level characters have access to more advanced
types of spells.

//KEY:
[[caster_level,caster level]]
*Caster level*: The level of the caster (i.e. not the spell). The potency,
duration, or range of certain spell increases with the casters level.

//KEY:
[[duration,duration]]
*Duration*: The duration of the spell. See also <<cancelling_spell>>.

//KEY:
[[focus,focus]]
*Focus*: These spells cut their duration short and stop instantly if you cast
another spell, take damage, or stop focusing on keeping the spell going.

//KEY:
[[range,range]]
*Range*: The range of the spell. See also <<targeting_spell>>.

//KEY:
[[ritual,ritual]]
*Ritual*: These spells can be cast via <<basic_ritual_casting>>, but can also
be cast normally via <<basic_spellcasting>>.

//KEY:
[[spell_level,level]]
*Level*: The level of the spell. If the spell also has the  property, _level_
is the level of the weakest version of the spell, meaning no versions of the
spell exists at a lower level that that.

//KEY:
[[trance,trance]]
*Trance*: You must be seated to cast a trance spell, and you must remain seated
for its duration. +
//
The spell stops instantly if you:
    a) take damage,
    b) make a defense check,
    c) get up,
    d) make a <<moves,move>>,
    or e) take an <<Actions,action>>. +
//
You can speak, breathe, and adjust your position to remain comfortable, and
nothing more.

//END_SORT

[%unbreakable]
--
[[example_multilevel]]
.Multilevel Spells (X)
====
<<_tragic_missile_x>> is technically not a single spell. It exists as __Tragic
Missile 1__, __Tragic Missile 2__, and so on all the way to __Tragic Missile
10__, each level being more powerful than the last.

---

<<_ghost_mount_x>> also represents multiple spells, but since its description
says it's <<spell_level,level>> stem:[2+], there is no __Ghost Mount 1__. Only
a __Ghost Mount 2__, __Ghost Mount 3__, and so on.
====
--

//}}}


//{{{SPELLS
== SPELLS
All spells listed in this section are <<basic>> and can be used by adventurers.

// START_SORT ===


=== Alertness (X)
*Level 1+, <<focus>> (special)*

Everyone within 3 meters of the caster gets <<advantage>> on checks that
involve spotting hidden things, traps, and enemies, The effect persists even if
they move further away from the caster. The spell ends when it has provided
advantage to 2·<<X>> checks in total (i.e. not to each recipient) or when the
caster stops focusing on the spell, whichever comes first.


=== Alluring Attraction (X)
*Level 1+, <<ritual>>, duration: <<X>> days (special)*

You have <<advantage>> on the next <<X>>+1 __charisma__ checks you make that
have a strong flirting component or involve physical attraction.


=== Animal Friendship (X)
*Level 1+, <<ritual>>, <<focus>> (up to <<X>> + 1 hours)*

You have <<advantage>> on all __intelligence__, __wisdom__, and __charisma__
checks made to befriend or calm animals. If you meet a hostile animal, there is
a fifty percent chance that it becomes cautious instead of hostile when it sees
you


=== Armor (X)
*Level 1+, <<ritual>>*

You turn a nonmagical piece of clothing that you wear into a magical armor
piece; it provides __3+<<X>>__ <<armor_hit_points,hit points>> and you are
skilled at using it. You can create a cuirass, gauntlets, greaves, and a
helmet, but you cannot create a shield. The armor piece reverts to a normal
piece of clothing if you doff it, sleep, or otherwise loose consciousness.


=== Banking Transaction (X)
*Level 2+, duration: 5 minutes*

You touch a magical <<bank_book>> and transfer coins into- or out of it. You
cannot bring the book’s balance below zero. It takes <<X>> minutes to cast this
spell, and it requires <<X>> gold pieces which are consumed by the spell (yes,
you must have at least <<X>> gold pieces on hand to withdraw your money).

The number of coins you can withdraw/deposit is __10·<<X>>·<<X>>·<<X>>__ (i.e.
10·<<X>>³).


=== Bug Repellent (X)
*Level 1+, duration: <<X>> minutes*

You target a nonmagical item within <<X>> meters. The item starts emitting
sounds and odors that repel insects and other vermin. The spells area of
influence is a sphere with a radius of 2·<<X>> meters

Vermin whose level is <<X>> or higher are completely unaffected.

Vermin whose level is lower than <<X>> must make a normal __wisdom__ check or
move out of the repellent area. Even if the check is successful, any other
checks made within the repellent area have <<disadvantage>>

Mundane vermin, such as normal spiders, worms, ants, flies, wasps, etc. are
level 0. Supernatural vermin such as giant wasps, etc. are at least level 1.

This spell has no effects on non-vermin.


=== Burial (X)
*Level 1+, <<ritual>>*

<<X>> corpses of your choice within __charisma__ meters will not automatically
become undead (see <<the_undead_curse>>. This spell doesn't work if the
corpse's level is higher than yours.


=== Calm Animal (X)
*Level 1+*

You calm a hostile animal within 10+<<X>> meters and whose level isn't higher
than <<X>>. The animal no longer considers you and your party as threats, and
will simply wander away if possible.

[quote]
This spell does not affect monsters, even if they look like animals.


=== Club
*Level 1*

A magical wooden club appears in your hand. You are skilled at wielding this
one-handed weapon, and your damage die is 1d12. The club dissolves into dust
after <<caster_level>>+5 rounds, or instantly if you let go of it.


=== Command Fire (X)
*Level 1, range: 2·<<X>> meters, <<trance>> (up to 2·<<X>> minutes)*

When you've just cast the spell you select a fire. It can be as small as a
candle and as large as <<X>> square meters. You can now give the fire a
command:

*Candle*: You shrink a bonfire to the size of a candle.

*Bonfire*: You make a candle grow to the size of a bonfire, provided there is
sufficient fuel available.

*Grow*: If the fire is the size of a bonfire, it expands to take up an entire
square meter. If the fire is 1 square meter or larger, it expands a further
square meter. You can control the direction of the fire’s growth, but you can
only make it expand to areas where there is plenty of fuel.

*Reduce*: If the fire is larger than 1 square meter, it shrinks by 1 square
meter. If the fire is 1 square meter in size, it shrinks to the size of a
bonfire. If the fire is the size of a bonfire, it goes out, not producing any
additional smoke in the process.


=== Crackdown (X)
*Level 2+, range: __wisdom__ meters, <<focus>> (up to <<X>> rounds)*

You call down a bolt of lightning onto a baddie within range. The bolt deals
<<L>>d6 damage. Each round thereafter, at the cost of 3 <<moves>> you can
call down lightning again.


=== Cure Exhaustion
*Level 1, <<ritual>>, range: __wisdom__ meter*

You target a willing person within range, and remove the <<exhausted>>
condition from them.

A creature that has been targeted by this spell becomes immune to it for 1
hour.


=== Danger Sense
*Level 2*

If you make a successful __charisma__ check, you get a sense, on a scale of 1
to 5, of how dangerous a given foe, group, situation, mechanism, substance, or
task.

[quote]
Context is important: a high level paladin might be dangerous to her foes, but
completely harmless to her friends.


=== Detect Magic
*Level 1, <<ritual>>, <<focus>> (up to __intelligence__ minutes)*

You can sense magical items, and items that are affected by spells, such as an
item with <<_illuminate_x>> cast on it. The item must be within __wisdom__
meters. Your magical sense works almost like a sense of smell. This means that
it is relatively hard to detect the direction of magical items, and it is
exceptionally hard to distinguish magical items from each other. In general, it
is only possible to detect the direction of the most powerful magical item.

[quote]
It can be advantageous to keep you and your party's items, including your
magical items, and spellbooks, away from you while you're using this spell.


=== Detect Traps (X)
*Level 1+, <<focus>>: ( up to <<X>> hours)*

You can sense if a trap is within 10+<<X>> meters, but you only know where it
is when the trap is within <<X>> meters of you.


=== Detect Undead
*Level 1, Duration: __wisdom__ hours*

You can feel when one or more undead creatures are within __wisdom__ meters of
you. You can detect undead creatures through most walls, but not it cannot
penetrate more than one meter of rock or one centimeter of lead.

You are not able to detect the direction of the undead; but nothing prohibits
you from traversing the area and probing when you feel the presence of the
undead creature, and discerning its location that way.


=== Fey Flames (X)
*Level 2*

You target a point within __wisdom__ meters. Every object and creature within
<<caster_level>> meters of that point glows with a faint light as if on fire.
<<invisible,Invisible>> creatures and object can now be seen and targeted, but
attack checks against them still have <<disadvantage>>.


=== Fierce Fortune (X)
*Level 1*

An ally within <<X>> meters gets <<advantage>> on their next
<<attack_and_damage,attack>>- or <<_defense,defense check>>, provided it occurs
within <<X>>+1 rounds.


=== Flaming Fingers (X)
*Level 1+*

Jets of fire spew forth from your burning hands, scorching up to <<X>> adjacent
targets of your choice. If you make a successful __intelligence__ check, each
target receives 1d6+<<X>> damage, otherwise they receive 1d6 damage.


=== Friendliness (X)
*Level 1, <<focus>> (up to <<X>> minutes)*

Your __charisma__ checks have <<advantage>>.


=== Furnace
*Level 2, <<trance>> (up to 8 hours)*

A bonfire within 10 meters becomes hot enough heat metal enough for forging.
The bonfire does not consume more wood that it normally would, and it does not
radiate more heat than it normally would; the intense heat stays very close to
to the fire.


=== Ghost Mount (X)
*Level 2, <<focus>> (special)*

You construct a ghostly, translucent horse that only you can ride. It appears
instantly under you, so you’re instantly mounted. The horse increases your
movement rate such that, whenever you spend one move, you move up to <<X>>
meters. The mount has 2·<<X>> hit points, all its primary stats are 8+<<X>>.

A Ghost Mount is immune to charm, sleep, fear, illusions, demoralization, and
other mind-based spells, as well as spells where __intelligence__, or
__charisma__ checks affect the spell’s outcome.

The spell lasts up to 3·<<X>> rounds, but stops if you stop <<focus,focusing>>
on it or if you dismount.


=== Ghost Servant (X)
*Level 1, <<focus>> (special)*

You construct a ghostly, humanoid that only you can see, hear, or smell. You
can send it telepathic commands, and it will obey you to the best of its
abilities, and without question or hesitation.

The servant appears within 3·<<X>> meters, and must stay within 10·<<X>>
meters.

* It can move up to <<X>> meters per round.
* Its primary stats are all 2·X, and its __hit point_total__ is also 2·X.
* It cannot hear, speak, read, write, or make sounds, but it does understand
  your telepathic commands. It can lift and carry <<X>> item slots.
* It cannot do difficult or demanding things such as disarming traps, but it
  can do simple tasks such as moving stuff or doing the dishes.
* It is immune to charm, sleep, fear, illusions, demoralization, and other
  mind-based spells, as well as spells where __intelligence__ or __charisma__
  checks affect the spell’s outcome.

The spell lasts 10·<<X>> minutes, until you stop focusing on it, or the servant
gets more than 10·<<X>> meters away.


=== Gills (X)
*Level 1+, <<ritual>>, <<focus>> (up to 2+<<X>> minutes)*

You and <<X>> willing creatures within 4+<<X>> meters gain the ability to
breathe in water for the duration of this spell.


=== Gloom (X)
*Level 1+, range: 2+<<X>> meters*

You target an object within range. The object emits a ghostly dark aura that
dulls all non-magical sources of light within 5+<<X>> meters reducing their
radius to 1 meter while they are within the effective range of the gloomy
object.

This spell also dulls magical light sources if their spell level or item level
is lower than <<X>>.

The dulled light sources cannot be seen by creatures more than 1 meter away
from them.

You cannot target an object that is currently being held, worn or touched by
another creature.

The gloomy area looks like dense fog when seen from the outside.


=== Heal (X)
*Level 1+, <<ritual>>, range: 3+<<X>> meters*

You target a creature within range who regains <<X>>d6+<<X>> hit points.


=== Hurt (X)
*Level 1+, <<ritual>>, range: 3+<<X>> meters*

You target a creature in range; if you succeed an <<adversarial>> __wisdom__
check, the creature loses 6·<<X>> <<hit_points>>, otherwise it loses <<X>>d6
<<hit_points>>.


=== Illuminate (X)
*Level 1+, range: 2+<<X>> meters, duration: <<X>> hours*

You target an object within range. The object lights up with a steady and
bright light that illuminates a radius of 10+<<X>> meters.

You can attempt to cast this spell on the eyes of a creature within range,
effectively blinding it (if it uses eyes and light to see). It requires a
successful __charisma__ check made with <<disadvantage>>, and if the creature’s
level is higher than <<X>>, the spell fizzles.

You must make a successful __charisma__ check to cast this spell on an item
currently held, worn, or touched by a living creature, and if the creature’s
level is higher than <<X>>, the spell fizzles.


=== Intruder Alert
*Level 1, <<ritual>>, duration: __wisdom__ hours*

Upon casting the spell, you touch a door, tent flap, a lock, or similar
moveable object. If the object is disturbed by a creature (but not, for
instance, the wind), this spell will wake you up swiftly and without startling
you.


=== Invisibility to Stupidity (X)
*Level 1+, <<focus>>, duration: 5·<<X>> Rounds*

Creatures with an __intelligence__ lower than <<X>>+5 cannot see you, smell
you, or detect you in any way, not even by touch. If such a creature touches
you, it will rationalize the sensation away.


=== Jump (X)
*Level 1+*

When you cast this spell, you instantly jump <<X>>+1 meters in a direction of
your choice. You cannot reduce the length of the jump, but you can jump into a
wall or other obstacle. Doing so causes you to take 1d6 damage for each meter
the obstacle shortens your jump.

If you jump into a creature, you each suffer 1d4 damage for each meter the
collision shortened your jump. If the creature succeeds a __dexterity__ check,
they're able to avoid you, and you fly right past it (note that very large
creatures don't get such a check).


=== Lightning Touch (X)
*Level 1+*

You touch an adjacent target, who then takes <<X>>d6 damage. After rolling
damage, you make a __wisdom__ check. If successful, the target is knocked
<<prone>>.

If the target is wearing three or more pieces of metal armor, you have
<<advantage>> on the damage roll and the __wisdom__ check.

[quote]
Medium- and heavy armor is made of metal unless otherwise specified.


=== Luck (X)
*Level 2+, duration: __charisma__ rounds*

Whenever you make a __check__ with your d20, and you roll less than __X__, this
spell turns that roll into a __1__.


=== Mage Might (X)
*Level 1+, <<focus>> (duration up to <<X>> rounds)*

Your __strength__ score becomes __15+0.5·<<X>>__ (rounded down).


=== Magical Reading
*Level 1, <<ritual>>, duration: 8 hours*

You cast this spell on a spellbook or mundane book. It allows you to safely
read the book without falling for any mental magical traps the text may hold.
It also allows you to decipher (but not cast) spells in spellbooks whose level
is up to three levels higher than yours.


=== Magical Stone
*Level 1*
You touch a nonmagical stone or slingshot no larger than your fist. It becomes
magical, and flies in a direct line towards an enemy within __wisdom__ meters
at great speed. The stone automatically hits the opponent, dealing damage equal
to three times your <<caster_level,level>>.


=== Milf's Caustic Aerosol (X)
*Level 1+, range: <<X>> meters*

You spray caustic liquid towards a baddie within <<X>> meters. The enemy takes
<<X>>d6 damage and <<X>> of their nonmagical functional armor pieces becomes
unusable.

=== Milf's Magnificent Melons (X)
*Level 1+*

You create <<X>> edible and nourishing melons. Each melon weighs one
<<item_slots,item slot>> and has <<X>> usage points.


=== Mind Message (X)
*Level 1+*

You target a creature within 10 plus 10·<<X>> meters, and telepathically send
10·<<X>> words to it. It can telepathically reply with the same number of
words. If the recipient makes a successful __charisma__ check, no one notices
its distraction while receiving and replying.


=== Mosstrum’s Magical Aura (X)
*Level 1, <<ritual>>, duration: <<X>> days*

You select a nonmagical item within 2 meters, weighing no more than <<X>> kg.

You give the item an invisible magical aura of your design. Anyone who uses
<<_detect_magic>>, identify or similar detection magic will think the item is
magical, and they will think the item has magical properties of your choosing.

Observers with a level higher than <<X>> can detect that this spell has been
cast, and that the item is nonmagical.


=== Mosstrum’s Mundane Shroud (X)
*Level 2, <<ritual>>, duration: <<X>> days*

You target a magical item within 2 meters of you, weighing no more than <<X>>
kg.

This spell completely hides the fact that the item is magical; only observers
with a level higher than <<X>> can detect the item’s magic, and that this spell
has been used to hide it.

Some magical items have a level; this spell only works if the item's level is ≤
<<X>>.


=== Order (X)
*Level: 1+, duration: 1 round*

You give a creature within <<X>> meters a one-word order and then make a
__charisma__ check. If you’re successful, the target will attempt to execute
the order as best it can, and as it understands the command, but only for one
round, and only if the order would not result in self harm.

You cannot affect creatures whose level is higher than <<X>>. But they become
hostile as soon as you have cast the spell.

If the target’s level is lower than <<X>> your __charisma__ check has
<<advantage>>.

Any creature targeted by this spell will become hostile towards you, regardless
if they executed the order or not.

[quote]
Orders such as »flee« and »run« are straight forward, but a order such as
»drop« can be interpreted in many ways (drop the thing you’re holding, or drop
<<prone>>, or drop the subject). Don't assume that the target of this spell
will fully understand the meaning or spirit your order, but don't assume that
they will misunderstand it either.


=== Otto Luke's Torch (X)
*Level 2+, <<focus>>, range: <<X>>·5 meters*

You target a spot you can see within range. At that spot a magical ghostly
torch appears. By spending one <<moves,move>> you can move the torch up to 5
meters to a spot you can see and that is within range.

The torch disappears after 8 hours, or earlier if you move so that the torch
comes out of range.


=== Phantasm (X)
*Level 1, <<focus>>*

You create a purely visual illusion of an object, creature, thing, or
phenomenon no bigger than <<X>> cubic meters and no longer than <<X>> meters on
a side.

You can make the phantasm appear anywhere you can see within 10·<<X>> meters,
and it must remain within that radius at all times. You can move the phantasm
<<X>> meters per round. The spell ends after 5·<<X>> minutes, if you stop
focusing on it, or if something substantial touches the phantasm (heavy smoke,
sandstorm, a creature, etc.).

Creatures that have a reason to disbelieve the phantasm (such as creatures that
rely heavily on scent and sound, or people who find the phantasm incompatible
with their sense of "`what ought to be`" can make an <<adversarial>>
__charisma__ check to see the phantasm for what it is.


=== Pleasure (X)
*Level 2+*

You touch a willing person, who instantly gets an orgasm, the intensity of
which depends on <<X>>. Once a target has been affected by this spell, they are
immune to this spell for 1d6 hours.


=== Purify Rations (X)
*Level 1+, <<ritual>>*

You purify <<X>> ration packs, making them completely safe, nourishing, and
even tasty to eat, no matter how old, stale, and nasty they were.

This spell does not remove curses or other magical effects that may affect the
food and drink.


=== Read Script
*Level 2, <<ritual>>, duration: 10·__intelligence__ minutes*

You can read and understand any written language. This spell does not decode
cryptographic cipher text, but it does let you understand secret languages.


=== Remove Fear (X)
*Level 2+, range: __charisma__ meters*

You target an ally within range. The spell automatically removes <<X>>
fear-based conditions such as <<demoralized>>.

If the target suffers from more than <<X>> fear effects, the GM chooses which
to remove.

[quote]
There are more fear effects than the ones described in this guide.


=== Repair (X)
*Level 1, range: 5+<<X>> meters*

You instantly repair a break, crack, scratch, or tear up to 5+<<X>> centimeters
on an object within range.

A <<broken_armor,broken>> piece of armor can be repaired if it isn't magical, and
it provides no more than 2·<<X>> <<armor_hit_points,hit points>>.

A <<damaged_weapon>> or <<broken_weapon>> weapon or item can be repaired if
they aren't magical, and <<X>> is at least double the item's number of
<<item_slots>>.

Once an item has been repaired, it becomes slightly magical for 1 day; it
cannot be repaired in that period, and it will be detectable with
<<_detect_magic>> and by baddies who are sensitive to magic.


=== Shield (X)
*Level 1+, <<focus>> (up to 5·<<X>> rounds)*

All damage you receive is halved (rounded down).

[example]
If a baddie hits you for 5 points of damage, you only take 2 points of damage.
And if you’re hit for 1 point of damage, you take zero points of damage.


=== Slow (X)
*Level 1+, <<focus>> (up to <<X>> rounds)*

You target a baddie within 2·<<X>> meters. For the duration of this spell, the
target creature has zero <<moves>> (but it can convert its <<Actions,action>>
into moves).


=== Slow Fall (X)
*Level 1+, <<ritual>>*

You touch  a nonmagical wearable item that weighs at least one
<<item_slots,item slot>> and is worth at least <<X>> silver pieces. The item
becomes a {consumable} magical item with <<X>> <<usage_points>>. When the
wearer of such an item falls more than one meter, the magic in the item
activates and the fall is slowed so the wearer does not take any damage from
the fall. When the wearer has landed, the item loses one of its
<<usage_points>>. When all the item’s usage points have been spent, the item
crumbles to dust.

[quote]
the item is magical so it can be detected with <<_detect_magic>>.


=== Snooze (X)
*Level 1+*

This spell can send one or more creatures to sleep, but it can only affect
creatures that need regular sleep, and whose level isn't higher than <<X>>.

Select a baddie within 10 meters. If the target has more hit points than your
__charisma__, the spell fizzles, otherwise the baddie falls asleep.

If the spell didn't fizzle, you may make a __charisma__ check, and if it
succeeds, the spell affects <<X>> additional creatures within 5 meters of the
first target.
//
This spell affects baddies and allies alike; these extra affected creatures are
selected in order of closeness to the first target.

Creatures sleep for a number of rounds equal to your __charisma__, however a
sleeping baddie wakes up if they take damage.


=== Spenser’s levitating Bowl
*Level 1, <<ritual>>, duration: __intelligence__ · 10 minutes*

You conjure a large, vaguely bowl-shape plate that can carry as many
<<item_slots>> as your __intelligence__ score.

It levitates about a meter above the ground, and can move half as fast as an
adventurer. It is able to negotiate stairs and hills, but cannot scale walls or
steep cliffs.


=== Spider Climb (X)
*Level 1+, <<focus>>*

This spell enables you to cling to almost any surface as long as it is not
overly wet, oily, or slippery. You can spend 3 moves to spider-move 1 meter.
The spell lasts <<X>> minutes, but ends if you stop focusing on it.


=== Spout (X)
*Level 1+ <<focus>>*

You cause 10·<<X>> liters of water to pour out of a wineskin, teapot, keg, or
similar; at a speed of about 1 liter per round (10 liters per minute)


=== Strength of Stone (X)
*Level 1+, <<focus>>, <<ritual>>*

You target a willing ally within 2·<<X>> meters, giving all their __strength__
checks <<advantage>> for a 2·<<X>> rounds.


=== Taunt
*Level 1+, duration: 1 round*

You target <<X>> creatures within 10+<<X>> meters. For each target, if you can
make a successful <<adversarial>> __charisma__ check (with <<disadvantage>> if
the target’s level is higher than yours), the target will rush and attack you
in melee combat on its next turn, and that attack will have <<disadvantage>> if
the baddie's level is lower than yours.


=== Tragic Missile (X)
*Level 1+, range: __wisdom+X__ meters*

You fire a frightening magical missile against a baddie within range. When
struck, the baddie takes <<X>> d6 damage, and then you make an <<adversarial>>
__charisma__ check; if successful the baddie becomes <<demoralized>>.


=== Vines (X)
*Level 2, <<focus>>*

You target a point within 10+<<X>> meters. Vines and wild growth sprouts from
the ground in  a radius of <<X>> meters around that point. Each creature inside
the affected area must make a successful __strength__, __dexterity__ or
__intelligence__ check (their choice) each round, or all they have zero moves
that round.


=== Wizard’s Mark
*Level 1, <<ritual>>, <<focus>>*

Makes a piece of chalk magical so it makes invisible marks that only you can
see.

Other than being invisible, the marks behave as normal chalk marks, which means
they can be rubbed out or washed away with water.

The chalk stops being magical once you stop focusing on the spell, or after
__charisma__ hours. But the marks remain visible to you, and invisible to
others.

//END_SORT

//}}}


//{{{DICTIONARY
// Page Break
<<<

== DICTIONARY

//START_SORT //KEY:

//KEY:
*Adventurer*: All PCs start out as adventurers and have to level up to level 3
before they can get their hero class.

//KEY:
*Adversarial Check*: A check that is affected by the level difference between
you and the opposition. <<adversarial,{link}>>

//KEY:
*Attack Check*: A check to hit an opponent. It's an <<adversarial>> check. The
stat used in the check depends on the attack type. See
<<adventurer_damage_rolls_table>>.

//KEY:
*Baddie*: A person, creature, or monster that is hostile or otherwise
considered to be your enemy.

//KEY:
*Check*: You roll your d20 against a given target number, usually one of your
stats. <<Checks,{link}>>

//KEY:
*Defense Check (Melee)*: A check to avoid being hit by melee attacks. This is
an <<adversarial>> __dexterity__ check. <<_defense, {link}>>

//KEY:
*Defense Check (Ranged)*: A check to avoid being hit by ranged attack. This is
an <<adversarial>> __wisdom__ check. <<_defense, {link}>>

//KEY:
*GM*: [[GM,GM]] The Game Master.

//KEY:
*Hit Points, HP*: A unit of health: your character has a number of hit points,
you lose some of them when you take damage, and if you lose all of them, you
must roll on the <<death_table>>.  __Baddies and NPCs also have hit points, and
when they lose all of them, they die.__

//KEY:
*Initiative*: A check made at the beginning of a combat round to see which side
gets to act first.

//KEY:
*Level, L*: [[L,L]] Your Level.

//KEY:
*NPC, NPCs*: Non player character(s). These persons and creatures are played by
the GM.

//KEY:
*PC, PCs*: Player Character(s).

//KEY:
*Roll*: A roll is simply when you roll a die or dice such as such as __1d20__,
__3d6__, __1d10__, __2d8+2__, etc. The most common type of roll is the
<<_checks,check>>, where you use a __d20__, and the next most common type is
the damage roll, where you roll your damage die for the type of weapon you're
using.

//KEY:
*Target Number, TN*: The number you must roll below (usually with your __d20__)
in order to make a successful check.

//KEY:
*Unskilled (Armor)*:  For each piece of armor you are wearing that you are
not skilled at using, you lose one <<moves,move>>.

//KEY:
*Unskilled (Weapon)*: If you are not skilled at using your weapon, your
__attack{sp}check__ has <<disadvantage>>.

//END_SORT

//}}}
