
= Y.A.R.I.S: Adventurer's guide to doom & destruction & stuff
:stylesheet: style.css
:doctype: article
:sectlinks:
:toc:
:toclevels: 1
:toc-placement!:
:experimental:
:stem:

This document contains character creation and game mechanics, as well as gear,
spells, and abilities for characters of first and second level.

toc::[]

// {{{ ADVENTURERS SHEET
== ADVENTURER’S SHEET
The adventurer’s sheet has a bunch of fields for you to pencil in, and when
you’re done, you’re ready for adventure.

=== Stats
Your character has 6 primary stats:

Strength::      is used for melee attacks, jock stuff and carrying gear.
Dexterity::     is used for stealth, melee defense, and tricky tasks.
Constitution::  is used for carrying gear and surviving bad trauma.
Intelligence::  is used for initiative, magic, and managing resources.
Wisdom::        is used for ranged attack, ranged defense, and perception.
Charisma::      is used for luck, negotiation, charm magic, and selling treasure.

=== Extra Stuff
Here’s some more things for you to keep track of.

Level:: your character's level is a measure of their badassity. You start at
level 1 and max out at level 10. Baddies, spells, certain items and tasks
also have levels

Hit points (HP):: is your current number of hit points. Bad stuff happens if
you <<zero_hp,run out of HP>>.

[[hit_point_total]]
Hit point total:: is the maximum number of hit points you can have. I.e. the
number of HP you have when you're at full health. This number increases every
time you gain a new level, and wearing armor
can also increase this number

[[recovery_die]]
Recovery die:: is the die you roll (one or more of) to regain hit points when
you rest or receive magical healing. You start with a recovery die of d8.

Total item slots:: is the maximum number of <<Item Slots,items>> you can carry.
This number is the highest of your _strength_ and _constitution_.

Unencumbered item slots:: is the number of items you can carry without being
encumbered. This number is the lowest of your _strength_ and _constitution_.

Moves:: is the number of meters you can move in a round. You can also use moves
to do other interesting <<Moves,things>>.
// }}}

// {{{ CREATE YOUR ADVENTURER
== CREATE YOUR ADVENTURER
Go through the following sections, one by one, to create a new character.

=== 1. Stats
For each of your six stats in order, you roll 1d8+6 and assign the result to
that stat. Now each stat has a value between 7 and 14.

=== 2. Background & Fluff
Roll on each of the following tables to flesh out your character.

==== Ancestral Traits
First roll a d6. If it is an even number, you do not have any special ancestral
traits. If it is an odd number, roll two more d6.  The lowest number is used on
the table on the left, and the highest number is used on the table on the
right.

[%header,%unbreakable,cols="^6,^6"]
|===
| Low roll  | High roll
//----------------------
| Hands     | Troll
| Ears      | Gnoll
| Nose      | Goblin
| Hair      | Elf
| Eyes      | Dwarf
| Teeth     | Gnome
|===

.Ancestral Traits
====
A roll of 1 and 6 would give you gnome hands. And a roll of one and one you
troll hands (claws, maybe?) and a roll of 4 and 3 would give you an elven nose.
====

==== Vice
Roll a d12. If you roll a number that isn't on the table, you don’t have a vice.

. Two vices: Roll twice.
. Drinking
. Bar fighting
. Attention
. Gambling
. Stealing
. Fornicating


==== Background
Roll a d6 and a d20. If the d6 rolled an even number, pick your background from
the left column, otherwise pick your background from the right column

[%header,cols=2*a]
|===
| d6 rolled 1, 3, or 5 | d6 rolled 2, 4, or 6
|
. Apothecary
. Baker
. Banker
. Bartender
. Butcher
. Carter
. Chandler
. Chef
. Clergy
. Clerk
. Companion
. Cook
. Courier
. Courtier
. Doctor
. Entertainer
. Farmer
. Fisherman
. Foreigner: roll again for original background
. Gambler
|
. Gold Smith
. Hunter
. Hustler
. Laborer
. Lazy spouse
. Magician’s apprentice
. Merchant
. Monestarian
. Musician
. Notary
. Officer
. Prisoner
. Royalty
. Sailor
. Scribe
. Smith
. Solder
. Squire
. Street urchin
. Thief
|===


=== 3. Adventuring Gear
All characters start with the following equipment:

* A backpack.
* Two torches.
* A weapon of their choice.
* Two common ration packs.
* A set of common clothing.
* A bedroll.

*In addition to that:* Roll on each of the following tables to find out what
equipment your character starts with. See <<EQUIPMENT>> for more info on
equipment and items.


==== Ranged weapon
Roll 1d6 on this table to find out if you have a ranged weapon.

[%header,cols="^2,10"]
|===
|d6     | Weapon
|1-3:   | No Ranged Weapon.
|4:     | Slingshot + Bag of stones.
|5:     | Bow + Quiver of arrows.
|6:     | Crossbow + Quiver of bolts.
|===

:!sectids:
==== Armor
:sectids:
Armors give you extra hit points; you have 1d3-1 light armor pieces. See
<<Armor>> and the <<light_armor_table,light armor table>> for more info.

==== Shield
Roll 1d6. If you rolled 5 or 6, you have a light shield. Otherwise, you don’t
have a shield.

==== Utility Gear
Roll once on the <<utility_gear_1>> table.

[[utility_gear_1]]
.Utility Gear 1
[%header,%unbreakable,cols="^1,11",grid=none,frame=none,stripes=even]
|===
| 1d10 | Item
| 1    | <<ration_pack_iron,Ration pack, iron>>
| 2    | Grappling hook
| 3    | <<Storm Lantern,Storm lantern>>
| 4    | Rope, 10 meters
| 5    | <<Kosh>>
| 6    | Ball bearings
| 7    | Shovel
| 8    | <<Lockpicking Tools>>
| 9    | <<Lantern>>
| 10   | <<purse_copper,Copper purse>>
|===


Roll twice on the <<utility_gear_2>> table.
If the second roll is the same as the first roll,
reroll it.

[[utility_gear_2]]
.Utility Gear 2
[%header,cols="^1,11",grid=none,frame=none,stripes=even]
|===
| 1d10 | Item
| 1    | 2d4 gold pieces
| 2    | <<Spellbook>> with 1 <<Usage Points,usage point>>
         and a spell of your choice
| 3    | <<Torch>>
| 4    | <<Spikes>>
| 5    | <<Tinkering Tools>>
| 6    | Pole, 3m, foldable
| 7    | Chalk
| 8    | <<ration_pack_normal,Ration pack, normal>>
| 9    | <<Lamp Oil>>
| 10   | <<Map Making Tools>>
|===

=== All Done
Now it’s time to read about the adventurer class and then check out the
sections on dice checks and combat.

// }}}

// {{{ ADVENTURER
== ADVENTURER

[quote, Baron LeDik]
____
Adventurers are brave, eager, and dangerous
____

All characters start out with the same class: Adventurer.

=== Level 1

==== Recovery Die
Your recovery die is d8. This means that you regenerate 1d8 hit points when you
get a good long rest. Spells and potions may let you regenerate several
recovery dice at once.


==== Hit Points
Your hit point total is 8, which means that, under normal circumstances, you
can’t have more than 8 hit points. When you have lost all your hit points, you
have to roll on the death table.

[[armor_skills]]
==== Armor Skills
You  are skilled at using light shields and light armors. If you are wearing an
armor you're not skilled at using, you become <<encumbered,encumbered>>.
See the <<Armor>> section for more info.

[[weapon_skills]]
==== Weapon Skills
You are skilled at using light melee weapons and ranged weapons. On the
<<adventurer_damage_rolls_table,table below>> you can see how much damage you
deal with each weapon category.

[[adventurer_damage_rolls_table]]
.Adventurer Damage Rolls
[%header,cols="8,^2,^2"]
|===
| Weapon Type         | Skill level | Damage Roll
| Light Melee Weapons | Skilled     | 1d6
| Ranged Weapons      | Skilled     | 1d6
| Unarmed Combat      | Unskilled   | 1d3
| Heavy Melee Weapons | Unskilled   | 1d10
|===

==== Spellcasting
You can use <<Spellbooks,spellbooks>> to cast <<basic,basic>> spells. You can
cast these spells on the fly (this is called <<Basic Spellcasting>>), and you
can cast certain spells as rituals (this is called <<Basic Ritual Casting>>).
In addition to using spellbooks to cast spells, you can also recharge the books
via <<Basic Recharging>>.

=== Level 2

==== More Hit Points More Better
Your hit point total is increased by 1d8. Roll with advantage.

==== Better Stats
For each of your stats, you roll a d20; if the roll is higher than the stat,
that stat is increased by 1 point. And an even more betterer stat Roll a d20
and select a stat that is lower than the result of the die roll. Increase that
stat by 1 point. If no stats are lower than your die roll, nothing happens.

==== Adventurer’s Special Ability
Choose one of the abilities below. You can switch this ability at levels 4, 6,
8, and 10.

//START_SORT [[]]

[[everdeen]]
Everdeen::
If you are without arrows during combat, you can spend 3 moves, and make a
_charisma_ check. If successful, you somehow have a single extra arrow and
you’re ready to fire. If unsuccessful, you cannot use this ability before you
have stocked up on ammunition. This ability also works with bolts, slingshots,
and darts.

[[armorer]]
Armorer:: 
You can repair a piece of broken armor if you have the right tools. See
<<Tinkering Tools>> for more information.

[[great_weapon_specialist]]
Great weapon specialist::
You are skilled at using heavy melee weapons.

[[mounstrous_gourmand]]
Monstrous Gourmand::
You can make edible ration packs from fresh monster parts (any recently dead
creature will do) It requires sharp cutting instruments, a large pot, a bonfire
(or equivalent source of heat), one hour of work, and a successful
_intelligence_ check to create one ration pack. A medium sized creature
“contains” 2 ration packs. In addition to creating rations, you are also able
to eat fresh, uncooked, monster meat without getting sick. It requires a sharp
cutting tool, 3d6 minutes, and a successful _constitution_ check to create and
eat such a “meal”.

[[negotiator]]
Negotiator::
You have advantage on checks that involve negotiation. You also have advantage
on haggle checks (see <<the_haggling_check,The haggling check>>).

[[pugilist]]
Pugilist::
You are skilled at unarmed combat, meaning your attack checks are normal
instead of difficult, and you use your skilled damage die when dealing damage.
Note that, if you’re using a shield, your unarmed damage is reduced to 1.
Beware that striking  certain dangerous monsters (such as fire elementals) with
your body can have grave consequences.

[[rider]]
Rider::
You acquire a trained horse (for free, as a gift, or similar). You become
proficient at riding horses. You have advantage on all riding-related checks.
You have advantage on <<Consumption Check,consumption checks>>for animal feed.
When you reach level 5 your riding proficiency expands to all rideable land
creatures. At level 8, you can ride virtually any tame creature.

[[shady]]
Shady::
On a successful _charisma_ check you pull out a dagger from a boot, a sleeve
or… somewhere. If your check fails, you cannot do it again for the rest of the
session. In combat, this feat requires 3 moves. You are also skilled at using a
<<Kosh,kosh>>, something normal adventurers are not.

[[spelunker]]
Spelunker::
You always have some chalk. You always know the cardinal directions. You have
advantage on checks that involve navigation in caves and dungeons. One of the
ropes you carry does not take up an item slot. Aside from being unable to see,
you do not suffer any debilitating effects from being alone in total darkness
(which can otherwise cause you to suffer from dungeon madness ??????). You have
advantage on consumption checks for <<Lamp Oil>> and <<Torch,Torches>>.

[[thrifty]]
Thrifty::
You have advantage on consumption checks with coin <<Purse,purses>>.

[[traveler]]
Traveler::
You have advantage on consumption checks for rations and animal feed. You have
advantage on geography related checks. One of the ration packs you carry does’t
take up an item slot.

//END_SORT

=== Level 3: Graduation
It is time for you to move on. You’re no longer just an adventurer, you’re a
Hero. Choose a hero class from the 
xref:heroes#[Hero’s Guide to doom & destruction & stuff].

//}}}

//{{{ LEVELS
== LEVELS
You begin at level 1, and you can gain levels until you reach level 10. You
gain levels by acquiring suitable treasures. For a team of level _X_
adventurers to gain a new level, they must acquire _X_ suitable treasures. This
document only deals with levels 1 and 2. Once you reach level 3, you become a
hero; see xref:heroes#[Hero’s Guide to doom & destruction & stuff] for more info.

[discrete]
==== Acquire
Acquiring a treasure means, recovering it (possibly by liberating it
from baddies), and getting it safely back to your base of operations. 
Since a hundred coins take up an entire item slot, it can be necessary to make
multiple trips to recover a large treasure. 

[discrete]
==== Suitable
A treasure is _suitable_ if it is worth 100 gold pieces times the sum
of the levels of all the characters in the party.

[discrete]
==== Treasure
A treasure is a big horde, often situated in one location. It is up to the GM
to decide what is an actual treasure, and what is just general loot.

.Leveling up
====
. In order to level up, a party of 5 first level characters must recover a
  single treasure worth _5·1·100=500_ gold pieces.

. In order to level up, a party of 4 PCs at 6th level must recover six
  treasures in order to advance. Each treasure must be worth at least
  _4·6·100=2,400_ gold pieces.

====

// }}}

//{{{DICE
== DICE
You can make rolls and checks with your dice. A roll is any kind of roll such
as 1d6, 2d4, 3d6+3, etc. A check is a special kind of roll described below.

=== Checks
You make checks to see if your character can successfully do something
non-trivial; you roll your d20. The check is successful if you roll under a
specified *_target number_*, which is usually one of your stats.

.Target Number
====
You want to lift something really heavy, so the GM tells you to make a
_strength_ check. You roll a d20. If you rolled lower than your _strength_, the
check was successful, otherwise it was unsuccessful.
====

[[nat1]]
Rolling a 1::
Checks are always successful if you roll a 1 on your d20, this is called a *_nat1_*.

[[nat20]]
Rolling a 20::
Checks are always unsuccessful if you roll a 20 on your d20. This is called a *_nat20_*.

[[easy]]
Easy checks::
are checks where the target number is 3 higher than what it would normally be.

.Easy strength check
====
if your _strength_ is 9, making an easy _strength_ check would need to roll under 12.
====

[[difficult]]
Difficult checks::
are checks where the target number is 3 lower than what it normally would be.

.Difficult strength check
[example]
if your _strength_ is 9, making a difficult _strength_ check would need to roll under 6.

Both = Difficult::
If one or more conditions make a check difficult, it remains difficult even
if one or more conditions make the check easy.

[[adversarial_checks]]
=== Adversarial Checks
These are checks where the difficulty depends on the level of the adversary. In
this context, and adversary can be a baddie, an <<NPC>>, a lock, a trap, a
riddle, or similar.

If the adversary is two or more levels above you, the check is
<<difficult,difficult>>, and if the adversary is two or more levels
below you, the check is <<easy,easy>>.

.Adversarial Checks
====

A second level adventurer is trying to attack an evil orc who is level 5.
This attack is <<difficult,difficult>> because the orc is two or more levels above the
adventurer.

---

A level 3 player character is trying to haggle with a merchant to get a good
price on some loot. The PC is level 3, and the merchant is level 1, so the
check is <<easy,easy>>.

---

You are attacking a zombie. You are level 2, and the zombie is level 1, so
your are within one level of each other, and thus your check is normal.

====


=== Advantage & Disadvantage
Certain conditions, abilities, classes, and spells can give a roll an advantage or disadvantage,
which changes the way you roll the dice.

[[advantage]]
Advantage::
If a roll has advantage, you roll the dice twice, and pick the result you like best.

.Damage roll with advantage
====
you have advantage on a Damage Roll, you roll your damage dice twice and pick
the roll you like best.
====

Disadvantage::
If a roll has disadvantage, you roll the dice twice, and the GM picks the
result they like.

Both = neither::
If at least one advantage and at least one disadvantage applies to the same
roll, it becomes a normal without any advantage or disadvantage roll.

//}}}

//{{{EQUIPMENT
== EQUIPMENT
This section contains info on item slots, <<Usage Points,usage points>>, and
several lists of equipment. These lists are not exhaustive, and other types of
items and equipment exist.

=== Money
The weight of a few coins is negligible, but in large quantities, 100 coins
take up one <<Item Slots,item slot>>. 
A gold piece is equivalent to 100 silver pieces, a silver piece is 100 copper
pieces. 
Normally, only rich persons deal in gold, small businesses and farmsteads deal
in silver, and unskilled labor deal mostly in copper.

=== Item Slots
An average item takes up one item slot. Bulky or heavy items, such as heavy
armor, can take up multiple Item Slots. Your number of Item Slots is determined
by your _strength_ and _constitution_. The lower of these two numbers is your
number of unencumbered item slots, and the higher number is your total number
of item slots. You can use all your unencumbered Item Slots without any side
effects, but If you use any of your remaining item slots, you become
encumbered, which means that everything you do becomes difficult. You can never
fill/carry more than your Item Slots Total.

.Calculating item slots
====
If your _strength_ is 7 and your _constitution_ is 16, you have 16 item slots,
and 7 of those are unencumbered item slots. This means that, if you use 8 or
more of your item slots, you become encumbered.
====

=== Usage Points
Certain items have usage points, which are, among other
things, the minimum number of times they can be used before they are used up.

[[consumable]]
Consumables:: Items that can be completely used up (such as rations, arrows,
lamp oil) have usage points. Once these items run out of
<<Usage Points,usage points>>, they’re gone, completely used up.

Repairables:: Items that can be worn out (such as armor pieces, weapons, and
spellbooks) have usage points to track when they will wear out. Once these
items run out of <<Usage Points,usage points>>, they stop working, but they can
be repaired.

=== Consumption Check
Consumption is an unspecified amount of a consumable item. When you use/consume
a consumption of an item, you make a consumption check, which is just a check
with a target number of 11, and if it is unsuccessful, the item loses a
<<Usage Points,usage point>>.

.Using Magic Components
====
A consumption of magic components means you use some unspecified amount of your
magic components and then you make a consumption check. And if the check was
unsuccessful, your magic components lose a usage point.
====

Consumable Projectiles:: In Combat, projectiles (such as arrows, bolts,
slingshots, etc.) are consumables. You do not roll a consumption check every
time you fire an arrow, bolt, or slingshot during combat. Instead you make one
consumption check after the combat ends; if you used more than one type of
projectile, make consumption checks for each type. If you fire a projectile
when not in combat, you make a consumption check with advantage after you fired
the shot.

Repairable Items:: A repairable item (such as a piece of armor or a spellbook)
has a maximum number of <<Usage Points,usage points>>, and a current number of
<<Usage Points,usage points>>. As a repairable item is used, it loses its
Current <<Usage Points,usage points>>, and it becomes unusable when it reaches
zero. It can be repaired, but never regain more than its Maximum
<<Usage Points,usage points>>.

Exactly how a repairable item loses its <<Usage Points,usage points>>, and how
it is repaired again, depends on the type of item; see the
<<Basic Spellcasting>>, and <<Weapon Damage>> for more info.

=== Gear

.General Gear
[%header,cols="10,^1,>1"]
|===
| Name                  | IS| Cost
| Pole, 3m foldable     | 2 | 5     cp
| Ladder, 2m            | 2 | 10    cp
| Rope, 25m             | 2 |
| Rope, 10m             | 1 |
| Shovel                | 1 |
| Clothing, poor        | 1 |
| Clothing moderate     | 1 |
| Clothing, wealthy     | 1 |
| Backpack              | 1 |
| Flint and steel       | 0 | 1     cp
|===


.Consumables
[%header,cols="9,^1,^1,>1"]
|===
| Name                          | IS| UP| Cost
| Bag of slingshots             | 1 | 3 |
| Ball bearings                 | 1 | 2 |
| Candles                       | 1 | 6 |
| Chalk                         | 1 | 12|
| <<Lamp Oil>>                  | 1 | 2 | 5     cp
| Quiver of arrows              | 1 | 3 |
| Quiver of bolts               | 1 | 3 |
| <<Magic Components>>          | 1 | 2 | 1     gp
| Ration pack, iron             | 1 | 2 | 4     sp   [[ration_pack_iron]]
| Ration pack, normal           | 1 | 1 | 1     sp   [[ration_pack_normal]]
| <<Spikes>>                    | 1 | 2 |
| <<Lockpicking Tools,Tools>>   | 1 | 4 |
| <<Tinkering Tools,Tools>>     | 1 | 4 |
| <<Torch>>                     | 1 | 2 | 5     cp
|===

// Price of armor is typically (hp)³
[[light_armor_table]]
.Light Armor
[%header,cols="9,^1,^1,>1"]
|===
| Name                  | IS| HP| Cost
| Light Shield          | 1 | 2 | 8     gp
| Light Helmet          | 1 | 2 | 8     gp
| Light Cuirass         | 2 | 3 | 27    gp
| Light Gauntlets       | 1 | 2 | 8     gp
| Light Greaves         | 1 | 2 | 8     gp
|===

.Medium Armor
[%header,cols="9,^1,^1,>1"]
|===
| Name                  | IS| HP| Cost
| Medium Shield         | 2 | 4 | 64    gp
| Medium Helmet         | 2 | 4 | 64    gp
| Medium Cuirass        | 3 | 5 | 125   gp
| Medium Gauntlets      | 2 | 4 | 64    gp
| Medium Greaves        | 2 | 4 | 64    gp
|===


.Heavy Armor
[%header,cols="9,^1,^1,>1"]
|===
| Name                  | IS| HP| Cost
| Heavy Shield          | 3 | 6 | 216   gp
| Heavy Helmet          | 3 | 6 | 216   gp
| Heavy Cuirass         | 4 | 7 | 343   gp
| Heavy Gauntlets       | 3 | 6 | 216   gp
| Heavy Greaves         | 3 | 6 | 216   gp
|===

[[lodging]]
.Food and lodging (per person per night)
[%header,cols="10,2"]
|===
| Lodging                                   | Cost
| Opulent (luxurious rooms and food)        | 1 gp
| Middle class (small room, decent fare)    | 1 sp
| Poor (sleep in common room, cheap food)   | 1 cp
|===

Light Melee Weapons::
A light weapon costs 5gp and takes up 1 <<Usage Points,usage point>>.

Heavy Melee Weapons::
A two-handed weapon costs 6gp and takes up 2 <<Usage Points,usage points>>.

.Melee Weapons
[%header,cols="9,^1,2"]
|===
| Melee Weapon                  | IS| Cost
| Light Melee Weapon            | 1 | 5 gp
| Heavy Melee Weapon            | 2 | 8 gp
|===


.Ranged Weapons
[%header,cols="8,^1,^1,2"]
|===
| Name                          | IS| UP| Cost
| Darts                         | 1 | 3 | 2  gp
| Bow                           | 2 | - | 7  gp
| ↳ quiver of arrows            | 1 | 10| 2  gp
| Crossbow                      | 1 | - | 10 gp
| ↳ quiver of bolts             | 1 | 10| 2  gp
| Sling                         | 0 | - | 4  gp
| ↳ bag of stones               | 1 | 10| 2  gp
|===



=== Special Items
//START_SORT ====
==== Bank book
A bank book is a magical book that can contain money. There is a magical ritual
called Banking Transaction (X), that allows you to transfer money into and out
of the book.

==== Coins
Small amounts of counts do not take up any room, but 100 coins 
take up 1 <<Item Slots,item slot>>, and generally requires a coin
sack to contain.

==== Kosh
Only adventurers with the <<shady,shady>> special ability are skilled at using
koshes. To use a target, you make an attack check; if you hit the target, it
loses 1 hit point. You then roll your damage die. If your roll was higher than
the target’s remaining hit points, the target gains the unconscious condition,
which means they’ll wake up within 2d6 hours if not healed.

==== Lantern
Lanterns illuminates the area around you. The lantern does not have have any
usage points itself, but it it does <<Lamp Oil>>; it uses one consumption every
hour.

You can throw a lantern, using it to ignite an area. You roll a _dexterity_
check. If successful, the lantern lands where you want it to (within _strength_
meters), and covers 1d4 square meters in flaming oil. Anyone inside the affected
area is set <<on_fire,on fire>>.

==== Lockpicking Tools
These tools allow you to pick various locks. They can be used up, and therefore
have <<Usage Points,usage points>>. To Open a Lock, you first spend 5 minutes and one
consumption of lockpicking tools. Then you make both a _dexterity_- and an
_intelligence_ check.

* If both are successful, you open the lock.
* If one is successful, the lock does not open, but you get to try again.
* If none are successful, the lock becomes jammed, and can only be opened by a
real key.

==== Magic Components
Magic components are used when casting spells as rituals and when recharging
spellbooks

==== Map Making Tools
You can use these tools to maps of dungeons, cities, and various land areas.
To do so you must make an _intelligence_ check and a _wisdom_ check.

*   If both are successful, your mapping process is accurate for the entire
    dungeon level, city, or area.
*   If just one is successful, your scales are incorrect, and using the
    map is <<difficult,difficult>>.
*   If both failed, the map is not accurate at all. Twists and turns are
    wrong, scales are wrong, the cardinal directions are wrong, and there
    are missing areas and notes.

==== Purse
Purses aren't real items; they are concepts that can simplify bookkeeping.
Instead of keeping track of every copper penny and doing a lot of math,
you just make consumptions whenever you buy something.
You don't need to buy purses from a merchant - you just "buy" them directly
from the GM. You cannot sell them or exchange them.

[[purse_copper]]
Copper purse:: for 1,000 copper pieces you can buy a copper purse. It has 10
<<Usage Points,usage points>>. Whenever you buy something costing less than 100
copper pieces, you make a <<Consumption Check,consumption check>> for the
copper purse instead.

[[purse_silver]]
Silver purse:: for 1,000 silver pieces you can buy a silver purse. It has 10
<<Usage Points,usage points>>. Whenever you buy something costing less than 100
silver pieces, you make a <<Consumption Check,consumption check>> for the
silver purse instead.

[[purse_gold]]
Gold purse:: for 1,000 gold pieces you can buy a gold purse. It has 10
<<Usage Points,usage points>>. Whenever you buy something costing less than 100
gold pieces, you make a <<Consumption Check,consumption check>> for the
gold purse instead.

==== Spellbook
A spellbook is a magical book or tome that contains a single spell and
takes up a single item slot.

Spellbook prices vary greatly from place to place and on which type of spell
is inscribed in the book. They are rarely cheaper than 25 gold pieces,
and prices skyrocket as the spell's level and/or the number of usage points
increases.

Spellbooks usually only have a single usage point.

See more about them in the <<Spellbooks>> section.

==== Spikes
When hammered in between the door and the wall or jamb, these 30 centimeter
spikes can wedge a door shut until the spikes are removed.

==== Storm Lantern
This is a variant of the <<Lantern,normal lantern>> that cannot be blown
out in normal storms and gales.

=== Lamp Oil
This <<consumable,consumable>> item is flammable; you can use it as fuel for your
lantern or storm lantern, and you can use it to light things on fire.

You can throw lamp oil to cover an area; You first roll a _dexterity_ check. If
successful, the oil bottle (or skin or jug) lands where you want it (within
_strength_ meters), ruptures, and covers an area of 1d4 square meters.
//
At this point the oil is not on fire; you must light it yourself with torch,
a spell, or similar fashion.

==== Tinkering Tools
Tinkering tools can be used to disarm traps and repair broken items.

Repairing items and armor pieces:: To repair a broken armor piece, trap,
mechanism, stuck door, or similar, you spend 10 minutes and one
<<consumption,consumption>> of tinkering tools. Then you make a _dexterity_
check and an _intelligence_ check.

* If both are successful, you have repaired the item.
* If one is successful, the item is still damage, but you may try again.
* If both failed, you cannot fix this item until you've gained a new level.

IMPORTANT: _light armor_ can be repair using only tinkering tools, but _medium_ and
_heavy_ armor also requires a rudimentary smithy:

Disarming traps:: To disarm a trap you spend 10 minutes and one
<<consumption,consumption>> of tinkering tools. Then you make a _dexterity_ and
_wisdom_ check.

* If both are successful, you have disarmed the trap.
* If one is successful, you did not disarm the trap, but you may try again.
* If both failed, the trap triggers, and you are not able to dodge the effects
  (if the trap is aimed at you).

==== Torch
Aside from illuminating the area around you, torches can be used for a number
of things.

Torches have 2 <<Usage Points,usage points>>, and you must make a consumption
check every hour.

Torches can be revitalized; it requires one consumption of <<Lamp Oil>> to
restore 1 <<Usage Points,usage point>> to a torch. This cannot be done while
the torch is lit. After revitalizing your torch, you roll a difficult _wisdom_
check. If unsuccessful, the torch is destroyed, and cannot be lit.

You can throw a torch and use it as a ranged weapon, but it is difficult. If
you rolled a nat20 on your attack check, the torch is broken and cannot
be repaired. The throwing range of a torch is 5 meters.

You can use your torch as a light melee weapon, but it is difficult. If you
roll a nat20 on your melee attack check, the torch breaks and cannot be
repaired. If you roll a nat1, the target is set <<on_fire,on fire>>, dealing
1d4 damage every round until it is put out.

.Light and visibility
[sidebar]
The radius/area of light from torches, lamps, lanterns, and even magical spells
strongly depends on the setting; fog reduces the light's radius, terrain
features might obscure visibility in general, and other factors, such as magic,
also comes into play. It is therefore up to the GM, and not the rules, to
determine what the PCs can see, based on these factors.

//END_SORT

=== Selling and Haggling
You buy things for price listed in this guide, but you cannot sell items at
that price. When selling something trivial or cheap, you sell it for 50% of the
listed value, but if you’re selling more precious things, you must make a
<<the_haggling_check,haggling check>>.

[[the_haggling_check]]
The Haggling Check::
If you’re selling expensive items, or if you’re selling things in bulk, you
must haggle to get a good price. You first roll a _charisma_ check, and
refer to the table below, and do what it says, even if you don't like the
result.

[cols=">1s,10",grid=none,grid=none,frame=none]
|===
| Nat20     | You sell the item(s) for 25% of local list price.
| Failure   | You sell the item(s) for 50% of local list price.
| Success   | You sell the item(s) for 75% of local list price.
| Nat1      | You sell the item(s) for 100% of local list price.
|===

//}}}

//{{{ COMBAT
== COMBAT

This section is all about fighting 🤺

=== Rounds
Combat is divided into 10-second rounds. At the beginning of each round, the
initiative is rolled to determine who goes first. After that, each combatant
gets to act once per round; this is called their turn.

During their turn, a combatant can do the following things in order.
. Make up to 5 moves.
. Take one action.

=== Initiative
At the beginning of each round each PC makes an _intelligence_ check. If the PCs
have more failed checks than there are combat capable baddies on the
battlefield, the baddies get to go first that round.

The players act in the order in which they sit around the gaming table,
clockwise from the GMs. The baddies act in whatever order the GM wishes.

=== Moves
An adventurer has 5 moves, and here are some examples on how to use them.

IMPORTANT: Moves do not carry over to the next round; use them or lose them.

.Moves
[%header,cols="^1,11"]
|===
| Moves | Description
| 1     | Move 1 meter in good terrain
| 1     | Ready a potion from a belt pouch
| 1     | Draw a weapon from your sheath or equivalent
| 1     | Switch to a new quiver
| 1     | Drop a light shield
| 2     | Open a door
| 2     | Mount or dismount
| 2     | Move 1 meter in bad terrain
| 2     | Get up from a prone position
| 4     | Remove your helmet
| 5     | Drop a functional heavy shield
| 5     | Ready a spellbook from your backpack
|===

=== Actions
When a character has performed their moves, they get to take their action.
Here are some examples of actions:

* Attack with a readied weapon.
* Unarmed attack.
* Drink a readied potion.
* Cast a spell with a readied spellbook via <<Basic Spellcasting>>.
* Drop an heavy shield.
* Use a special ability.

An action can also be converted to 3 moves that must be used right away, and do
not carry over to the next round.

=== Attacks & Damage

Whenever you attack someone, you must first make an attack check.
After that, you make your damage roll, which depends on the type of weapon you're using,
and whether or not you are skilled at using said weapon.

==== Attack Check
* If you use a ranged weapon, the attack check is an adversarial _wisdom_ check.
* If you use a melee weapon, or you use unarmed combat, the attack check is an adversarial _strength_ check.
* If you attack someone who is 2 or more levels lower than you, your attack check is easy.
* If you attack someone who is 2 or more levels higher than you, your attack check is difficult.
* If you are not <<weapon_skills,skilled>> at using your weapon, your check is difficult.

==== Damage Roll
When you hit a baddie, you roll a die to see how much damage you deal.
The die depends on the type of weapon you used.

See the <<adventurer_damage_rolls_table>> table to find your damage die.

NOTE: If you have the <<great_weapon_specialist,Great weapon specialist>>
special ability, you are also skilled in using heavy melee weapons.

[[critical_hit]]
Critical hits::
If you roll a <<nat1>> on your attack check, you get an extra action for free.
You do not get any moves, but you can use your action any way you like,
including attacking the same opponent again.

==== Weapon Wear
If you roll a <<nat20>> on your attack check, you must roll your damage die. If you
roll the minimum possible value, your weapon becomes unusable and must be
repaired before it can be used again. It can be repaired by a weaponsmith, a
process that takes hours of work and requires a weaponsmith workshop.

=== Defense
When a baddie attacks you, you make a defense check to see if you avoid the
damage. The GM does not make an attack check for the baddie.

Melee Defense Check:: When a baddie attacks you in melee combat, you make a
_dexterity_ check. If successful, you dodge the attack. If you’re unsuccessful,
you lose a number of hit points equal to the attacker’s damage check.

Ranged Defense Check:: When a baddie attacks you at range, you make a _wisdom_
check. If you succeed, you dodge the attack, but if you fail the check, you’re
hit and take damage.

==== Armor
You can wear up to five pieces of armor: a helmet, a cuirass, a gauntlet, of
greaves, and a shield.

===== Armor Grants Hit Points
Each piece of armor you wear increases your hit point total by a number of
points. The better the armor piece, the more hit points you get.

When you don armor, your <<hit_point_total,hit point total>> and your current
number of hit points both increase by the number of hit points provided by the
armor piece.

When you doff armor, your <<hit_point_total,hit point total>> and your current
number of hit points both decrease by the number of hit points provided by the
armor piece. (which means that, technically, you can die if you are very low on
hit points and remove an armor piece).

===== Armor Requires Skill
If you are wearing one or more armor pieces that you are not proficient with,
you become <<encumbered,encumbered>>, which makes every check you make difficult.

===== Armor Wears Out
If you roll a <<nat20,nat20>> on you Defense Check, and the damage dealt
was higher than your worst armor piece (the one that provided fewest hit points),
that armor piece becomes broken, and no longer provides any hit points.

WARNING: if you're wearing two or more pieces of broken armor, you become
<<encumbered,encumbered>>.

IMPORTANT: 
====
The armor can be repaired. So you should make a note of how many HP the armor
piece granted initially.

But Only an <<armorer,armorer>> can restore the armor piece to its former
glory.
====

=== Damage and Death
When you hit a baddie, you roll a damage roll to see how many points of damage
you deal. The dice used in the damage roll depends on your class, your
abilities, and the weapon (or spell) you used in the attack. Your opponent
subtracts your damage from their current number of hit points. If a baddie is
reduced to zero hit points (or below) they die instantly.

==== Taking damage
The GM tells you what the damage die is, and you roll it, and subtract the
result from your hit points.

IMPORTANT: You can never go below zero hit points; when you have reached
0 HP, any further damage will result in <<trauma_table,trauma>>.

==== Baddies With Zero Hit Points
Baddies die when they reach 0 HP. The only way to bring them back is to revive
or resurrect them with powerful magic. If you want to stun a baddie, you can
use certain items, spells, and abilities.

[[zero_hp]]
==== Adventurers With Zero Hit Points
If you reach 0 hit points, you permanently decrease a random stat by one point,
and then you must roll on the <<death_table,Death Table>>.

.Reaching zero hit points
[example]
--
You have 4 HP left, and an angry troll hits you for 12 points of damage. You're
brought down to zero HP.

You roll a d6 to find out which stat to reduce. You rolled a 2, so your
_dexterity_ is reduced by 1.

You now have to roll on the <<death_table,Death Table>>: You roll a 53, meaning
you're unconscious and <<dying,dying>>, which in turn means you will have to roll a
d20 every round from now on, and a nat20 will result in your death.
--

===== Taking Damage At Zero Hit Points
If you take damage and you are already at zero hit points, you lose 1d4 points
from a random stat, and you must roll on the <<trauma_table,Trauma Table>> and add the amount of
damage taken to your d100 roll.

.Kicking a player character while they're down
[example]
--
You’re have zero hit points, you have already rolled on the
<<death_table,Death Table>> once (and survived, for now), and some dastardly baddie strikes you for
5 damage.

You first roll a d6 and a d4 to reduce one of your stats, you rolled a 6 and a
3, meaning your _charisma_ is lowered by 3 points.

You then roll on the <<trauma_table,Trauma Table>> and add 5 to your d100 roll
(because you received 5 points of damage). You rolled _7+5=12_, meaning you did
not suffer any trauma effects, you lucky bastard.
--

==== Death table

[[death_table]]
.Death Table
[%header,cols="^1,11",grid=none,frame=none,stripes=odd]
|===
| d100          | Effect
| 100           | You’re destroyed.
| 99            | You’re dead.
| 76-98         | You’re comatose and dying.
| 25-75         | You’re unconscious and dying.
| 02-25         | You’re unconscious.
| 1             | You’re still awake. At 1 HP, but prone.
|===

Destroyed:: You’re extremely dead; You must roll twice on the Trauma Table and
mark any temporary losses as Reversible. Only great resurrection magic,
accessible only to elites, can bring you back to life, and the costs of doing
so are grave.

Dead:: You’re dead; you must roll on the <<trauma_table,trauma table>> (in case
you are revived or turn into an undead).

[[dying]]
Dying:: You’re near death; you must roll on the trauma table. Every round, at the
beginning of your turn, you must make a d20 roll; if you roll a nat1, you are
no longer dying, but unconscious, and if you rolled a nat20, you are dead.

Comatose:: You’re in a deep coma. If you receive conventional medical care, you
will wake up in a matter of hours; make a _constitution_ check every hour to see
if you wake up. If you receive magical healing, you will wake up in a matter of
minutes; make a _constitution_ check every minute to see if you wake up.

Unconscious:: You are unconscious; if you receive any kind of healing, you will
wake up right away, otherwise you will wake up within 2d6 hours.

==== Trauma Table
The trauma table is used when you take damage after being reduced to 0 hit points.

[[trauma_table]]
.Trauma table
[%header,cols="^1,^2,8",stripes=even,frame=none,grid=none]
|===
| Roll      | Type          | Effect
| 101+      | Amputation    | Lose a random limb
| 100       | Permanent     | -1d4 to random stat
| 89-99     | Permanent     | -1d8 maximum hit points
| 90-98     | Reversible    | -1 moves
| 81-89     | Reversible    | -1 to _charisma_
| 71-80     | Reversible    | -1 unencumbered item slot
| 61-70     | Temporary     | -1 moves
| 51-60     | Temporary     | All checks are difficult
| 41-50     | Temporary     | -1d6 to random stat
| 31-40     | Temporary     | 1d8 to maximum hit points
| 21-30     | Reversible    | Battle scar
| 01-20     | -             | No trauma.
|===

[horizontal]
Amputation:: You lose an arm or a limb. Roll 1d4 to find out which. Roll
_dexterity_ or _constitution_ (your choice) if you succeed, you only lose half the
limb. Otherwise you lose all of it. Your limb can regrow if the restoration
spell is used.

Permanent:: This trauma is permanent. There is no way to undo it or reverse it.

Reversible:: This type of trauma can be reversed with powerful restoration magic.

Temporary:: lasts for 1d20 days or it can be reversed with restoration magic.

NOTE: The restoration spells referred to here are not basic, and adventurers
cannot cast them themselves. You can find more info on such spells in
The Hero's guide and Elite's guide.

=== Healing and regeneration
You can regain hit points in various ways, but you can never heal or be healed
beyond your <<hit_point_total,hit point total>>.

Resting:: Resting for 8 hours, at least six of which are spent sleeping, will
allow you to regenerate a bit; roll your <<recovery_die,recovery die>>, and
increase your hit points by that number. Aside from sleeping, eating, and
keeping watch, you cannot do anything of consequence while resting.

____
An adventurer regenerates 1d8 hit points after a meal,
6 hours of sleep, and two hours of rest.
____

Magical Healing:: Spells (such as <<Heal (X)>>), potions, and powers often
allow you to instantly recover hit points, usually by rolling a number of
recovery dice.

== CONDITIONS

Conditions can affect characters and baddies.

//START_SORT::

ZEncumbered:: [[encumbered]]
All checks become <<difficult,difficult>>, meaning that you
have to roll 3 points lower than you normally would to succeed.

Exhausted:: [[exhausted]]
Same as encumbered AND your number of moves is halved, rounded down.

Frightened:: [[frightened]]
You cannot move closer to what you believe is the source of
your fear. You have 2 fewer moves than normal.

Poisoned:: [[poisoned]]
You temporarily lose 1d4 points of a random stat every minute. After
rolling your stat loss, you make a _constitution_ check with disadvantage. If
successful, the poisoned condition is removed. You die if any of your stats are
reduced to zero. If you die from poison, only Greater Revival can restore you
back to life.

Demoralized:: [[demoralized]]
On your next turn you must spend all your moves (if possible)
retreating from your opponents. When you have done that, the demoralized
condition goes away.

On Fire:: [[on_fire]]
You are on fire. At the start of every round, just before you get to act,
you take 1d4 points of damage, and then you roll a _constitution_ check. If you
succeed, the fire goes out. If you failed, the fire persists, and if you
rolled a nat20, the damage die increases (for instance, from 1d4 to 1d6).

//END_SORT
//}}}

//{{{ MAGIC
== MAGIC

=== Spellbooks
A spellbook is a magical tome, book, or scroll. It takes up one Item Slot,
contains a single spell and can only be used if it has enough magical charge.

Spellbooks need magical charge (<<Usage Points,usage points>>) to
work. When a spellbook runs out of <<Usage Points,usage points>>, it becomes
inert and unusable until it is recharged. A spellbooks maximum
<<Usage Points,usage points>> depends on the power and skill of its creator.

Adventurers can recharge spellbooks via <<Basic Recharging>>.

NOTE: Adventurers cannot create spellbooks,
so the rules on how to create spellbooks is not included here.
Suffice it to say that normal spellbooks only have a single usage point,
and only very powerful tomes have more.


=== Basic Spellcasting
Adventurers can cast <<basic,basic>> spells (all spells in this document are
<<basic,basic>>). But they must have a spellbook containing the given spell
and:

Requirements::
* The spellbook has at least one <<Usage Points,usage point>>.
* You are holding the spellbook in both hands.
* There’s enough light for you to read the text, you are able to speak, and you aren't
  encumbered or restrained.
* The spell’s level isn't higher than yours.
* It is an action to cast a spell (unless otherwise specified in the spell’s
  description, some spells can take a long time to cast).


Procedure::
* Remove 1 <<Usage Points,usage point>> from the spellbook.
* Then make an _intelligence_ check:
* If your _intelligence_ check was successful, you cast the spell, and it takes
  effect. If unsuccessful, the spell fizzles. If you rolled a nat20, the
  spellbook instantly loses all its <<Usage Points,usage points>>.
* If your spell fizzled, you can try again next round if your spellbook still
  has charge.


=== Basic Ritual Casting
Some spells can be cast without exhausting the spellbook, but it takes more
time to do so.

Requirements::
* The spell must have the <<ritual,ritual>> property,
* You must have the spellbook on you while the ritual is performed.
* The spellbook must have at least one <<Usage Points,usage point>>.

Procedure::
* You spend 10 minutes chanting and reading from the spellbook.
* Then you spend one consumption of magic components.
* Then you make an _intelligence_ check; if successful, you cast the spell. If
  unsuccessful, the spell fizzles, but you can try again later. If nat20, the
  spellbook loses all its <<Usage Points,usage points>>.

=== Basic Recharging
Adventurers can recharge <<basic,basic>> spellbooks, restoring them to their maximum
<<Usage Points,usage points>>.

Requirements:: The spell in the spellbook must be <<basic,basic>>, and its level must
not be higher than yours.

Procedure:: You start by spending one consumption of magic components, followed
by 30 minutes of ritualistic work. Then you make an _intelligence_ check. If
the check succeeds, you have recharged the spellbook, otherwise you must try
again.

==== Spell Properties
The properties of a spell is listed in bold font right underneath the spell's
name.

.Spell properties
[frame=none,grid=none,stripes=odd,cols="2,10"]
|===

| basic [[basic]] |
All basic spells can be cast by adventurers, and all spells in this document
are <<basic,basic>>. Higher level characters have access to more advanced types
of spells.

| ritual [[ritual]] |
These spells can be cast via Basic Ritual Casting, but can also be
cast normally via Basic Spellcasting.

| multilevel [[multilevel]] |
There are many versions of this spell, each with its own level. +
See the <<example_multilevel>> example for an illustration.

| trance  [[trance]] |
You must be seated to cast a trance spell, and you must remain seated
for its duration. +
//
The spell stops instantly if you:
    a) take damage,
    b) make a defense check,
    c) get up,
    d) move,
    or e) take an action. +
//
You can speak, breathe, and adjust
your position to remain comfortable, and nothing more.

| focus [[focus]] |
These spells cut their duration short and stop instantly if you
cast another spell,
take damage,
or stop focusing on keeping the spell going.


| Range |
The range of the spell.

| Duration |
The duration of the spell

| LVL [[LVL]] |
The level of the caster (i.e. not the spell). The potency, duration, or range
of certain spell increases with the casters level.

|===

[[example_multilevel]]
.Spells with <<multilevel,multilevel>> tag
====
The <<Tragic Missile (X)>> spell is technically not a single spell. It exists
as Tragic Missile 1, Tragic Missile 2, and so on all the way to Tragic Missile
10. Tragic Missile 10 is much more powerful than Tragic Missile 1.
====

//}}}

//{{{SPELLS
== SPELLS
All spells listed in this section are <<basic,basic>> and can be used by
adventurers.

// START_SORT ===
=== Alertness (X)
*Level 1, <<multilevel,multilevel>>, <<focus,focus>>*

Anyone within 3 meters of the caster gets advantage on checks that involve
spotting hidden things, traps, and enemies, The effect persists even if they
move further away from the caster. The spell ends when it has provided
advantage to 2·_X_ checks in total (i.e. not to each recipient) or when the
caster stops focusing on the spell, whichever comes first.


=== Alluring Attraction (X)
*Level 1, <<multilevel,multilevel>>, <<ritual,ritual>>, duration: _X_ days*

Of the next _X_+1 _charisma_ checks you make, you have advantage on checks that
have a strong flirting component or involve physical attraction.


=== Animal Friendship (X)
*Level 1, <<focus,focus>>, <<multilevel,multilevel>>, <<ritual,ritual>>*

Within the next _X_ + 1 hours, all _intelligence_, _wisdom_, and _charisma_
checks made to befriend animals have <<advantage,advantage>>. On top of that,
there is a 50% chance that an animal that would have otherwise been hostile
towards you, is now simply cautious.


=== Armor (X)
*Level 1, <<multilevel,multilevel>>, <<ritual,ritual>>*

?????????????????????????????????????????????????


=== Banking Transaction (X)
*Level 3, <<multilevel,multilevel>>, duration: 5 minutes*

You touch a magical Bank Book and transfer coins into- or out of it. You cannot
bring the book’s balance below zero.

It takes _X_ minutes to cast this spell, and it requires _X_ gold pieces, which are
consumed by the spell (yes, you must have at least _X_ gold coins on hand to
withdraw your money).

The number of coins you can withdraw/deposit is 10·X·X·_X_ (i.e. 10·X³).


=== Bug Repellent (X)
*Level 1+, <<multilevel,multilevel>>, duration: _X_ minutes.*

You target a nonmagical item within _X_ meters. The item starts emitting sounds
and odors that repel insects and other vermin. The spells area of influence is
a sphere with a radius of 2·_X_ meters

This spell has no negative effects on non-vermin.

Vermin whose level is _X_ or higher are completely unaffected.

Vermin whose level is lower than _X_ must make a normal _wisdom_ check or move out of
the repellent area. Even if the check is successful, any other checks made
within the repellent area are difficult.

Mundane vermin, such as normal spiders, worms, ants, flies, wasps, etc. are
level 0. Supernatural vermin such as giant wasps, etc. are at least level 1.

=== Calm Animal (X)
*Level 1, <<multilevel,multilevel>>*

You calm a hostile animal within 10 + _X_ meters and whose level isn't higher
than _X_. The animal no longer considers you or your party as threats, and will
simply wander away if possible.

=== Club
*Level 1, duration: <<LVL,LVL>>+5 rounds.*

A magical wooden club appears in your hand. You are proficient at wielding this
one-handed weapon, and your damage die is 1d12 when doing so. The club
dissolves into dust after <<LVL,LVL>>+5 rounds, or instantly if you let go of it.

=== Command (X)
*Level: 1, <<multilevel,multilevel>>, duration: 1 round.*

You give a creature within _X_ meters a one-word command and then make a _charisma_
check. If you’re successful, the target will attempt to execute the command as
best it can, and as it understands the command, but only for one round, and
only if the command would not result in self harm.

This spell does not affect targets whose level is higher than _X_.

If the target’s level is lower than _X_ the _charisma_ check is easy.

Any creature targeted by this spell will become hostile towards you, regardless
if they executed the command or not.

Commands such as flee and run are straight forward, but a command such as drop
can be interpreted in many ways (drop the thing you’re holding, or drop prone,
or drop the subject).

=== Command Fire (X)
*Level 1, <<trance,trance>>, <<multilevel,multilevel>>, range: 2·_X_ meters, duration: 2·_X_ minutes.*

When you've just cast the spell you select a fire. It can be as small as a
candle and as large as _X_ square meters. You can now give the fire a command:

Candle:: You shrink a bonfire to the size of a candle.

Bonfire:: You make a candle grow to the size of a bonfire, provided there is
sufficient fuel available.

Grow:: If the fire is the size of a bonfire, it expands to take up an entire
square meter. If the fire is 1 square meter or larger, it expands a further
square meter. You can control the direction of the fire’s growth, but you can
only make it expand to areas where there is plenty of fuel.

Reduce:: If the fire is larger than 1 square meter, it shrinks by 1 square
meter. If the fire is 1 square meter in size, it shrinks to the size of a
bonfire. If the fire is the size of a bonfire, it goes out, not producing any
additional smoke in the process.

=== Cure Exhaustion
*Level 1, <<ritual,ritual>>*

You target a willing person. If you make a successful easy _wisdom_ check, the
exhausted condition is removed from the target.

A creature that has been targeted by this spell becomes immune to it for 1 hour.

=== Danger Sense
*Level 2*

If you make a successful _charisma_ check, you get a sense, on a scale of 1 to
5, of how dangerous a given foe, group, situation, mechanism, substance, or
task.

Context is important: a high level paladin might be dangerous to her foes, but
completely harmless to her friends.

=== Detect Magic
*Level 1, <<ritual,ritual>>, duration: _intelligence_ minutes*

You can see magic items, and items that are affected by spells, such as an item
with light cast on it. The item must be within _wisdom_ meters. To you, magical
items start to glow after you've looked directly at them for a while. You need
to take things slow if you want to scan everything around you. The “glow” can
penetrate cloth and paper, so a magical ring in a pocket or a magical pen
underneath a sheet of paper can be detected.

=== Detect Traps (X)
*Level 1, <<focus,focus>>, <<multilevel,multilevel>>*

You can sense if a trap is within 10+_X_ meters, but you only know where it is
when the trap is within _X_ meters of you.

This spell lasts for 30 minutes, plus _X_·10 minutes, or until you stop focusing
on it.

=== Detect Undead
*???*

See undead through walls?

Sense Undead?

=== Fey Flames
*Faerie Fire ???????????*


=== Fierce Fortune (X)
*Level 1, <<multilevel,multilevel>>*

An ally within _X_ meters gets advantage on their next <<Attack Check,attack>>-
or <<Defense,defense check>>, provided it occurs within _X_+1 rounds.

=== Find Flora & Fauna
*Level 1, <<focus,focus>>,  ??????*


=== Flaming Fingers (X)
*Level 1, <<multilevel,multilevel>>*

Jets of fire spew forth from your burning hands, scorching up to _X_ adjacent
targets of your choice. If you make a successful _intelligence_ check, each
target receives 1d6+_X_ damage, otherwise they receive 1d6 damage.

=== Friendliness (X)
*Level 1, <<focus,focus>>, <<multilevel,multilevel>>*

Your _charisma_ checks are easy for the next _X_ minutes.

=== Ghost Mount (X)
*Level 2, <<focus,focus>>, <<multilevel,multilevel>>*

You construct a ghostly, translucent horse that only you can ride. It appears
instantly under you, so you’re instantly mounted. The horse increases your
movement rate such that, whenever you spend one move, you move up to _X_ meters.
The mount has 2·_X_ hit points, all its primary stats are 8+X.

A constructed being, a Ghost Horse is immune to charm, sleep, fear, illusions,
demoralization, and other mind-based spells, as well as spells where
_intelligence_, or _charisma_ checks affect the spell’s outcome.

The spell lasts up to 3·_X_ rounds, but stops earlier if you stop focusing on it
or if you dismount.

=== Ghost Servant (X)
*Level 1, <<focus,focus>>, <<multilevel,multilevel>>*

You construct a ghostly, humanoid that only you can see, hear, or smell. You
can send it telepathic commands, and it will obey you to the best of its
abilities, and without question or hesitation.

The servant appears within 3·_X_ meters, and must stay within 10·_X_ meters.

* It can move up to _X_ meters per round.
* Its primary stats are all 2·X, and its hit point total is also 2·X.
* It cannot hear, speak, read, write, or make sounds, but it does understand
  your telepathic commands. It can lift and carry _X_ item slots.
* It cannot do difficult or demanding things such as disarming traps, but it
  can do simple tasks such as moving stuff or doing the dishes.
* It is immune to charm, sleep, fear, illusions, demoralization, and other
  mind-based spells, as well as spells where _intelligence_, or _charisma_
  checks affect the spell’s outcome.

The spell lasts 10·_X_ minutes, until you stop focusing on it, or the servant
gets more than 10·_X_ meters away.

=== Gills (X)
*Level 1, <<focus,focus>>, <<multilevel,multilevel>>, <<ritual,ritual>>*

You and 1+_X_ willing creatures within 4+_X_ meters can breathe water (and only
water) for the next 2+_X_ minutes. The spell also ends if you stop focusing on
it.

=== Gloom (X)
*Level 1+, <<multilevel,multilevel>>, range: 2+_X_ meters*

You target an object within range. The object emits a ghostly dark aura that
dulls all non-magical sources of light within 5+_X_ meters so much that their
radius is reduced to 1 meter while they are within the effective range of the
gloomy object.

This spell can also dull magical light sources if their spell level or item
level is lower than _X_.

The dulled light sources cannot be seen by creatures more than 1 meter away
from them.

You cannot target an object that is currently being held, worn or touched by
another creature.

The gloomy area looks like dense fog when seen from the outside.

=== Heal (X)
*Level 1+, <<ritual,ritual>>, <<multilevel,multilevel>>, range: 3+_X_ meters*

You heal a creature within range. It recovers _X_ recovery dice.

=== Hurt (X)
*Level 1+, <<multilevel,multilevel>>, <<ritual,ritual>>, range: _X_+3 meters*

You use dark necrotic magic to harm a creature within range. If you make a
successful _wisdom_ check, the creature loses _X_d8, otherwise it loses _X_d4

=== Illuminate (X)
*Level 1+, <<multilevel,multilevel>>, range: 2+_X_ meters, duration: _X_ hours.*

You target an object within range. The object lights up with a steady and
bright light that illuminates a radius of 10+_X_ meters.

You can attempt to cast this spell on the eyes of a creature within range,
effectively blinding it (if it uses eyes and light to see). It requires a
successful difficult _charisma_ check, and if the creature’s level is higher
than _X_, the spell fizzles.

You must make a successful _charisma_ check to cast this spell on an item
currently held, worn, or touched by a living creature, and if the creature’s
level is higher than _X_, the spell fizzles.

=== Intruder Alert
*Level 1, <<ritual,ritual>>, duration: _wisdom_ hours*

Upon casting the spell, you touch a door, tent flap, a lock, or similar
moveable object. If the object is disturbed by a creature (but not the wind), a
loud alarm will “ring” inside your head. The alarm is loud enough to wake you
up, but quiet enough that you don’t wake up screaming.

=== Invisibility to Stupidity (X)
*Level 1, <<focus,focus>>, <<multilevel,multilevel>>, duration: 5·_X_ Rounds.*

Creatures with an _intelligence_ lower than _X_+2 cannot see you, smell you, or
detect you in any way, not even by touch.

=== Jump (X)
*Level 1, <<multilevel,multilevel>>*

When you cast this spell, you instantly jump _X_+1 meters in a direction of your
choice. You cannot reduce the length of the jump, but you can jump into a wall
or other obstacle. Doing so causes you to take 1d6 damage for each meter the
obstacle reduces your jump.

=== Lightning Touch (X)
*Level 1+, <<multilevel,multilevel>>*

You touch an adjacent target, who then takes _X_d6 damage. After rolling damage,
you make a _wisdom_ check. If successful, the target is knocked prone, and must
spend a number of moves next round to get up.

If the target is wearing three or more pieces of metal armor, you have
advantage on the damage roll and the _wisdom_ check.

=== Mage Might (X)
*Level 1, <<focus,focus>>, <<multilevel,multilevel>>*

For the next _X_ rounds, your _strength_ score becomes 15+_X_*0.5 (rounded
down).


=== Mage Torch (X)
*Level 2, <<focus,focus>>, <<multilevel,multilevel>>, range: _X_×5 meters*

You target a spot you can see within range. At that spot a magical ghostly
torch appears. By spending one <<moves,move>> you can move the torch up to 5
meters to a spot you can see and that is within range.

If you move so that the torch comes out of range, the spell stops and the torch
vanishes.

The torch disappears after 8 hours.

=== Magical Reading
*Level 1, <<ritual,ritual>>, duration: 8 hours*

You cast this spell on a spellbook or mundane book. It allows you to safely
read the book without falling for any mental magical traps the text may hold.
It also allows you to decipher (but not cast) spells in spellbooks whose level
is three levels higher than yours.

=== Magical Stone
*Level 1*
You touch a nonmagical stone or slingshot no larger than your fist. It becomes
magical, and flies towards an enemy within _wisdom_ meters at great speed. The
stone automatically hits the opponent, dealing damage equal to three times your
level.

NOTE: The stone can only hit the baddie if there is a direct line between the
stone and the baddie. It cannot curve or fly around obstacles.


=== Mend (X)
*Level 1, <<multilevel,multilevel>>*

You instantly repair a break, crack, scratch, or tear up to 5 + _X_ centimeters
from an object within _X_ meters that weighs no more than _X_ kg.  Mending a
nonmagical Armor Piece, Weapon, or Tool restores _X_ Usage Points. Once an item
has been mended, it becomes slightly magical for 1 day; it cannot be mend-ed in
that period, and it will be detectable with <<Detect Magic>>.

=== Mind Message (X)
*Level 1, <<multilevel,multilevel>>*

You target a creature within 5 plus 5_X_ meters, and telepathically send 10 plus
10_X_ words to it. It can telepathically reply with the same number of words. If
the recipient makes a successful _charisma_ check, no one notices its distraction
while receiving and replying.

=== Mustrum’s Mundane Shroud (X)
*Level 2, <<ritual,ritual>>, duration: _X_ days*

You select a magical item within 2 meters of you, weighing no more than _X_ kg.

This spell completely hides the fact that the item is magical; only observers
with a level higher than _X_ can detect the item’s magic, and that this spell
has been used to hide it.

=== Nostrum’s Magical Aura (X)
*Level 1, <<ritual,ritual>>, duration: _X_ days, range: 2 meters*

You select a nonmagical item within range, weighing no more than _X_ kg.

You give the item an invisible magical aura of your design. Anyone who uses
<<Detect Magic>>, identify or similar detection magic will think the item is
magical, and they will think the item has magical properties of your choosing.

Observers with a level higher than _X_ can detect that this spell has been
cast, and that the item is nonmagical.

=== Phantasm (X)
*Level 1, <<focus,focus>>, <<multilevel,multilevel>>*

You create a purely visual illusion of an object, creature, thing, or
phenomenon no bigger than 3 cubic meters. You can make the phantasm appear
anywhere you can see within 10·_X_ meters, and it must remain within that
radius at all times. You can move the phantasm 1·_X_ meters per round. The
spell ends after 5·_X_ minutes, if you stop focusing on it, or if something
substantial touches the phantasm (heavy smoke, sandstorm, a creature, etc.).

Creatures that have a reason to disbelieve the phantasm (such as creatures that
rely heavily on scent and sound, or people who find the phantasm incompatible
with their sense of “what ought to be” can make an adversarial _charisma_ check
to see the phantasm for what it is. The check is easy if the creature's level
is 2 or more higher than the caster's level, and difficult of the creatures
level is 2 or more lower than the caster's level.

=== Purify Rations (X)
*Level 2, <<ritual,ritual>>, <<multilevel,multilevel>>*

You purify 1 ration pack and 1 water skin’s worth of liquid per level of this
spell. The food and drink is completely safe to eat and drink; it does not
taste bad, and it is nourishing. This spell does not remove curses or other
magical effects that may affect the food and drink.

=== Read Script
*Level 2, <<ritual,ritual>>, duration: 10·_intelligence_ minutes*

You can read and understand any written language. This spell does not decode
cryptographic cipher text, but it does let you understand secret languages.

=== Remove Fear (X)
*Level 2, <<multilevel,multilevel>>, range: _charisma_ meters*

You target an ally within _charisma_ meters of you. The spell automatically
removes _X_ fear-based conditions such as <<demoralized,demoralized>>.

If the target suffers from more than _X_ fear effects, the GM chooses which to
remove.

NOTE: There are more fear effects than the ones described in this guide.

=== Shield
*Level 1, <<multilevel,multilevel>>, <<focus,focus>>*

For the next 5·_X_ rounds, all damage you receive is halved (rounded down).

If a baddie hits you for 5 points of damage, you only take 2 points of damage.
And if you’re hit for 1 point of damage, you take zero points of damage.

=== Slow Fall (X)
*Level 1, <<multilevel,multilevel>>, <<ritual,ritual>>*

You touch  a nonmagical wearable item, weighing at least 1
<<Item Slots,item slot>> and worth at least _X_ silver pieces.
The item becomes a consumable magical item with _X_
<<Usage Points,usage points>>.
When the wearer of such an item falls more than one meter, the magic in the
item activates and the fall is slowed so the wearer does not take any damage.
When the wearer has landed, the item loses one Usage Point. When all the item’s
Usage Points have been spent, the item crumbles to dust.

=== Snooze (X)
*Level 1+, : <<multilevel,multilevel>>*

This spell can send one or more creatures to sleep, but it can only affect
creatures that need regular sleep, and whose level isn't higher than _X_.

Select a baddie within 10 meters. If the target has more hit points than your
_charisma_, the spell fizzles, otherwise the baddie falls asleep.

If the spell didn't fizzle, you may make another _charisma_ check, and if it
succeeds, the spell affects _X_ additional creatures within 5 meters of the
first target.
//
This spell affects baddies and allies alike; these extra affected creatures are
selected in order of closeness to the first target.

Creatures sleep for a number of rounds equal to your _charisma_, however a
sleeping baddie wakes up if they take damage.

=== Spenser’s levitating Bowl
*Level 1, <<ritual,ritual>>, duration: _intelligence_ · 10 minutes.*

You conjure a large vaguely bowl-shape plate that can carry as many
<<Item Slots,item slots>> as your _strength_ score.

It levitates about a meter above the ground, and can move half as fast as an
adventurer. It is able to “climb” stairs and hills, but cannot scale walls or
steep cliffs.

=== Spider Climb (X)
*Level 1, <<focus,focus>>, <<multilevel,multilevel>>*

This spell enables you to cling to almost any surface as long as it is not
overly wet, oily, or slippery. You can spend 3 moves to spider-move 1 meter.
The spell lasts _X_ minutes, but ends if you stop focusing on it.

=== Spout (X)
*Level 1, <<focus,focus>>, <<multilevel,multilevel>>*

You cause 10·_X_ liters of water to pour out of a wineskin, teapot, keg, or
similar; at a speed of about 1 liter per round (10 liters per minute)

=== Strength of Stone (X)
*Level 1, <<focus,focus>>, <<multilevel,multilevel>>, <<ritual,ritual>>*

You target a willing ally within 2·_X_ meters, making all their _strength_ checks
easy for a 2·_X_ rounds.

=== Taunt
*Level 1, <<multilevel,multilevel>>, duration: 1 round*

You target _X_ creatures within 10+_X_ meters. For each target, if you can make a
successful adversarial _charisma_ check (which is difficult if the target’s level
is higher than yours), the target will rush and attack you in melee combat on
its next turn.

=== Tragic Missile (X)
*Level 1+, <<multilevel,multilevel>>, range: _wisdom+X_ meters*

You fire a frightening magical missile against a baddie within range. When
struck, the baddie takes _X_ d4 damage, and then you make an
<<adversarial_checks,adversarial>> _charisma_ check; if successful the baddie
becomes <<demoralized,demoralized>>.

=== Vines (X)
*Level 2, <<focus,focus>>, <<multilevel,multilevel>>*

You target a point within 10+_X_ meters. Vines and wild growth sprouts from the
ground in  a radius of _X_ meters around that point. Each creature inside the
affected area must make a successful _strength_, _dexterity_ or _intelligence_
check (their choice) each round, or all they have zero moves that round.

=== Wizard’s Mark
*Level 1, <<ritual,ritual>>, <<focus,focus>>*

Makes a piece of chalk magical so it makes invisible marks that only you can
see.

Other than being invisible, the marks behave as normal chalk marks, which
means they can be rubbed out or washed away with water.

The chalk stops being magical once you stop focusing on the spell, or after
_charisma_ hours. But the marks remain visible to you, and invisible to others.

//END_SORT
//}}}

//{{{DICTIONARY
//START_SORT::
Adventurer::
All PCs start out as adventurers and have to level up to level 3 before they
can get their hero class.

Adversarial check::
A check that is affected by the level of the opposition. For instance, if
you're attacking a baddie who is 2 or more levels higher than you, your check
is difficult.

Attack check, melee::
A check to hit an opponent. It's an adversarial _strength_ check, and it is
difficult if you're not skilled at using the given weapon.

Attack check, ranged::
A check to hit an opponent. It's an adversarial _wisdom_ check, and it is
difficult if you're not skilled at using the given weapon.

Baddie::
A person, creature, or monster that is hostile or otherwise considered to be
your enemy.

Check::
You roll your d20 against a given target number (usually one of your stats). +
_For example: when rolling a strength check you roll a d20 and must roll lower
than your strength to succeed._

Difficult::
Difficult checks have a target number that’s 3 lower than normal checks.

Easy::
Easy checks have a target number that's 3 higher than normal checks.

GM::
The Game Master.

Hit Points (HP)::
A unit of health: your character has a number of hit points, you lose some of
them when you take damage, and if you lose all of them, you must roll on the
<<death_table, death table>>.  + Baddies and NPCs also have hit points, and
when they lose all of them, they die.

Initiative::
A check made at the beginning of a combat round to see which side gets to act
first.

Level (LVL)::
A character can have a level between 1 and 10. Baddies, traps, locks, spells,
and various tasks can also have a level.

Melee defense check::
A check to avoid being hit. This is an adversarial _dexterity_ check.

NPC and NPCs::
Non player character(s). These persons and creatures are played by the GM.

Nat 1::
If you roll a d20 and it shows the number 1, you rolled a natural (nat) one.

Nat 20::
If you roll a d20 and it shows the number 20, you've rolled a natural (nat)
twenty.

PC and PCs::
Player Character(s).

Proficient::
It is difficult or impossible to use an armor, weapon, or specialist tool you
are not proficient with.

Roll::
Rolls are generic die rolls where you roll one or more specified dice, such as
_3d6_, _1d10_, _2d8+2_, etc. The most common type of roll is the damage roll,
where you roll your damage die for the type of weapon you're using.

TN::
Abbreviation of Target Number.

Target number::
The number you must roll below (usually with your d20) in order to make a
successful check.

Y.A.R.I.S::
It’s an acronym: Yet Another Reduced Instruction Set.

//END_SORT
//}}}
uction Set.

//END_SORT
//}}}

