= Elite's guide to doom & destruction & stuff
include::vars.adoc[]

:stylesheet: style.css
:doctype: article
:icons: font
:sectlinks:
:toc:
:toclevels: 1
:toc-placement!:
:experimental:
:stem:
:xrefstyle: basic

== STUFFFF

*   CHAMPION
**      Paladin
***         __SPIRIT MOUNT__
****            Instantly summon and mount a horse or similar mount
****            It can "die", but it can be resummoned
****            Cooldown.
***         COMMANDER
****            Give other people orders/actions
***         SPIRIT ARMOURY
****            Summon and instantly don a set of armor, shield,
                and weapon from a special storage dimension
****            Cooldown / usage points.

**      Shaman
***         __SPIRIT BEAST__
****            Can help you in combat.
****            Can be resummoned if it dies, but there is a cooldown.
****            Maybe it's just a spellbook
***         SHAPE SHIFTING
****            Basically a were-thing (werewolf, werebear)
****            Claw Shape
****            Low Light Vision
****            Natural Armor
****            Climbing, Jumping
****            High movement rate

**      Paragon
***         __SPIRIT COMPANION__
****            Time limit & Cooldown
****            An intangible blob of shimmering light with no shape
****            Can only be attacked with very special spells
****            Can heal (a la Healing Spirit from DnD)
****            Can {focus} on a spell for the paragon
****            You can cast spell through the spirit companion
****            You can see through its eyes, but its very very blurry
***         TOME KEEPER
****            Spirit Armoury where K spellbooks can be kept
***         DESTROYER
****            You have all the __Terror of XXX__ abilities.
****            When you cast spells against these beings all your
                spellcasting checks and damage rolls have advantage.

*   MAGE
**      Bone Tamer
***         SPIRIT ARMOURY - CAN CONTAIN BONES
***         ANIMATE BONES
***         CONTROL BONES
****            Manipulate bones in living beings
****            Control
****            Heal
****            Damage
**      Illusionist: Mirror Image(s)
***         MIRROR IMAGE
**      Elementalist
***         SUMMON ELEMENTAL
**      Apex
***         SPELL ARMOURY
****            Contain K spellbooks in a separate storage dimension
***         APEX CASTING
****            Cast spells from memory, draining HP instead of book
***         ARMOURY CASTING
****            Cast spell from book in armoury

* WARRIOR
**  Berserker
***     Already Done

**  War Dancer
***     SPIRIT WEAPON (METEOR HAMMER):
****        Conjured out of thin air
****        Constrict
****        Disarm
****        Surprise Strike
****        Ranged Melee Attack
****        Chaotic Strike Strike (decrease TN, but increase critical threshold)

**  Fighter
***     ARTILLERY:
****        Spirit Arrows and/or bow
****        Exploding spirit arrows
****        Sniper arrow (fly through walls)

***     JUGGERNAUT:
****        Spirit Armor
****        Slow Movement
****        Disadvantage on attack checks.
****        Outgoing damage has disadvantage.
****        Advantage on Defense Checks
****        Incoming damage has disadvantage.

***     SKIRMISHER:
****        Fast Mover
****        Rearm (magical rearm) when engaging this stance

***     OFFICER:
****        Analyze Opponent


//{{{ ELITE WARRIORS
== ELITE WARRIORS

=== Berserker

The berserker is a very dangerous combatant, almost impossible to kill in
combat. When you pick this class you instantly gain access to the very powerful
berserker's range; an ability that keeps growing in power as your level
increases. Berserker's rage is the only active ability the berserker class
provides; this makes them both tough and easy to play.

==== Level 6

===== More Hit Points
Your {hit_point_total} is increased by 12.

===== Better Stats
Increase your __constitution__ and __strength__ by one point each, and increase
one other stat by one point as well.

===== Bonus Hit Points
You gain 3 bonus hit points per unused item slot. Other adventurers only get one.
This hit point bonus increases by one every time you gain a level, such that when
you're level 10, you gain 7 bonus hit points per unused item slot.

===== No Armor
You fight without armor and shields. If you equip any armor pieces or shields,
you lose the ability to go berserk.

==== Weapon Skills
You are skilled at using light melee weapons, heavy melee weapons, and unarmed
combat.

===== Berserker's Rage
You can choose to go berserk when a baddie attacks or damages you or one of
your allies. Your rage continues as long as you or your allies are attacked or
damaged by baddies, Your rage ends if an entire combat round passes without you
being aware that you or your allies have been attacked or damaged by baddies.

The berserker's rage has the following properties:

* The damage you deal with heavy weapons is doubled.
* You gain 2 extra moves, and that number increases by one every time you
  gain a level, such that when you are level 10, you have 7 extra moves per
  round.
* You have {advantage} on all  __strength__, __constitution__, and
  __dexterity__ checks.
* You have {disadvantage} on all  __intelligence__, __wisdom__, and
  __charisma__ checks.
* You do not roll on the {death_table} when you reach zero hit points; you
  remain alive and kicking. But when you are at zero hit points and take
  damage, you must roll on the {trauma_table}, just like other adventurers when
  they take {damage_at_zero_hp}.
* If you reach zero hit points the damage you deal with heavy weapons is
  tripled instead of doubled.
* If you are at zero hit points when your rage ends you must roll on the
  {death_table} with {disadvantage}.
* If your berserker's rage ends, and you are not at zero hit points, you take
  {L}d6 damage. Should this damage cause you to reach zero hit points, you do
  not roll on the {death_table}, but you do become {exhausted} until you regain
  at least one hit point.

==== Level 7

===== More Hit Points
Increase your {hit_point_total} by 1d8. Roll with {advantage}.

===== Better Stats

First::
For each of your stats, you roll a d20; if the roll is higher than the stat,
that stat is increased by 1 point.

Then::
If your strength is lower than 15, increase it by 1, and if your
constitution is lower than 15, increase it by 1.

===== Bonus Hit Points
You gain now gain 4 bonus hit points per unused item slot.


==== Level 8

===== More Hit Points
Increase your {hit_point_total} by 1d8. Roll with {advantage}.

===== Better Stats
For each of your stats, you roll a d20; if the roll is higher than the stat,
that stat is increased by 1 point.

===== Bonus Hit Points
You gain now gain 4 bonus hit points per unused item slot.

==== Level 9


==== Level 10


=== War Dancer


=== Fighter

// ELITE WARRIORS }}}

// {{{ ELITE CHAMPIONS
== ELITE CHAMPIONS

=== Shaman (Champion Specialization)
* Nature Spells.
* Totems instead of spellbooks.
* Only non-metal armor.
* Abilities (choose one, maybe more at later levels).
** SHAPE SHIFTER:
   Shift into animals and elementals.
   Very high damage.
   Very high regeneration.
** SPIRIT BEAST
   It cannot die, but can be temporarily sent back to the spirit world.
   Competent fighter.
   Completely silent.
   Immune to fear, charm, etc.
   Frenzy (à la detonate)


=== Paladin (Champion Specialization)
* Basically a continuation of champion, but primarily
  strengthening melee ability.
* Heavy Armor
* Shield is a must.
* All item slots are unencumbered.
* Abilities
.. SPIRIT MOUNT
    Conjure mount and lance at will.
    Mounted charge is fucking insane.
    Disappears when not mounted.
.. COMMANDER:
    As an action:
     a) Give an ally an extra action.
     b) Give many allies extra moves.
    Passive:
     Nearby allies have an extra move.
.. SPIRIT ARMORY:
    Summon blade and shield. Uses no item slots. Is badass.


=== Paragon
* Better (than a champion) at casting spells
* Only light armor?
* Faster/better spellcasting.
* Need not have book readied.
* Automatically get more books.
* Abilities
.. TOME KEEPER
   Storage dimension where many books can be kept
   Automatically get more books.
   Able to keep more than {focus} spell alive at the same time.
.. DESTROYER:
   Has all the `Terror of ____` abilities.
   Can free cast certain spells against X at any time without any books.
   Gains access to the spells mentioned above.
.. SPIRIT COMPANION:
   Humanoid
   Can heal
   Can attack
   Is only active for a limited number of rounds at a time.
   Takes one action to summon.
   Paragon can cast spells through the companion
      *) Companion can __touch__ the target.
      *) Ranged spells can be fired from the companions position.
    Trans Familiar
    Detonate


// }}} ELITE CHAMPIONS

//{{{SPELLS
== Spells

=== Gate (X)
*Level 7+, mage*

* Magical portal opens within {X} meters of you.
* A similar magical portal opens within 10·{X} kilometers of you in a place
  you have been to within the last {X} days.
* The two portals connect the two places like a wormhole, a tunnel of zero
  length.

=== Great Resurrection (X)
*Level 7+, champion*

This spell can revive anyone with the adventurer's blessing who has not yet
been turned undead and whose level is lower than X.

You must first fast for at least a day, and then you cast this spell,
chanting for <<X>> hours, upon which you touch the corpse of the creature
you wish to revive.

You then permanently lose one point from a random stat - this loss cannot be
undone in any way.
The recipient must roll 1d20 for every stat. If they roll __above__ a stat's
score, that stat is reduced by 1. This usually means that the recipients worst
stats get even worse. These losses are permanent and cannot be undone.

This spell requires a diamond worth at least 400·<<X>> gold pieces, which is
consumed by the spell.

[[quote]]
Since this spell takes a permanent toll on the caster, it is difficult to find
a caster who is willing to cast this spell, and if they can be persuaded, it
will most likely be extremely expensive.


//}}}
