= Elite's guide to doom & destruction & stuff

:stylesheet: style.css
:doctype: article
:icons: font
:sectlinks:
:toc:
:toclevels: 1
:toc-placement!:
:experimental:
:stem:
:xrefstyle: basic

:moves: xref:adventurer#moves[moves]

== STUFFFF

Most casters use "helpers" such as summoned familiars.
At least one caster type should also have a "body double" or
a number of "mirror images". Maybe you can cast spells via mirror images.

* Champion
** Paladin: Spirit Mount
** Shaman: Spirit Animal(s) [optional]
** Paragon: Spirit Companion

* Mage:
** Illusionist: Mirror Image(s)
** Elementalist: summon elementals
** Bone Tamer (keep bones in bags (Item Slots), and animate them on demand.
** Apex:  Spirit Parallel: Gives the caster extra (limit) actions

*Warrior
** Battle Dancer:   Spirit Chain Weapon (Meteor Hammer)
                        Constrict
                        Disarm
                        Surprise Strike
                        Ranged Melee Attack
                        Chaotic Strike Strike (decrease TN, but increase critical threshold)
** Fighter:
***     ARTILLERY:  Spirit Arrows and/or bow
                    Exploding spirit arrows
                    Sniper arrow (fly through walls)
***     FORTRESS:   Spirit Armor

** Berserker:   already done, just needs tweaking

//{{{ ELITE WARRIORS
== ELITE WARRIORS

=== Berserker

==== Level 6

===== More Hit Points
Your {hit_point_total} is increased by 12.

===== Better Stats
Increase your __constitution__ and __strength__ by one point each, and increase
one other stat by one point as well.

===== Bonus Hit Points
You gain 3 bonus hit points per unused item slot. Other adventurers only get one.
This hit point bonus increases by one every time you gain a level, such that when
you're level 10, you gain 7 bonus hit points per unused item slot.

===== No Armor
You fight without armor and shields. If you equip any armor pieces or shields, 
you lose the ability to go berserk.

==== Weapon Skills
You are skilled at using light melee weapons, heavy melee weapons, and unarmed
combat.

===== Berserker's Rage
You can choose to go berserk when someone has drawn the blood of one or more of
you or your, causing at least one hit point of damage. This rage lasts as long
as someone attacks or your allies. If an entire combat round passes without you
or your allies being attacked, your rage ends.

Being berserk has the following properties:

* The damage you deal with heavy weapons is doubled.
* You gain 2 extra moves, and that number increases by one every time you 
  gain a level, such that when you are level 10, you have 7 extra moves per
  round.
* You have {advantage} on all  __strength__, __constitution__, and
  __dexterity__ checks.
* You have {disadvantage} on all  __intelligence__, __wisdom__, and
  __charisma__ checks.
* You do not roll on the {death_table} when you reach zero hit points;
  you simply remain alive and kicking. But when you are at zero hit points and
  take damage, you must roll on the {trauma_table}, just like other adventurers
  when they take {damage_at_zero_hp}.
* If you reach zero hit points the damage you deal with heavy weapons is
  tripled instead of doubled.
* If you are at zero hit points when your rage ends you must roll on the
  {death_table} again.
* When your berserker's rage ends, you take __L__d6 damage, where __L__ is your 
  level.
* If your rage ends when you are at zero hit pints, you must roll on the 
  {death_table}.

==== Level 7

===== More Hit Points
Increase your {hit_point_total} by 1d8. Roll with {advantage}.

===== Better Stats

First::
For each of your stats, you roll a d20; if the roll is higher than the stat,
that stat is increased by 1 point.

Then:: 
If your strength is lower than 15, increase it by 1, and if your
constitution is lower than 15, increase it by 1.

===== Bonus Hit Points
You gain now gain 4 bonus hit points per unused item slot. 


==== Level 8

===== More Hit Points
Increase your {hit_point_total} by 1d8. Roll with {advantage}.

===== Better Stats
For each of your stats, you roll a d20; if the roll is higher than the stat,
that stat is increased by 1 point.

===== Bonus Hit Points
You gain now gain 4 bonus hit points per unused item slot. 

==== Level 9


==== Level 10


=== War Dancer
* Only wears light helmet and light, medium, or heavy cuirass.
* Can only use light melee weapons and throwing weapons.
* Gains 3 hp per unused item slot if not wearing any armor or shield.
* Extra {moves}
* Specialization
.. MARTIAL ARTS:
   Multiple attacks.
   High damage chi strikes.
.. CHAIN WEAPONS:
   Can use Meteor Hammer, spiked chain, and similar weapons.
   https://en.wikipedia.org/wiki/Chain_weapon
.. THROWING WEAPONS:
   Only uses throwable melee weapons.
   Always has an extra throwing weapon.
   Can make multiple attacks and throws.


=== Fighter
* Can wear all armor and shields.
* Can use all non-exotic weapons.
* All item slots are unencumbered.
* Skilled in heavy weapons
* Expertise
.. FORTRESS:
   Skilled in heavy armor.
   For each heavy armor piece worn, the armor expert gains __L__ extra hit
   pints. 
   Shield Bash
   Backstabber
.. ARTILLERY:
   Long range. Can spend {moves} to __aim__ to add damage.
   High damage with ranged weapons.
   Ultra Range Shot  shot with extreme range, may damage bow, uses an arrow
   usage point right away, causes X points of damage to the fighter.
.. ZWEIHÄNDER:
   Expert in using heavy weapons.
   Ranged Force Attack: Attack an enemy 2-3 meters away, may damage weapon,
   causes a few points of damage to the fighter.

// ELITE WARRIORS }}}

// {{{ ELITE CHAMPIONS
== ELITE CHAMPIONS

=== Shaman (Champion Specialization)
* Nature Spells.
* Totems instead of spellbooks.
* Only non-metal armor.
* Abilities (choose one, maybe more at later levels).
** SHAPE SHIFTER:
   Shift into animals and elementals.
   Very high damage.
   Very high regeneration.
** SPIRIT ANIMAL. 
   It cannot die, but can be temporarily sent back to the spirit world.
   Competent fighter.
   Completely silent.
   Immune to fear, charm, etc.
   Frenzy (à la detonate)


=== Paladin (Champion Specialization)
* Basically a continuation of champion, but primarily
  strengthening melee ability.
* Heavy Armor
* Shield is a must.
* All item slots are unencumbered.
* Abilities
.. SPIRIT MOUNT
    Conjure mount and lance at will.
    Mounted charge is fucking insane.
    Disappears when not mounted.
.. COMMANDER:
    As an action: 
     a) Give an ally an extra action.
     b) Give many allies extra moves.
    Passive:
     Nearby allies have an extra move.
.. SPIRIT ARMORY:
    Summon blade and shield. Uses no item slots. Is badass.


=== Paragon
* Better (than a champion) at casting spells
* Only light armor?
* Faster/better spellcasting.
* Need not have book readied.
* Automatically get more books.
* Abilities
.. TOME KEEPER
   Storage dimension where many books can be kept 
   Automatically get more books.
   Able to keep more than {focus} spell alive at the same time.
.. DESTROYER:
   Has all the Terror of X abilities.
   Can free cast certain spells against X at any time without any books.
   Gains access to the spells mentioned above.
.. SPIRIT COMPANION:
   Humanoid
   Can heal
   Can attack
   Is only active for a limited number of rounds at a time.
   Takes one action to summon.
   Paragon can cast spells through the companion
      *) Companion can _touch_ the target.
      *) Ranged spells can be fired from the companions position.
    Trans Familiar
    Detonate


// }}} ELITE CHAMPIONS

//{{{SPELLS
== Spells

=== Gate (X)
*Level 7+, mage*

* Magical portal opens within {X} meters of you.
* A similar magical portal opens within 10·{X} kilometers of you in a place
  you have been to within the last {X} days.
* The two portals connect the two places like a wormhole, a tunnel of zero
  length.

=== Great Resurrection (X)
*Level 7+, champion*

This spell can revive anyone with the adventurer's blessing who has not yet
been turned undead and whose level is lower than X.

You must first fast for at least a day, and then you cast this spell,
chanting for <<X>> hours, upon which you touch the corpse of the creature
you wish to revive.

You then permanently lose one point from a random stat - this loss cannot be
undone in any way.
The recipient must roll 1d20 for every stat. If they roll __above__ a stat's
score, that stat is reduced by 1. This usually means that the recipients worst
stats get even worse. These losses are permanent and cannot be undone.

This spell requires a diamond worth at least 400·<<X>> gold pieces, which is
consumed by the spell.

[[quote]]
Since this spell takes a permanent toll on the caster, it is difficult to find
a caster who is willing to cast this spell, and if they can be persuaded, it
will most likely be extremely expensive.


//}}}
