= GM's Guide To Doom & Destruction & Stuff

:stylesheet: style.css
:doctype: article
:icons: font
:sectlinks:
:toc:
:toclevels: 1
:toc-placement!:
:experimental:
:stem:
:xrefstyle: full

// {{{RULES
== RULES

=== Leveling Up
You begin at level 1, and you can gain levels until you reach level 10. You
gain levels by acquiring suitable treasures. In order for a team of adventurers
to gain a level, they must <<lvl_acquire>> a number of <<lvl_suitable>>
<<lvl_treasures>> equal to the typical level of the team's members.

[reftext="treasures"]
[[lvl_treasures]]
*Treasure*: A treasure is a big horde, often situated in one location. It is up
to the GM to decide what is an actual treasure, and what is just general loot.

[reftext="suitable"]
[[lvl_suitable]]
*Suitable*: A __suitable__ treasure is worth at least 100 gold pieces times the
sum of the levels of all the characters in the party.

[reftext="acquire"]
[[lvl_acquire]]
*Acquire*: You have __acquired__ a treasure when it is stored safely at your
base of operations. Recovering a large treasure in a distant dungeon may
require a lot of travel and hauling.

====
* In order to level up, a party of 5 first level characters must acquire a
  single treasure worth __5路1路100=500__ gold pieces.

* In order to level up, a party of 4 PCs at 6th level must acquire six
  treasures in order to advance. Each treasure must be worth at least
  __4路6路100=2,400__ gold pieces.
====

=== Social Encounters.
Like attacks and most other things, the player rolls their die BEFORE
they act out what happens.

Advanced Encounters::
Sometimes social encounters require multiple rolls in order to change an NPCs
attitude several steps.

//}}}


// {{{ CAMPAIGN
== CAMPAIGN 

=== Adventurer Logbook & Logging
You are expected to keep and use an Adventurer's Logbook at all time,
and you are expected to transcribe your book's latest pages into any
town's log you find.

//}}}


// {{{ ITEMS
== ITEMS

=== Weapons

Lethal (X):: You can crit on both a __1__, __2__, ... , __X+1__.
Riposte (X):: If an adjacent foe attacks you, you poke them for X + __LEVEL__ damage.
Heavy (X):: Deal X extra points of damage, requires 12+X strength, takes up one extra item slot.
Brutal (X):: Deal X extra points of damage.

=== Shower in a Bottle
Makes you clean, but for dogs sake, don't drink it. Also, makes you smell
"fresh" (lavender, etc.) so it does not hide your scent.

=== Everdark Gear
These items allow you to see in the dark without using visible light that could
give you away.

==== Everdark Torch
This is a magical torch whose light (called everdark light) can only be seen by
those inside the illuminated who are wearing Everdark Goggles. 

* The light has a radius of 10 meters.
* Darkness spells can blot out the everdark light.
* The torch is a one-handed item that must be readied for it to work; if you
  drop the torch (for instance, if you are knocked out), the everdark light
  goes out.

==== Everdark Beacon??
Like a torch, but with large radius, and can work without being readied.

==== Everdark Goggles
This magical item allows you to see the light from an everdark torch. The
goggles only work if they are inside the illuminated radius of an everdark
torch (10 meters). This means that people cannot see you from far away, even if
they are also wearing everdark goggles. You cannot wear a helmet at the same
time as the goggles.

=== SOS Crystal
Two crystals. If one is crushed, the other starts giving of a bright strobe
light. The distance between the crystals can be many KM.

=== Message Scrolls
Two scrolls. If you write something on one scroll and then burn it, the text
will show up, flashing with light, on the other scroll. Range is many KM.

//}}}
