= Y.A.R.I.S: Heroe's guide to doom & destruction & stuff
//{{{ Front matter
:stylesheet: style.css
:sectlinks:
:toc:
:toclevels: 1
:experimental:
:stem:
//}}}


== HERO CLASSES

=== Cleric

==== Level 3

Hit Points:: Increase by 8
Stats:: Increase your _constitution_ and _wisdom_ by one point each,
and increase one other stat by one point as well.
Recovery Die:: 1d8
Armor skills:: Skilled at using light and medium armor and shields.
Magic:: Aside from using conventional spellbooks to cast _basic_ spells, 
you gain access to <<holy_magic>> that is a more effective and powerful
way to cast _basic_ and _holy_ spells.

.Cleric Damage Rolls
[%header,cols="8,^2,^2"]
|===
| Weapon Type           | Skill level | Damage Roll
//----------------------|-------------|------------
| Light Melee Weapons   | Skilled     | 1d6
| Ranged Weapons        | Skilled     | 1d6
| Unarmed Combat        | Unskilled   | 1d3
| Heavy Melee Weapons   | Unskilled   | 1d10
//----------------------|-------------|------------
|===

[[holy_magic]]
===== Holy Magic


==== Level 4


== SPELLS

=== Detect Undead, Major
*Level 4. Duration: _wisdom_ hours.*

This spell works like Detect Undead, Minor, except that when you detect an
undead creature, you roll a _intelligence_ check, and if it succeeds you
discern whether the creature's level is higher than your own.


=== Trauma (X) ===
*Level 6*
You touch a baddie who must roll on the trauma table: 1d100+_X_.
