= Hero's guide to doom & destruction & stuff

:stylesheet: style.css
:doctype: article
:icons: font
:sectlinks:
:toc:
:toclevels: 1
:toc-placement!:
:experimental:
:stem:
:xrefstyle: basic

When you reach your third level, you can choose a heroic class, which allows
you to obtain more powerful abilities, spells, and gear.

// {{{ CHAMPION
== Champion

[quote,Pontius LeDique]
The champion is pious, steadfast, and dangerous.

The champion is a special kind of hero that specializes in destroying the
undead, casting spells from the front lines, and healing their comrades.

=== Level 3

==== Recovery Die
Your recovery die is 1d8.

==== Hit Points
Your __hit point total__ is increased by 8.

==== Stats
Increase your __constitution__ and __wisdom__ by one point each, and increase
one other stat by one point as well.


==== Weapon Skills

.Champion Damage Rolls
[%header,cols="8,^2,^2"]
|===
| Weapon Type             | Skill level | Damage Roll
//------------------------|-------------|------------
| Light Melee Weapons     | Skilled     | 1d6
| Ranged Weapons          | Skilled     | 1d6
| Unarmed Combat          | Unskilled   | 1d3
| Heavy Melee Weapons     | Unskilled   | 1d10
//------------------------|-------------|------------
|===

==== Armor Skills
You are skilled at using light and medium armor, as well as light and medium
shields.

==== Champion Spellcasting

As a champion, you get an improved magical ability where you can upgrade your
basic spellbooks into __Champion's Spellbooks__.

*Champion's spellbooks* are an upgraded version of basic spellbooks; they have
been imbued with the fire of your spirit, linking them to you so you alone can
use them, and you can cast them much more easily.

*Creating a champion's spellbook* is done by upgrading an existing basic
spellbook. The spell in the source book must not have a higher level than
yours, it takes an hour per spell level, and it requires one __consumption__ of
__magic components__ per spell level. Once upgraded, the book is completely
attuned to you, and only you can use it to cast spells. There are, however,
magical rituals that can convert a champion's spellbook back into a basic
spellbook, and there are also rituals that can attune champion's spellbook to
another champion.

[quote]
Like basic spellbooks, the champion's spellbook is faintly magical, and can be
detected with __Detect Magic__ spells.

*You can cast a spell with a champion's spellbook* by grasping the spellbook
firmly in one hand, holding it up, and __shouting__ an incantation from memory.
Once this is done, you roll a __charisma__ check, and if it succeeds, you cast
the spell.


* You can upgrade a basic spellbook into a champion's spellbook.
* It can only be used by _you_.
* You use it with only one hand, by holding it up and __shouting__ a champion's
  prayer. 
* You do not need to see or read.
* You still have to speak and move.
* It is recharged with __holy components__ instead of __magic components__.

=== Level 4

* Lay on hands
* Burial


=== Level 5

* Turn undead

// CHAMPION }}}

// {{{ MAGE
== MAGE

=== Level 3

* Increase your __hit point total__ by 6.
* Increase your __intelligence__ and __wisdom__ by one point each,
  and increase one other stat by one point as well.
* Your recovery die is 1d6.
* You are skilled at using light armor, but no shields.
* Aside from using conventional spellbooks to cast __basic__ spells, you
  gain access to <<mage_books>> allowing you to store and cast many <<mage>>
  spell that is a more effective and powerful way to cast __basic__ and __holy_
  spells.


=== Level 4

* Increase your __hit point total__ by 6.
* Roll a d20. Increase one of the stats (if any) that are lower than what you
  rolled.
* You may switch your __Adventurer's Special Ability__ if you want.

=== Level 5
* Increase your __hit point total__ by 6.
* Roll a d20. Increase one of the stats (if any) that are lower than what you
  rolled.

// MAGE }}}

// {{{ ROGUE
== ROGUE

[quote,Kars LeDique]
The rogue is stealthy, clever, and dangerous.

=== Level 3

==== Recovery Die
Your recovery die is 1d8.

==== Hit Points
Your __hit point total__ is increased by 8.

==== Stats
Increase your __dexterity__ and __wisdom__ by one point each,
  and increase one other stat by one point as well.

==== Weapon skills
You are skilled at using light weapons, unarmed combat, as well throwing
daggers.

.Rogue Damage Rolls
[%header,cols="8,^2,^2"]
|===
| Weapon Type             | Skill level | Damage Roll
//------------------------|-------------|------------
| Light Melee Weapons     | Skilled     | 1d6
| Throwing Daggers        | Skilled     | 1d6
| Other Ranged Weapons    | Unskilled   | 1d4
| Unarmed Combat          | Unskilled   | 1d4
| Heavy Melee Weapons     | Unskilled   | 1d8
//------------------------|-------------|------------
|===

==== Armor Skills
You are skilled at using light armor, but not shields.


==== Rogue's Ability

//START_SORT //KEY:

//KEY:
Lockpicker::
You have __advantage__ on all checks (including __consumption checks__ when
using lockpicking tools to pick locks.


//KEY:
Tinkerer::
You have __advantage__ on all checks (including __consumption checks__ when
using lockpicking tools to pick locks.


//KEY:
Absent::
You have __advantage__ on all checks related to sneaking, hiding, stealth,
and camouflage.

//KEY:
Backstabber::
If an adjacent baddie moves away from you, you can make a melee attack against
them with a readied melee weapon.

//KEY:
Venom Specialist::
You can make poisonous venom from dead monster parts. It requires a dead
monster, a bonfire or similar, one hour of preparation, one __consumption__ of
<<alchemist_tools>>, and one glass bottle to create a dose of venom that can
coat the business end of a slashing or piercing weapon.

Once a weapon has been coated, the first attack you make with it has
__advantage__ on its damage.

=== Level 4

* Increase your __hit point total__ by 6.
* Roll a d20. Increase one of the stats (if any) that are lower than what you
  rolled.
* You may switch your __Adventurer's Special Ability__ if you want.

=== Level 5
* Increase your __hit point total__ by 8.
* Roll a d20. Increase one of the stats (if any) that are lower than what you
  rolled.


// ROGUE }}}

// {{{ WARRIOR
== WARRIOR

=== Level 3

==== Recovery Die
Your recovery die is 1d10.

==== Hit Points
Your __hit point total__ is increased by 10.

==== Stats
Increase your __constitution__ and __strength__ by one point each, and increase
one other stat by one point as well.


==== Weapon Skills

.Warrior Damage Rolls
[%header,cols="8,^2,^2"]
|===
| Weapon Type             | Skill level | Damage Roll
//------------------------|-------------|------------
| Light Melee Weapons     | Skilled     | 1d8
| Ranged Weapons          | Skilled     | 1d6
| Unarmed Combat          | Unskilled   | 1d4
| Heavy Melee Weapons     | Skilled     | 1d12
//------------------------|-------------|------------
|===

==== Armor Skills
You are skilled at using light and medium armor, as well as light and medium
shields.

==== Bonus Damage
When you strike with a weapon you're skilled with, you add your __level__ to
the damage roll.

==== Warrior Special Ability
Chose one of the abilities below. You may switch this ability every time you
gain a level.

Shield Fighter::
If you failed an attack check with a light melee weapon, and your are wearing a
shield, you are allowed to make an attack with your shield. In your hands, a
shield is the same as a light weapon.

[quote]
If you roll a __20__ on your shield attack, your shield becomes __broken__,
which means you lose one __move__.

Critter::
If you roll a __1__ on an attack check with a weapon you're skilled at using,
you roll your damage with __advantage__, and then you make a second attack with
the same weapon against a foe of your choice. If this extra attack hits, you
also roll that damage with __advantage__. You can keep making these bonus
attacks as long as you keep rolling __1__s.

Tank::
You are skilled at using heavy armor.

Hauler::
Your number of total number of item slots and your  __unencumbered__ item slots
is increased by 3.

Basher::
If you have landed a successful hit with a blunt weapon on a baddie, you can
push them one meter away from you.

[quote]
A basher`'s push can cause a baddie to fall off a cliff or into a pit trap, or
it can ensure that the pushed baddie must use at least one __move__ to get back
into melee range with you.

Sniper::
Your ranged damage is increased to 1d10, you can attack baddies up to
__wisdom__ meters away with a __normal__ check, and up to 2路__wisdom__ meters
away with __difficult__ checks.

Pugilist::
You are skilled at unarmed combat, your unarmed damage is 1d8, and you are allowed
to add the warrior's Bonus Damage.

Backstabber::
If an adjacent baddie moves away from you, you can make a melee attack against
them with a readied melee weapon that you are skilled at using.

// Barbarians only have unencumbered item slots. Because they are badass.

=== Level 4

* Increase your __hit point total__ by 10.
* Roll a d20. Increase one of the stats (if any) that are lower than what you
  rolled.
* You may switch your __Adventurer's Special Ability__ if you want.

=== Level 5

* Increase your __hit point total__ by 10.
* Roll a d20. Increase one of the stats (if any) that are lower than what you
  rolled.

// WARRIOR }}}

// {{{ HERO GEAR
== HERO GEAR

// }}}

// {{{ HERO SPELLS
== HERO SPELLS

//START_SORT //KEY:

//KEY:
=== Detect Undead, Major
*<<holy>>, Level 4. Duration: __wisdom__ hours.*

You can feel when one or more undead creatures are within __wisdom__ meters of
you. You can detect undead creatures through most walls, but not it cannot
penetrate more than one meter of rock or one centimeter of lead.

If the undead creature's level is lower than <<X>>, you are able to ascertain
its direction, otherwise you only know that the creature is present, not where
it might be.


//KEY:
=== Trauma (X)
*Level 6*
You touch a baddie who must roll on the __trauma table_: 1d100+<<X>>.


//KEY:
=== Money Talks (X)
*<<basic>>, Level 5+*

You chant for <<X>> minutes and then you touch a pair of gilded clipboards
worth at least 100路<<X>> gold pieces each. The clipboards become enchanted so
when a piece of paper is placed on top of each board, anything written on
either paper also shows up on its counterpart on the other clipboard.

This only works if the two plates are within 100路<<X>> kilometers of each
other.

The enchantment lasts 100路<<X>> days, but you can cast this spell on the
clipboards again later, as long as they are both undamaged and close enough to
touch.

Destroying or severely damaging either clipboard breaks the spell.


// SPELLS }}}

// {{{ DICTIONARY
== DICTIONARY

//START_SORT //KEY:

//KEY:
[reftext="holy"]
[[holy]]
*holy*: A type of spell that can be cast by <<_champion,champions>>.

//KEY:
[reftext="x"]
[[X]]
*X*: The level of the spell. See xref:adventurer#X[X] in the adventurer's
guide.

//END_SORT
// }}}
