= Hero's guide to doom & destruction & stuff

:stylesheet: style.css
:doctype: article
:icons: font
:sectlinks:
:toc:
:toclevels: 1
:toc-placement!:
:experimental:
:stem:
:xrefstyle: basic

When you reach your third level, you can choose a heroic class, which allows
you to obtain more powerful abilities, spells, and gear.


// {{{ CHAMPION
== Champion

[quote,Pontius LeDique]
The champion is pious, steadfast, and dangerous.

The champion is a special kind of hero that specializes in destroying the
undead, casting spells from the front lines, and healing their comrades.

=== Level 3

==== Recovery Die
Your __recovery die__ is 1d8.

==== More Hit Points
Your __hit point total__ is increased by 8.

==== Better Stats
Increase your __constitution__ and __charisma__ by one point each, and increase
one other stat by one point as well.

==== Weapon Skills

.Champion Damage Rolls
[%header,cols="8,^2,^2"]
|===
| Weapon Type             | Skill level   | Damage Roll
//------------------------|---------------|------------
| Light Melee Weapons     | __skilled__   | 1d6
| Ranged Weapons          | __skilled__   | 1d6
| Unarmed Combat          | __unskilled__ | 1d3
| Heavy Melee Weapons     | __unskilled__ | 1d10
//------------------------|---------------|------------
|===

==== Armor Skills
You are __skilled__ at using light and medium armor, as well as light and
medium shields.

==== Champion Spellcasting

You can use __champion's spellbooks__ to cast spells directly from the front
lines without even opening the books.

*Champion's spellbooks* can contain both __basic__ and __champion__ spells,
they can only be used by the champion they are attuned to, and they can be used
without being opened.

*Spellcasting requirements:*

* You must have the __champion's spellbook__ with the given spell inscribed
  in it.
* The spell's level must not be higher than yours.
* The book must be attuned to you.
* The book must have at least one __usage point__.
* You must be holding the book up high in one hand.
* You must be able to speak, and move one arm, hands, and fingers.
* You must not be __exhausted__, __on fire__, or __restrained__.

*Spellcasting procedure:*: Make a __charisma__ check:

.. If you rolled a __1__, the spell takes effect, and the book does not lose
   any __usage points__.
.. If your check was a success, the spell spell takes effect, and the book
   loses one __usage point__.
.. If your check failed, the spell fizzles, but no __usage points__ are lost.
.. If you rolled a __20__, the spell fizzles, and the book loses all its
   __usage points__.

*Champion's Ritual Casting* works exactly like __basic ritual casting__, except
you're using a __champion's spellbook__, and can cast <<champion>> spells,
provided they have the __ritual__ property.

*Upgrade Basic Spellbooks* takes one hour per spell level and requires one
__consumption__ of __magic components__ per spell level. The spell in the
source book must not have a higher level than you. Once upgraded, the spellbook
is attuned to you, and only you can use it.

[quote]
Like basic spellbooks, the champion's spellbook is faintly magical, and can be
detected with __Detect Magic__ spells.

*Reattuning a champion's spellbook* from one champion to you requires an hour
per spell level, one consumption of __magic components__ per spell level, and
can only be done if your level is at least as high as the spell's level.

==== New Spellbook
You acquire a __champion's spellbook__; it is already attuned to you, and it
has two __usage points__. The spell in the book is one that you do not already
posses, it has the <<champion>> property, and its level is no higher than
yours.

==== Peaceful Rest
You acquire a __champion's spellbook__ with the spell <<_peaceful_rest>> on it.
It has 1 __usage point__, and when you carry it, it does not take up any __item
slots__. 

=== Level 4

==== More Hit Points
Increase your __hit point total__ by 1d8. Roll with __advantage__.

==== Better Stats
For each of your stats, you roll a d20; if the roll is higher than the stat,
that stat is increased by 1 point.

==== Adventurer's Ability
You may change your __Adventurer's Ability__ if you want.

==== New Spellbook
You acquire a __champion's spellbook__; it is already attuned to you, and it
has two __usage points__. The spell in the book is one that you do not already
posses, it has the <<champion>> property, and its level is no higher than
yours.

==== Champion's Special Ability
You gain one of the abilities below.

//START_SORT //KEY:

//KEY:
*Bane of Demons*: When you attack an demonic creature (such as the various
dungeon guards and dungeon masters), your __attach check__ and __damage roll__
is made with __advantage__.


//KEY:
*Bane of Mechanoids*: When you attack an mechanoid creature (such as golems and
iron guards), your __attach check__ and __damage roll__ is made with
__advantage__.


//KEY:
*Bane of Orcs*: When you attack an orcish creature (orc, troll, bugbear, etc.),
your __attach__ __check__ and __damage__ __roll__ is made with __advantage__.


//KEY:
*Bane of Undeads*: When you attack an undead creature, your __attach__
__check__ and __damage__ __roll__ is made with __advantage__.


//KEY:
*Healer*: You obtain a champion's spellbook with the spell __Heal 4__ on it.

* It starts as __Heal{nbsp}4__, and its level increases by one whenever you
  gain a level.
* It does not take up any __item slots__.
* It has 1 __usage point__, and gains one extra __usage point__ when
  you reach level 5, 7, and 9.
* If you lose or change this ability, you keep the book as it is, but it begins
  taking up one __item slot__, and it does not gain any more spell levels.

//END_SORT


=== Level 5

==== More Hit Points
Increase your __hit point total__ by 1d8. Roll with __advantage__.

==== Better Stats
For each of your stats, you roll a d20; if the roll is higher than the stat,
that stat is increased by 1 point.

==== New Spellbook
You acquire a __champion's spellbook__; it is already attuned to you, and it
has two __usage points__. The spell in the book is one that you do not already
posses, it has the <<champion>> property, and its level is no higher than
yours.

=== Level 6: Graduation
It is time for you to move on. You’re no longer just an hero, you’re an Elite.
See how this affects you in the
xref:elites#[Elite’s Guide to doom & destruction & stuff].

// CHAMPION }}}


// {{{ MAGE
== MAGE

[quote,Feya LeDique]
The mage is clever, mystical, and dangerous.

The mage is a scholar that solely specializes in spellcasting.

=== Level 3

==== Recovery Die
Your __recovery die__ is 1d6.

==== More Hit Points
Your __hit point total__ is increased by 6.

==== Better Stats
Increase your __intelligence__ and __wisdom__ by one point each, and increase
one other stat by one point as well.

==== Weapon Skills
You are only __skilled__ at using daggers and quarterstaffs, both of which are
__light melee weapons__, even though a quarterstaff is two-handed. You are not
skilled at throwing daggers.

.Rogue Damage Rolls
[%header,cols="8,^2,^2"]
|===
| Weapon Type             | Skill level   | Damage Roll
//------------------------|---------------|------------
| Light Melee Weapons     | __unskilled__ | 1d4
| Ranged Weapons          | __unskilled__ | 1d4
| Unarmed Combat          | __unskilled__ | 1d4
| Heavy Melee Weapons     | __unskilled__ | 1d8
| Quarterstaffs           | __skilled__   | 1d8
| Daggers                 | __skilled__   | 1d6
//------------------------|---------------|------------
|===

==== Armor Skills
You are __skilled__ at using light armor, but not shields.

==== Mage Spellcasting
You can use __mage's spellbooks__ to cast spells much more efficiently.

*Mage's spellbooks* can contain both __basic__ and __mage__ spells, they can
only be used by mages, and they are more efficient than __basic spellbooks__.

*Spellcasting requirements*:

* You must have a __mage's spellbook__ with the given spell inscribed in it.
* The spell's level must not be higher than yours.
* The spellbook must have at least one __usage point__.
* You must be holding the spellbook open in both hands.
* You must be able to see, speak, read, and move your arms, hands, and fingers.
* You must not be __exhausted__, __on fire__, __prone__, or __restrained__.


*Spellcasting procedure*: You cast the spell and the book loses one __usage__
__point__. Unlike __basic spellcasting__, there is no __intelligence check__
involved.


*Recharging*: You can recharge a __mage's spellbook__ if the spell's level
isn't higher than yours. Your start by spending one __consumption__ of magic
components, and then you perform a 15-minute ritual. When it is complete,
you have recharged the spellbook back to full capacity.


*Mage's Ritual Casting* has the same requirements as basic ritual casting, but
the procedure is the following: you spend 10 minutes chanting and reading from
the spellbook, then you spend one __consumption__ of __magic_components__, and
then the spell takes

*Upgrade Basic Spellbooks* takes one hour per spell level and requires one
__consumption__ of __magic components__ per spell level. The spell in the
source book must not have a higher level than you.


==== New Spellbook
You acquire a __mage's spellbook__ with two __usage points__. The spell in the
book has the <<mage>> property, and its level is no higher than yours.


=== Level 4

==== More Hit Points
Increase your __hit point total__ by 1d6. Roll with __advantage__.

==== Better Stats
For each of your stats, you roll a d20; if the roll is higher than the stat,
that stat is increased by 1 point.

==== New Spellbook
You acquire a __mage's spellbook__ with two __usage points__. The spell in the
book has the <<mage>> property, and its level is no higher than yours.

==== Adventurer's Ability
You may change your __Adventurer's Ability__ if you want.

==== Mage's Ability
You gain one of the abilities below:
//START_SORT //KEY:


//KEY:
*Blood Mage*: When casting a spell, you can chose to sacrifice some of your
life force to improve its effect. You take 5 points of damage, but all checks
you make in conjunction with casting your spells have __advantage__. This
includes damage rolls and any checks some spells require you to make, such as
the __charisma__ check you must make when casting the __Snooze (X)__ spell.


//KEY:
*Collector*: When you become a __collector__,  and every time you as a
__collector__ gain a new level, you acquire a new __mage's spellbook__ with a
new spell on it; the spell is of your level or less and it has two __usage
points__.


//KEY:
*Efficient Caster*: Whenever you cast a spell you make a roll. If you roll
below or equal your __level__ your book does not lose a __usage point__ and you
gain a new action right away, allowing you to, among other things, cast the same
spell again.


//KEY:
*Librarian*: At any point in time, three of your __mage's spellbooks__ do not
take up any __item slots__. 


//KEY:
*Savant*: You can attempt to cast any one of your spells directly from memory a
without using its spellbook. This means you don't have to have the book in your
hands, and you need not be able to see and read. To do so you first lose a
number of __hit points__ equal to the spell's level, and then you must succeed
a __difficult__ __intelligence__ check; if that check succeeded you cast the
spell successfully. When casting a spell from memory you don't need to have its
book on you, but you must have had it on you sometime within __L__ days, where
__L__ is your level.


//KEY:
*Scholar*: You acquire a special __mage's spellbook__ with a number of __usage
points__ equal to your level and it contains a spell of your level or less. As
long as you are a __scholar__ the book does not take up any __item slots__, its
__usage points__ continues to match your level, and you can to change the spell
every time you gain a new level. When changing the spell in the book you must
have some knowledge of the new spell; for instance, you can change Heal 4 into
Heal 5, but you cannot change your spell into Money Talks 5 if you haven't used
a book with that spell or one of its multilevel variants before.


//END_SORT


=== Level 5

==== More Hit Points
Increase your __hit point total__ by 1d6. Roll with __advantage__.

==== Better Stats
For each of your stats, you roll a d20; if the roll is higher than the stat,
that stat is increased by 1 point.

==== New Spellbook
You acquire a __mage's spellbook__ with two __usage points__. The spell in the
book has the <<mage>> property, and its level is no higher than yours.

=== Level 6: Graduation
It is time for you to move on. You’re no longer just an hero, you’re an Elite.
See how this affects you in the
xref:elites#[Elite’s Guide to doom & destruction & stuff].

// MAGE }}}


// {{{ ROGUE
== ROGUE

[quote,Kars LeDique]
The rogue is stealthy, clever, and dangerous.

=== Level 3

==== Recovery Die
Your recovery die is 1d8.

==== More Hit Points
Your __hit point total__ is increased by 8.

==== Better Stats
Increase your __dexterity__ and __wisdom__ by one point each, and increase one
other stat by one point as well.

==== Weapon skills
You are __skilled__ at using light weapons, unarmed combat, as well throwing
daggers.

.Rogue Damage Rolls
[%header,cols="8,^2,^2"]
|===
| Weapon Type             | Skill level   | Damage Roll
//------------------------|---------------|------------
| Light Melee Weapons     | __skilled__   | 1d6
| Throwing Daggers        | __skilled__   | 1d6
| Other Ranged Weapons    | __unskilled__ | 1d4
| Unarmed Combat          | __unskilled__ | 1d4
| Heavy Melee Weapons     | __unskilled__ | 1d8
//------------------------|---------------|------------
|===

==== Armor Skills
You are __skilled__ at using light armor, but not shields.

==== Adventurer's Ability
You may change your __Adventurer's Ability__ if you want.

==== Rogue's Ability
You gain one of the abilities below.

//START_SORT //KEY:

//KEY:
*Absent*: You have __advantage__ on all checks related to sneaking, hiding,
stealth, and camouflage. All attempts to track you are __difficult__; even
animals have trouble finding your scent, and you cannot be marked by someone
with the __tracker__ ability.

If you attack someone who is completely unaware of your presence you have
__advantage__ on both your attack check and your damage roll, provided you are
__skilled__ with the weapon you are using.


//KEY:
*Acrobat*: By spending an __action__ you can jump up to __dexterity__ meters
horizontally, or up to __L__ meters vertically, where __L__ is your level.
You cannot do this if you're __encumbered__, __exhausted__, or similarly
affected. Your acrobatic skills also enables you to move at full speed in
difficult terrain.


//KEY:
*Dagger Master*: You do not need to use any __moves__ to ready a dagger as long
as you have one on you, and you are not __encumbered__, __exhausted__,
__restrained__ or similar. You can spend three __moves__ (instead of an
__action__) to make a ranged attack with a dagger, as long as the target is
within __L__ meters, where __L__ is your level.


//KEY:
*Lockpicker*: You have __advantage__ on all checks (including __consumption__
__checks__) when using your lockpicking tools, and one of the sets of
lockpicking tools you carry do not take up an __item slot__.
If you do not have a set of lockpicking tools already, you receive one when
you pick this ability.

Using your lockpicking tools you are able to pseudo-jam a lock such that it can
only be opened by you, or by a lockpicker who is at least two levels higher
than you. It cannot even be opened with the key. It takes 10 minutes and one
__consumption__ of lockpicking tools to do pseudo-jam a lock.


//KEY:
*Pacifier*: If you don't have a kosh when you chose this ability you receive
one. You are __skilled__ at using the __kosh__, and when you use it, the die
you use to determine if the baddie goes unconscious is 1d10, and if the
baddie's level is lower than yours, you roll your d10 with __advantage__. If
you combine this ability with the __shady__ adventurer's ability, the you roll
1d12 with __advantage__ to test for unconsciousness regardless of the level of
the baddie.


//KEY:
*Tinkerer*: You have __advantage__ on all checks (including __consumption__
__checks__) when using your tinkering tools, and one of the sets of tinkering
tools you carry do not take up an __item slot__.

You can repair weapons and armor pieces just as if you had the __armorer__ 
adventurer's ability.

Your attack checks and damage rolls against mechanoid creatures are made with
__advantage__. You also completely ignore any and all damage resistances these
creatures have.

You have __advantage__ on all checks involved in detecting traps, certain
hidden doors, and other hidden mechanical installations.

You can make and install simple traps. It takes one hour and one __usage__
__point__ of tinkering tools to create a simple trap that deals 1d6+__L__
points of damage, where __L__ is your level. Such traps can be installed on
doors, in alcoves, in chests, and similar places. The trap only deals damage
once, and if someone knows where it is, they can generally avoid (but not
disarm) it. In general, traps created so fast stop working after a number of
weeks equal to your level.


//KEY:
*Tracker*: You magically mark a baddie within __charisma__ meters. You can only
have one creature marked at a time. You have __advantage__ on all ranged attack
checks you make against a marked baddie.

As long as the baddie is within __charisma__ kilometers of you, you are able to
sense in which direction it is, and if you make a successful __adversarial__
__wisdom__ check and you are within __charisma__ meters of the "path" of the
baddie, you are able to track the actual path of the target for the next 10
minutes.

[quote]
Some creatures have special abilities that allow them to avoid or remove the
tracker's mark.


//KEY:
*Venom Specialist*: You can make poisonous venom from dead monster parts. It
requires a recently deceased monster, a bonfire or similar, one hour of
preparation, one __consumption__ of <<_alchemist_tools>>, and one steel bottle
to create a dose of venom that can coat the business end of a slashing or
piercing weapon, including arrowheads.

It takes one __action__ to apply a readied bottle of venom to a readied weapon,
and it lasts for up to one week one the weapon.

Once you have coated your weapon, you add __L__d6 to the damage of the next
successful attack with that weapon, where __L__ is your level.

[quote]
Some baddies, such as undeads and mechanoids, are immune to poison.

//END_SORT


=== Level 4

==== More Hit Points
Increase your __hit point total__ by 1d8. Roll with __advantage__.

==== Better Stats
For each of your stats, you roll a d20; if the roll is higher than the stat,
that stat is increased by 1 point.

=== Level 5

==== More Hit Points
Increase your __hit point total__ by 1d8. Roll with __advantage__.

==== Better Stats
For each of your stats, you roll a d20; if the roll is higher than the stat,
that stat is increased by 1 point.


=== Level 6: Graduation
It is time for you to move on. You’re no longer just an hero, you’re an Elite.
See how this affects you in the
xref:elites#[Elite’s Guide to doom & destruction & stuff].

// ROGUE }}}


// {{{ WARRIOR
== WARRIOR

=== Level 3

==== Recovery Die
Your recovery die is 1d10.

==== More Hit Points
Your __hit point total__ is increased by 10.

==== Better Stats
Increase your __constitution__ and __strength__ by one point each, and increase
one other stat by one point as well.

==== Weapon Skills

.Warrior Damage Rolls
[%header,cols="8,^2,^2"]
|===
| Weapon Type             | Skill level   | Damage Roll
//------------------------|---------------|------------
| Light Melee Weapons     | __skilled__   | 1d8
| Ranged Weapons          | __skilled__   | 1d6
| Unarmed Combat          | __unskilled__ | 1d4
| Heavy Melee Weapons     | __skilled__   | 1d12
//------------------------|---------------|------------
|===

==== Armor Skills
You are __skilled__ at using light and medium armor, as well as light and
medium shields.

==== Bonus Damage
When you strike with a weapon you're __skilled__ with, you add your __level__
to the damage roll.

==== Adventurer's Ability
You may change your __Adventurer's Ability__ if you want.

==== Warrior Special Ability
Chose one of the abilities below. You may switch this ability every time you
gain a level.

//START_SORT //KEY:


//KEY:
*Basher*: If you have landed a successful hit with a non-broken blunt heavy
melee weapon on a baddie no larger than you, you may push them 2 meters away
from you. If your attack was a __critical hit__ you can push a creature of any
size and weight. Pushing a baddie past or away from an ally with the
__backstabber__ ability will trigger their bonus attack, but if __you__
yourself have that ability, you do not get a bonus attack. 
When you reach level 6 you can push a baddie 3 meters away from you, when you
reach level 8 the distance is 4 meters, and a 10th level character with this
ability can push an enemy up to 5 meters.


//KEY:
*Critter*: you only have to roll lower than or equal to your level in order to
get a __critical __hit.


//KEY:
*Hauler*: At any point in time, the three heaviest items you carry do not take
up any __item slots__.


//KEY:
*Hunter*: Your ranged damage is increased to 1d10, you can attack baddies up to
__wisdom__ meters away with a __normal__ check, and up to 2·__wisdom__ meters
away with __difficult__ checks.


//KEY:
*Pugilist*: You are __skilled__ at unarmed combat, your unarmed damage is 1d10,
you are allowed to add the warrior's <<Bonus Damage>>, and you are able to
fully damage creatures with resistance to non-magical attacks. In addition to
these benefits, you are able to use a light or medium shield along with your
unarmed combat, but your damage is only 1d8 if doing so.


//KEY:
*Shield Fighter*: If you failed an attack check with a light melee weapon, and
your are wearing an non-broken shield, you are allowed to make an attack with
your shield. In your hands, a shield is the same as a light melee weapon. 

[quote]
If you roll a __20__ on your shield attack, your shield becomes __broken__,
which means you lose one __move__.


//KEY:
*Tank*: You are __skilled__ at using heavy armor, and one of the armor pieces
you carry does not take up any __item slots__.

//END_SORT

=== Level 4

==== More Hit Points
Increase your __hit point total__ by 1d10. Roll with __advantage__.

==== Better Stats
For each of your stats, you roll a d20; if the roll is higher than the stat,
that stat is increased by 1 point.

=== Level 5

==== More Hit Points
Increase your __hit point total__ by 1d10. Roll with __advantage__.

==== Better Stats
For each of your stats, you roll a d20; if the roll is higher than the stat,
that stat is increased by 1 point.


=== Level 6: Graduation
It is time for you to move on. You’re no longer just an hero, you’re an Elite.
See how this affects you in the
xref:elites#[Elite’s Guide to doom & destruction & stuff].

// WARRIOR }}}


// {{{ HERO GEAR
== HERO GEAR

=== Alchemist tools
Blaaaaaahahaaahah


// }}}


// {{{ HERO SPELLS
== HERO SPELLS

//START_SORT ===


=== Detect Undead, Major
*<<champion>>, Level 4. Duration: __wisdom__ hours.*

You can feel when one or more undead creatures are within __wisdom__ meters of
you. You can detect undead creatures through most walls, but not it cannot
penetrate more than one meter of rock or one centimeter of lead.

If the undead creature's level is lower than <<X>>, you are able to ascertain
its direction, otherwise you only know that the creature is present, not where
it might be.


=== Money Talks (X)
*<<basic>>, Level 5+*

You chant for <<X>> minutes and then you touch a pair of gilded clipboards
worth at least 100·<<X>> gold pieces each. The clipboards become enchanted so
when a piece of paper is placed on top of each board, anything written on
either paper also shows up on its counterpart on the other clipboard.

This only works if the two plates are within 100·<<X>> kilometers of each
other.

The enchantment lasts 100·<<X>> days, but you can cast this spell on the
clipboards again later, as long as they are both undamaged and close enough to
touch.

Destroying or severely damaging either clipboard breaks the spell.


=== Peaceful Rest
*<<champion>>, Level 3. __ritual__*

You touch a inanimate corpse that has died within the last __charisma__ hours.
That corpse will not rise as an undead unless a sufficiently powerful
necromancer uses dark magic on it.

=== Trauma (X)
*Level 6*
You touch a baddie who must roll on the __trauma table_: 1d100+<<X>>.

//END_SORT

// SPELLS }}}


// {{{ DICTIONARY
== DICTIONARY

//START_SORT //KEY:


//KEY:
[reftext="basic"]
[[basic]]
*Basic (spell property)*: Spells with this property are basic, and have no
specific class requirements.


//KEY:
[reftext="champion"]
[[champion]]
*Champion (spell property)*: Spells with this property can only be cast by
<<_champion,champions>>.


//KEY:
[reftext="mage"]
[[mage]]
*Mage (spell property)*: Spells with this property can only be cast by
<<_mage,mages>>.


//KEY:
[reftext="x"]
[[X]]
*X (spell property)*: The level of the spell. See xref:adventurer#X[X] in the
adventurer's guide.


//END_SORT
// }}}
