= Hero's guide to doom & destruction & stuff

:stylesheet: style.css
:doctype: article
:icons: font
:sectlinks:
:toc:
:toclevels: 1
:toc-placement!:
:experimental:
:stem:
:xrefstyle: basic

When you reach your third level, you can choose a heroic class, which allows
you to obtain more powerful abilities, spells, and gear.


// {{{ CHAMPION
== Champion

[quote,Pontius LeDique]
The champion is pious, steadfast, and dangerous.

The champion is a special kind of hero that specializes in destroying the
undead, casting spells from the front lines, and healing their comrades.

=== Level 3

==== Recovery Die
Your __recovery die__ is 1d8.

==== More Hit Points
Your __hit point total__ is increased by 8.

==== Better Stats
Increase your __constitution__ and __charisma__ by one point each, and increase
one other stat by one point as well.

==== Weapon Skills

.Champion Damage Rolls
[%header,cols="8,^2,^2"]
|===
| Weapon Type             | Skill level   | Damage Roll
//------------------------|---------------|------------
| Light Melee Weapons     | __skilled__   | 1d6
| Ranged Weapons          | __skilled__   | 1d6
| Unarmed Combat          | __unskilled__ | 1d3
| Heavy Melee Weapons     | __unskilled__ | 1d10
//------------------------|---------------|------------
|===

==== Armor Skills
You are __skilled__ at using light and medium armor, as well as light and
medium shields.

==== Champion Spellcasting

You can use __champion's spellbooks__ to cast spells directly from the front
lines without even opening the books.

*Champion's spellbooks* can contain both __basic__ and __champion__ spells,
they can only be used by the champion they are attuned to, and they can be used
without being opened.

*Spellcasting requirements:*

* You must have the __champion's spellbook__ with the given spell inscribed
  in it.
* The spell's level must not be higher than yours.
* The book must be attuned to you.
* The book must have at least one __usage point__.
* You must be holding the book up high in one hand.
* You must be able to speak, and move one arm, hands, and fingers.
* You must not be __exhausted__, __on fire__, or __restrained__.

*Spellcasting procedure:*: Make a __charisma__ check:

.. If you rolled a __1__, the spell takes effect, and the book does not lose
   any __usage points__.
.. If your check was a success, the spell spell takes effect, and the book
   loses one __usage point__.
.. If your check failed, the spell fizzles, but no __usage points__ are lost.
.. If you rolled a __20__, the spell fizzles, and the book loses all its
   __usage points__.

*Champion's Ritual Casting* works exactly like __basic ritual casting__, except
you're using a __champion's spellbook__, and can cast <<champion>> spells,
provided they have the __ritual__ property.

*Upgrade Basic Spellbooks* takes one hour per spell level and requires one
__consumption__ of __magic components__ per spell level. The spell in the
source book must not have a higher level than you. Once upgraded, the spellbook
is attuned to you, and only you can use it.

[quote]
Like basic spellbooks, the champion's spellbook is faintly magical, and can be
detected with __Detect Magic__ spells.

*Reattuning a champion's spellbook* from one champion to you requires an hour
per spell level, one consumption of __magic components__ per spell level, and
can only be done if your level is at least as high as the spell's level.

==== New Spellbook
You acquire a __champion's spellbook__; it is already attuned to you, and it
has two __usage points__. The spell in the book is one that you do not already
posses, it has the <<champion>> property, and its level is no higher than
yours.

==== Peaceful Rest
You acquire a __champion's spellbook__ with the spell <<_peaceful_rest>> on it.
It has 1 __usage point__, and when you carry it, it does not take up any __item
slots__. 

=== Level 4

==== More Hit Points
Increase your __hit point total__ by 1d8. Roll with __advantage__.

==== Better Stats
For each of your stats, you roll a d20; if the roll is higher than the stat,
that stat is increased by 1 point.

==== Adventurer's Ability
You may change your __Adventurer's Ability__ if you want.

==== New Spellbook
You acquire a __champion's spellbook__; it is already attuned to you, and it
has two __usage points__. The spell in the book is one that you do not already
posses, it has the <<champion>> property, and its level is no higher than
yours.

==== Champion's Special Ability
You gain one of the abilities below.

//START_SORT //KEY:

//KEY:
*Bane of Demons*: When you attack an demonic creature (such as the various
dungeon guards and dungeon masters), your __attach check__ and __damage roll__
is made with __advantage__.


//KEY:
*Bane of Mechanoids*: When you attack an mechanoid creature (such as golems and
iron guards), your __attach check__ and __damage roll__ is made with
__advantage__.


//KEY:
*Bane of Orcs*: When you attack an orcish creature (orc, troll, bugbear, etc.),
your __attach__ __check__ and __damage__ __roll__ is made with __advantage__.


//KEY:
*Bane of Undeads*: When you attack an undead creature, your __attach__
__check__ and __damage__ __roll__ is made with __advantage__.


//KEY:
*Healer*: You obtain a champion's spellbook with the spell __Heal 4__ on it.

* It starts as __Heal{nbsp}4__, and its level increases by one whenever you
  gain a level.
* It does not take up any __item slots__.
* It has 1 __usage point__, and gains one extra __usage point__ when
  you reach level 5, 7, and 9.
* If you lose or change this ability, you keep the book as it is, but it begins
  taking up one __item slot__, and it does not gain any more spell levels.

//END_SORT


=== Level 5

==== More Hit Points
Increase your __hit point total__ by 1d8. Roll with __advantage__.

==== Better Stats
For each of your stats, you roll a d20; if the roll is higher than the stat,
that stat is increased by 1 point.

==== New Spellbook
You acquire a __champion's spellbook__; it is already attuned to you, and it
has two __usage points__. The spell in the book is one that you do not already
posses, it has the <<champion>> property, and its level is no higher than
yours.

=== Level 6: Graduation
It is time for you to move on. You’re no longer just an hero, you’re an Elite.
See how this affects you in the
xref:elites#[Elite’s Guide to doom & destruction & stuff].

// CHAMPION }}}


// {{{ MAGE
== MAGE

[quote,Feya LeDique]
The mage is clever, mystical, and dangerous.

The mage is a scholar that solely specializes in spellcasting.

=== Level 3

==== Recovery Die
Your __recovery die__ is 1d6.

==== More Hit Points
Your __hit point total__ is increased by 6.

==== Better Stats
Increase your __intelligence__ and __wisdom__ by one point each, and increase
one other stat by one point as well.

==== Weapon Skills
You are only __skilled__ at using daggers and quarterstaffs, both of which are
__light melee weapons__, even though a quarterstaff is two-handed. You are not
skilled at throwing daggers.

.Rogue Damage Rolls
[%header,cols="8,^2,^2"]
|===
| Weapon Type             | Skill level   | Damage Roll
//------------------------|---------------|------------
| Light Melee Weapons     | __unskilled__ | 1d4
| Ranged Weapons          | __unskilled__ | 1d4
| Unarmed Combat          | __unskilled__ | 1d4
| Heavy Melee Weapons     | __unskilled__ | 1d8
| Quarterstaffs           | __skilled__   | 1d8
| Daggers                 | __skilled__   | 1d6
//------------------------|---------------|------------
|===

==== Armor Skills
You are __skilled__ at using light armor, but not shields.

==== Mage Spellcasting
You can use __mage's spellbooks__ to cast spells much more efficiently.

*Mage's spellbooks* can contain both __basic__ and __mage__ spells, they can
only be used by mages, and they are more efficient than __basic spellbooks__.

*Spellcasting requirements*:

* You must have a __mage's spellbook__ with the given spell inscribed in it.
* The spell's level must not be higher than yours.
* The spellbook must have at least one __usage point__.
* You must be holding the spellbook open in both hands.
* You must be able to see, speak, read, and move your arms, hands, and fingers.
* You must not be __exhausted__, __on fire__, __prone__, or __restrained__.


*Spellcasting procedure*: You cast the spell and the book loses one __usage__
__point__. Unlike __basic spellcasting__, there is no __intelligence check__
involved.


*Recharging*: You can recharge a __mage's spellbook__ if the spell's level
isn't higher than yours. Your start by spending one __consumption__ of magic
components, and then you perform a 15-minute ritual. When it is complete,
you have recharged the spellbook back to full capacity.


*Mage's Ritual Casting* has the same requirements as basic ritual casting, but
the procedure is the following: you spend 10 minutes chanting and reading from
the spellbook, then you spend one __consumption__ of __magic_components__, and
then the spell takes

==== New Spellbook
You acquire a __mage's spellbook__ with two __usage points__. The spell in the
book has the <<mage>> property, and its level is no higher than yours.

=== Level 4

==== More Hit Points
Increase your __hit point total__ by 1d6. Roll with __advantage__.

==== Better Stats
For each of your stats, you roll a d20; if the roll is higher than the stat,
that stat is increased by 1 point.

==== New Spellbook
You acquire a __mage's spellbook__ with two __usage points__. The spell in the
book has the <<mage>> property, and its level is no higher than yours.

==== Adventurer's Ability
You may change your __Adventurer's Ability__ if you want.

==== Mage's Ability
You gain one of the abilities below:
//START_SORT //KEY:


//KEY:
*Blood Mage*: When casting a spell, you can chose to sacrifice a bit of your
life force to improve its effect. You take 5 points of damage, but all
checks you make in conjunction with casting your spells have __advantage__.
This includes damage rolls and the various checks some spells require you to
make, such as the __charisma__ checks you must make when casting the __Snooze
(X)__ spell.


//KEY:
*Librarian*: ????

//KEY:
*Librarian*: ????

//KEY:
*Librarian*: ????

//KEY:
*Librarian*: Three of the __mage's spellbooks__ you're carrying do not take up
any __item slots__.


//END_SORT


=== Level 5

==== More Hit Points
Increase your __hit point total__ by 1d6. Roll with __advantage__.

==== Better Stats
For each of your stats, you roll a d20; if the roll is higher than the stat,
that stat is increased by 1 point.

==== New Spellbook
You acquire a __mage's spellbook__ with two __usage points__. The spell in the
book has the <<mage>> property, and its level is no higher than yours.

=== Level 6: Graduation
It is time for you to move on. You’re no longer just an hero, you’re an Elite.
See how this affects you in the
xref:elites#[Elite’s Guide to doom & destruction & stuff].

// MAGE }}}


// {{{ ROGUE
== ROGUE

[quote,Kars LeDique]
The rogue is stealthy, clever, and dangerous.

=== Level 3

==== Recovery Die
Your recovery die is 1d8.

==== More Hit Points
Your __hit point total__ is increased by 8.

==== Better Stats
Increase your __dexterity__ and __wisdom__ by one point each, and increase one
other stat by one point as well.

==== Weapon skills
You are __skilled__ at using light weapons, unarmed combat, as well throwing
daggers.

.Rogue Damage Rolls
[%header,cols="8,^2,^2"]
|===
| Weapon Type             | Skill level   | Damage Roll
//------------------------|---------------|------------
| Light Melee Weapons     | __skilled__   | 1d6
| Throwing Daggers        | __skilled__   | 1d6
| Other Ranged Weapons    | __unskilled__ | 1d4
| Unarmed Combat          | __unskilled__ | 1d4
| Heavy Melee Weapons     | __unskilled__ | 1d8
//------------------------|---------------|------------
|===

==== Armor Skills
You are __skilled__ at using light armor, but not shields.

==== Adventurer's Ability
You may change your __Adventurer's Ability__ if you want.

==== Rogue's Ability
You gain one of the abilities below.

//START_SORT //KEY:

//KEY:
*Absent*: You have __advantage__ on all checks related to sneaking, hiding,
stealth, and camouflage. All attempts to track you are __difficult__; even
animals have trouble finding your scent. If you attack someone who is
completely unaware of your presence, you have __advantage__ on both your attack
check and your damage roll, as long as you are __skilled__ with the weapon you
are using.


//KEY:
*Acrobat*: By spending an __action__ you can jump up to __dexterity__ meters
horizontally, or up to __L__ meters vertically, where __L__ is your level.
You cannot do this if you're __encumbered__, __exhausted__, or similarly
affected.


//KEY:
*Dagger Master*: You do not need to use any __moves__ to ready a dagger, as
long as you have one on you, and you are not __encumbered__, __exhausted__, or
similar. You can spend three __moves__ to make a ranged attack with a dagger,
as long as the target is within __L__ meters, where __L__ is your level.


//KEY:
*Lockpicker*: You have __advantage__ on all checks (including __consumption__
__checks__) when using your lockpicking tools, and one of the sets of
lockpicking tools you carry do not take up an __item slot__.


//KEY:
*Subduer*: You are __skilled__ at using the __kosh__, and when you use it, the
die you use to determine if the baddie goes unconscious is 1d10, and if the
baddie's level is lower than yours, you roll your d10 with __advantage__. When
you chose this ability, and you already have the "`__shady__`" adventurer's
ability, you may switch that ability for something else if you want.


//KEY:
*Tinkerer*: You have __advantage__ on all checks (including __consumption
checks__) when using your tinkering tools, and one of the sets of tinkering
tools you carry do not take up an __item slot__.


//KEY:
*Tracker*: You mark a baddie within __charisma__ meters. As long as the baddie
is within __charisma__ kilometers of you, you are able to sense in which
direction it is, and if you make a successful __adversarial__ __wisdom__ check
and you are within __charisma__ meters of the "path" of the baddie, you are
able to track the actual path of the target.


//KEY:
*Venom Specialist*: You can make poisonous venom from dead monster parts. It
requires a dead monster, a bonfire or similar, one hour of preparation, one
__consumption__ of <<_alchemist_tools>>, and one steel bottle to create a dose
of venom that can coat the business end of a slashing or piercing weapon.

It takes one __action__ to apply a readied bottle of venom to a readied weapon,
and it lasts for up to one week one the weapon.

Once a weapon has been coated, you add __L__d6 to the damage of the next
successful attack with that weapon, where __L__ is the level of the person who
created the poison.

[quote]
Some baddies, such as undeads and mechanoids, are immune to poison.

//END_SORT


=== Level 4

==== More Hit Points
Increase your __hit point total__ by 1d8. Roll with __advantage__.

==== Better Stats
For each of your stats, you roll a d20; if the roll is higher than the stat,
that stat is increased by 1 point.

=== Level 5

==== More Hit Points
Increase your __hit point total__ by 1d8. Roll with __advantage__.

==== Better Stats
For each of your stats, you roll a d20; if the roll is higher than the stat,
that stat is increased by 1 point.


=== Level 6: Graduation
It is time for you to move on. You’re no longer just an hero, you’re an Elite.
See how this affects you in the
xref:elites#[Elite’s Guide to doom & destruction & stuff].

// ROGUE }}}


// {{{ WARRIOR
== WARRIOR

=== Level 3

==== Recovery Die
Your recovery die is 1d10.

==== More Hit Points
Your __hit point total__ is increased by 10.

==== Better Stats
Increase your __constitution__ and __strength__ by one point each, and increase
one other stat by one point as well.

==== Weapon Skills

.Warrior Damage Rolls
[%header,cols="8,^2,^2"]
|===
| Weapon Type             | Skill level   | Damage Roll
//------------------------|---------------|------------
| Light Melee Weapons     | __skilled__   | 1d8
| Ranged Weapons          | __skilled__   | 1d6
| Unarmed Combat          | __unskilled__ | 1d4
| Heavy Melee Weapons     | __skilled__   | 1d12
//------------------------|---------------|------------
|===

==== Armor Skills
You are __skilled__ at using light and medium armor, as well as light and
medium shields.

==== Bonus Damage
When you strike with a weapon you're __skilled__ with, you add your __level__
to the damage roll.

==== Adventurer's Ability
You may change your __Adventurer's Ability__ if you want.

==== Warrior Special Ability
Chose one of the abilities below. You may switch this ability every time you
gain a level.

//START_SORT //KEY:


//KEY:
*Basher*: If you have landed a successful hit with a blunt weapon on a baddie,
you may push them __L__ meter away from you, where __L__ is your level.

[quote]
A basher`'s push can cause a baddie to fall off a cliff or into a pit trap, or
it can ensure that the pushed baddie must use at least __moves__ to get back
into melee range with you. If you push a baddie away from one of your allies
who has the __backstabber__ ability.


//KEY:
*Critter*: Normally you will have to roll a __1__ to make a __critical hit__.
But you only have to roll lower than or equal to your level.

[quote]
If you're level 4, on average, every 6th attack check would be a critical hit,
which gives you an extra action.


//KEY:
*Hauler*: Three of your items does not take up any __item slots__.


//KEY:
*Pugilist*: You are __skilled__ at unarmed combat, your unarmed damage is 1d10,
you are allowed to add the warrior's Bonus Damage, and you are able to fully
damage creatures with resistance to non-magical attacks. In addition to these
benefits, you are able to use a light or medium shield along with your unarmed
combat, but your damage is only 1d8 if doing so.


//KEY:
*Shield Fighter*: If you failed an attack check with a light melee weapon, and
your are wearing a shield, you are allowed to make an attack with your shield.
In your hands, a shield is the same as a light melee weapon.

[quote]
If you roll a __20__ on your shield attack, your shield becomes __broken__,
which means you lose one __move__.


//KEY:
*Sniper*: Your ranged damage is increased to 1d10, you can attack baddies up to
__wisdom__ meters away with a __normal__ check, and up to 2·__wisdom__ meters
away with __difficult__ checks.


//KEY:
*Tank*: You are __skilled__ at using heavy armor, and one of the armor pieces
you carry does not take up any __item slots__.

//END_SORT

=== Level 4

==== More Hit Points
Increase your __hit point total__ by 1d10. Roll with __advantage__.

==== Better Stats
For each of your stats, you roll a d20; if the roll is higher than the stat,
that stat is increased by 1 point.

=== Level 5

==== More Hit Points
Increase your __hit point total__ by 1d10. Roll with __advantage__.

==== Better Stats
For each of your stats, you roll a d20; if the roll is higher than the stat,
that stat is increased by 1 point.


=== Level 6: Graduation
It is time for you to move on. You’re no longer just an hero, you’re an Elite.
See how this affects you in the
xref:elites#[Elite’s Guide to doom & destruction & stuff].

// WARRIOR }}}


// {{{ HERO GEAR
== HERO GEAR

=== Alchemist tools
Blaaaaaahahaaahah

// }}}


// {{{ HERO SPELLS
== HERO SPELLS

//START_SORT ===


=== Detect Undead, Major
*<<champion>>, Level 4. Duration: __wisdom__ hours.*

You can feel when one or more undead creatures are within __wisdom__ meters of
you. You can detect undead creatures through most walls, but not it cannot
penetrate more than one meter of rock or one centimeter of lead.

If the undead creature's level is lower than <<X>>, you are able to ascertain
its direction, otherwise you only know that the creature is present, not where
it might be.


=== Money Talks (X)
*<<basic>>, Level 5+*

You chant for <<X>> minutes and then you touch a pair of gilded clipboards
worth at least 100·<<X>> gold pieces each. The clipboards become enchanted so
when a piece of paper is placed on top of each board, anything written on
either paper also shows up on its counterpart on the other clipboard.

This only works if the two plates are within 100·<<X>> kilometers of each
other.

The enchantment lasts 100·<<X>> days, but you can cast this spell on the
clipboards again later, as long as they are both undamaged and close enough to
touch.

Destroying or severely damaging either clipboard breaks the spell.


=== Peaceful Rest
*<<champion>>, Level 3. __ritual__*

You touch a inanimate corpse that has died within the last __charisma__ hours.
That corpse will not rise as an undead unless a sufficiently powerful
necromancer uses dark magic on it.

=== Trauma (X)
*Level 6*
You touch a baddie who must roll on the __trauma table_: 1d100+<<X>>.

//END_SORT

// SPELLS }}}


// {{{ DICTIONARY
== DICTIONARY

//START_SORT //KEY:


//KEY:
[reftext="champion"]
[[champion]]
*Champion (spell property)*: Spells with this property can only be cast by
<<_champion,champions>>.


//KEY:
[reftext="mage"]
[[mage]]
*Mage (spell property)*: Spells with this property can only be cast by
<<_mage,mages>>.


//KEY:
[reftext="x"]
[[X]]
*X (spell property)*: The level of the spell. See xref:adventurer#X[X] in the
adventurer's guide.


//KEY:
[reftext="basic"]
[[basic]]
*Basic (spell property)*: Spells with this property are basic, and have no
specific class requirements.


//END_SORT
// }}}
