= Hero's guide to doom & destruction & stuff

:stylesheet: style.css
:doctype: article
:icons: font
:sectlinks:
:toc:
:toclevels: 1
:toc-placement!:
:experimental:
:stem:
:xrefstyle: basic

When you reach your third level, you can choose a heroic class, which allows
you to obtain more powerful abilities, spells, and gear.

// {{{ CHAMPION
== Champion

[quote, Pontius LeDik]
The champion is pious, steadfast, and dangerous.


The champion is a special kind of spellcaster that specializes in casting
spells from the front line.

=== Level 3

==== Recovery Die
Your recovery die is 1d8.

==== Hit Points
Your _hit point total_ is increased by 8.

==== Stats
Increase your _constitution_ and _wisdom_ by one point each, and increase one
other stat by one point as well.


==== Weapon Skills

.Champion Damage Rolls
[%header,cols="8,^2,^2"]
|===
| Weapon Type             | Skill level | Damage Roll
//------------------------|-------------|------------
| Light Melee Weapons     | Skilled     | 1d6
| Ranged Weapons          | Skilled     | 1d6
| Unarmed Combat          | Unskilled   | 1d3
| Heavy Melee Weapons     | Unskilled   | 1d10
//------------------------|-------------|------------
|===

==== Armor Skills
You are skilled at using light and medium armor, as well as light and medium
shields.

==== Holy Tablets
Aside from using conventional spellbooks to cast _basic_ spells, you gain the
ability to create and use holy tablets. These tablets are made of wood or slate,
they take up a single _item slot_, they can contain a single spell, and they
have a single _usage point_.

Create Holy Tablet::
If you have a spellbook with a <<holy>> spell on it, you can use that book to
create a holy tablet. You need a tablet-like piece of wood or 



=== Level 4

* Lay on hands
* Burial


=== Level 5

* Turn undead

// CHAMPION }}}

// {{{ MAGE
== MAGE

=== Level 3

* Increase your _hit point total_ by 6.
* Increase your _intelligence_ and _wisdom_ by one point each,
  and increase one other stat by one point as well.
* Your recovery die is 1d6.
* You are skilled at using light armor, but no shields.
* Aside from using conventional spellbooks to cast _basic_ spells, you
  gain access to <<mage_books>> allowing you to store and cast many <<mage>>
  spell that is a more effective and powerful way to cast _basic_ and _holy_
  spells.


=== Level 4

* Increase your _hit point total_ by 6.
* Roll a d20. Increase one of the stats (if any) that are lower than what you
  rolled.
* You may switch your _Adventurer's Special Ability_ if you want.

=== Level 5
* Increase your _hit point total_ by 6.
* Roll a d20. Increase one of the stats (if any) that are lower than what you
  rolled.

// MAGE }}}

// {{{ ROGUE 
== ROGUE

=== Level 3

* Increase your _hit point total_ by 8.
* Increase your _dexterity_ and _wisdom_ by one point each,
  and increase one other stat by one point as well.
* Your recovery die is 1d8.
* You are skilled at using light armor, but not shields.
* You are skilled at using light weapons, unarmed combat, as well 
  throwing daggers.
* You gain a Rogue's Ability.

==== Rogue's Ability

Lockpicker:: 
You have <<advantage>> on all checks (including _consumption checks_ when
using lockpicking tools to pick locks.


Tinkerer::
You have advantage on all checks (including _consumption checks_ when
using lockpicking tools to pick locks.


Absent::
You have _advantage_ on all checks related to sneaking, hiding, stealth,
and camouflage.


=== Level 4

* Increase your _hit point total_ by 8.
* Roll a d20. Increase one of the stats (if any) that are lower than what you
  rolled.
* You may switch your _Adventurer's Special Ability_ if you want.

=== Level 5
* Increase your _hit point total_ by 8.
* Roll a d20. Increase one of the stats (if any) that are lower than what you
  rolled.


// ROGUE }}}

// {{{ WARRIOR
== WARRIOR

=== Level 3

* Increase your _hit point total_ by 10.
* Increase your _constitution_ and _strength_ by one point each,
  and increase one other stat by one point as well.
* Your recovery die is 1d10.
* You are skilled at using light and medium armor, as well as light and medium
  shields.

.Warrior Damage Rolls
[%header,cols="8,^2,^2"]
|===
| Weapon Type             | Skill level | Damage Roll
//------------------------|-------------|------------
| Light Melee Weapons     | Skilled     | 1d8
| Ranged Weapons          | Skilled     | 1d6
| Unarmed Combat          | Unskilled   | 1d3
| Heavy Melee Weapons     | Skilled     | 1d12
//------------------------|-------------|------------
|===


==== Warrior Special Ability
Chose one:

Shield Fighter::
If you attack a baddie, but failed your attack check, you
are allowed to make an attack with your shield. It behaves
like a light weapon. 

[quote]
If you roll a _20_ on your shield slice, your shield becomes
_broken_, which means you lose one _move_.

Critter::
If you roll a _1_ on your attack check, you roll your damage with
_advantage_, and then you make a second attack with the same weapon
against a foe of your choice. If your bonus attack hits, you also
roll that damage with _advantage_.

Tank::
You are skilled at using heavy armor.

Hauler::
Your number of total number of item slots and your  _unencumbered_ item slots
is increased by 3.

Basher::
If you have landed a successful hit with a blunt weapon on a baddie, you can
push them one meter away from you. 

[quote]
A basher`'s push can cause a baddie to fall off a cliff or into a pit trap. It
also ensure that the pushed baddie must use at least one _move_ to get back
into melee range with you.

Sniper::
Your ranged damage is increased to 1d10, you can attack baddies up to
_wisdom_ meters away with a _normal_ check, and
up to 2路__wisdom__ meters away with _difficult_ checks.

Pugilist::
You are skilled at unarmed combat, and your unarmed damage is 1d8.

Backstabber::
If an adjacent baddie moves away from you, you can make a melee attack
against them.

// Barbarians only have unencumbered item slots. Because they are badass.

=== Level 4

* Increase your _hit point total_ by 10.
* Roll a d20. Increase one of the stats (if any) that are lower than what you
  rolled.
* You may switch your _Adventurer's Special Ability_ if you want.

=== Level 5

* Increase your _hit point total_ by 10.
* Roll a d20. Increase one of the stats (if any) that are lower than what you
  rolled.

// WARRIOR }}}

// {{{ HERO GEAR
== HERO GEAR

// }}}

// {{{ HERO SPELLS
== HERO SPELLS

//START_SORT //KEY:

//KEY:
=== Detect Undead, Major
*<<holy>>, Level 4. Duration: _wisdom_ hours.*

You can feel when one or more undead creatures are within _wisdom_ meters of
you. You can detect undead creatures through most walls, but not it cannot
penetrate more than one meter of rock or one centimeter of lead.

If the undead creature's level is lower than <<X>>, you are able to ascertain
its direction, otherwise you only know that the creature is present, not where
it might be.


//KEY:
=== Trauma (X)
*Level 6*
You touch a baddie who must roll on the _trauma table_: 1d100+<<X>>.


//KEY:
=== Money Talks (X)
*<<basic>>, Level 5+*

You chant for <<X>> minutes and then you touch a pair of gilded clipboards
worth at least 100路<<X>> gold pieces each. The clipboards become enchanted so
when a piece of paper is placed on top of each board, anything written on
either paper also shows up on its counterpart on the other clipboard.

This only works if the two plates are within 100路<<X>> kilometers of each
other.

The enchantment lasts 100路<<X>> days, but you can cast this spell on the
clipboards again later, as long as they are both undamaged and close enough to
touch.

Destroying or severely damaging either clipboard breaks the spell.

//KEY:
=== Create Holy Tablet (X)
*<<holy>>, level 3+*

You chant for <<X>> minutes and then you touch a spellbook within range. The
spell fizzles if the level of the spell in the spell in the spellbook is higher
than <<X>> or if the spellbook has less that 1 _usage point_ left.

After touching the spellbook you touch a piece of paper, parchment, or papyrus.
The paper turns into a stone tablet with holy writing on it. It is magical, can
be detected with a _Detect Magic_ spell, and weighs one <<item_slot>>.

// SPELLS }}}

// {{{ DICTIONARY
== DICTIONARY

//START_SORT //KEY:

//KEY:
[reftext="_holy_"]
[[holy]]
*holy*: A type of spell that can be cast by <<_champion,champions>>.

[reftext="_x_"]
[[X]]
*X*: The level of the spell.

[reftext="item slot"]
[[item_slot]]
*Item slot*: See xref:adventurer#item_slots[item slots] in the adventurer's guide.
//END_SORT
// }}}
