= Hero's Guide to Doom & Destruction & Stuff
// {{{ VARIABLES
:stylesheet: style.css
:doctype: book
:icons: font
:sectlinks:
:toc:
:toclevels: 1
:toc-placement!:
:experimental:
:stem:
:xrefstyle: full


:A: xref:adventure#
:E: xref:elite#
:X: xref:adventurer#X[x]
:elites: xref:elites#[Elite's Guide to Doom & Destruction & Stuff]
:one: xref:adventurer#nat1[One]
:twenty: xref:adventurer#nat20[Twenty]
:action: xref:adventurer#_actions[action]
:advantage: xref:adventurer#advantage[advantage]
:adventurers_ability: xref:adventurer#_adventurers_special_ability[adventurer's ability]
:adversarial: xref:adventurer#adversarial[adversarial]
:armorer: xref:adventurer#armorer[armorer]
:backstabber: xref:adventurer#backstabber[backstabber]
:basic: xref:adventurer#basic[basic]
:consumption: xref:adventurer#consumption_check[consumption]
:consumption_check: xref:adventurer#consumption_check[consumption check]
:consumption_checks: xref:adventurer#consumption_check[consumption checks]
:critical_hit: xref:adventurer#_critical_hits[critical hit]
:difficult: xref:adventurer#difficult[difficult]
:encumbered: xref:adventurer#encumbered[encumbered]
:exhausted: xref:adventurer#exhausted[exhausted]
:heal4: xref:adventurer#_heal_x[Heal 4]
:heal5: xref:adventurer#_heal_x[Heal 5]
:hit_point_total: xref:adventurer#hit_point_total[hit point total]
:item_slot: xref:adventurer#item_slots[item slot]
:item_slots: xref:adventurer#item_slots[item slots]
:kosh: xref:adventurer#kosh[kosh]
:move: xref:adventurer#moves[move]
:moves: xref:adventurer#moves[moves]
:nat1: xref:adventurer#nat1[1]
:nat20: xref:adventurer#nat20[20]
:on_fire: xref:adventurer#on_fire[on_fire]
:prone: xref:adventurer#prone[prone]
:restrained: xref:adventurer#restrained[restrained]
:ritual: xref:adventurer#ritual[ritual]
:shady: xref:adventurer#shady[shady]
:trauma_table: xref:adventurer#trauma_table[trauma table]
:usage_point: xref:adventurer#usage_points[usage point]
:usage_points: xref:adventurer#usage_points[usage points]
// }}}

When you reach your third level, you can choose a heroic class, which allows
you to obtain powerful abilities, spells, and gear.

The game now starts to transition from survival into heroic fantasy; your
character gains powers and special abilities, you can carry more resources,
traversing the wilderness is less dangerous, and you begin establishing good
reputations, bases of operations, and strong allies.

toc::[]

// {{{ CHAMPION
== CHAMPION

[quote,Pontius LeDique]
The champion is pious, steadfast, and dangerous.

The champion is a special kind of hero that specializes in destroying the
undead, casting spells from the front lines, and healing their comrades.

=== Level 3

==== More Hit Points
Your {hit_point_total} is increased by 8.

==== Specialization
You may switch two stats.

==== Better Stats
Roll a d20 with {advantage}; if the roll is higher than your __wisdom__
increase that it by one point. Do the same for __charisma__.

==== Weapon Skills

[%unbreakable]
--
.Champion's Attack and Damage
[%header,cols="6,^2,^2,^2"]
|===
| Weapon                | Stat        | Skill       | Damage 
//----------------------|-------------|-------------|-------------
| Light Melee Weapons   | _strength_  | Skilled     | 1d8
| Ranged Weapons        | _wisdom_    | Unskilled   | 1d6
| Heavy Melee Weapons   | _strength_  | Unskilled   | 2d12
| Unarmed Combat        | _dexterity_ | Unskilled   | 1d4
//----------------------|-------------|-------------|-------------
|===
--

==== Armor Skills
You are __skilled__ at using light and medium armor, as well as light and
medium shields.

==== Champion Spellcasting

You can use __champion's spellbooks__ to cast spells directly from the front
lines without even opening the books.

*Champion's spellbooks* can contain both {basic} and __champion__ spells,
they can only be used by the champion they are attuned to, and they can be used
without being opened.

*Spellcasting requirements:*

* You must have the __champion's spellbook__ with the given spell inscribed
  in it.
* The spell's level must not be higher than yours.
* The book must be attuned to you.
* The book must have at least one {usage_point}.
* You must be holding the book up high in one hand.
* You must be able to speak, and move one arm, hands, and fingers.
* You must not be {exhausted}, {on_fire}, or {restrained}.

*Spellcasting procedure:*: Make a __charisma__ check and refer to the table
below.

[cols="^2s,10"]
|===
//----------|----------------------------------------------------
| {One}     | The spell takes effect.
| Success   | The spell takes effect, and the book loses a {usage_point}.
| Failure   | The spell fizzles.
| {Twenty}  | The spell fizzles, and the book loses all its {usage_points}.
//----------|----------------------------------------------------
|===

*Champion's Ritual Casting* works exactly like __basic ritual casting__, except
you're using a __champion's spellbook__, and can cast <<champion>> spells,
provided they have the {ritual} property.

*Recharging*: You can recharge a <<champions_spellbook>> if it is attuned to
you; you start by spending one {consumption} of magic components, then you
perform a 15-minute ritual, and then you roll a __charisma__ check. If
the check was successful, you have recharged the book to full capacity.

*Upgrade Basic Spellbooks* takes one hour per spell level and requires one
{consumption} of __magic components__ per spell level. The spell in the
source book must not have a higher level than you. Once upgraded, the spellbook
is attuned to you, and only you can use it.

:detect_magic: xref:adventurer#_detect_magic[Detect Magic]
[quote]
Like basic spellbooks, the champion's spellbook is faintly magical, and can be
detected with {detect_magic} spells.

*Reattuning a champion's spellbook* from one champion to you requires an hour
per spell level, one consumption of __magic components__ per spell level, and
can only be done if your level is at least as high as the spell's level.

==== New Spellbook
You acquire a __champion's spellbook__; it is already attuned to you, and it
has two {usage_points}. The spell in the book is one that you do not already
posses, it has the <<champion>> property, and its level is no higher than
yours.

==== Last Rites
You acquire a __champion's spellbook__ with the spell <<_last_rites>> on it.
It has a number of {usage_points} equal to your level and for you it does not
take up any {item_slots}.

=== Level 4

==== More Hit Points
Increase your {hit_point_total} by 1d8. Roll with {advantage}.

==== Better Stat
Roll a d20 and increase one of the stats that is lower than what you rolled.
Too bad if you didn't roll higher than any stat.

==== Adventurer's Ability
You may change your {adventurers_ability} if you want.

==== New Spellbook
You acquire a __champion's spellbook__; it is already attuned to you, and it
has two {usage_points}. The spell in the book is one that you do not already
posses, it has the <<champion>> property, and its level is no higher than
yours.

==== Champion's Special Ability
You gain one of the abilities below.

//START_SORT //KEY:

//KEY:
*Healer*: You obtain a champion's spellbook with the spell {heal4} on
it.


* It starts as {heal4}, and its level increases by one whenever you
  gain a level.
* It starts with 4 {usage_points}, and it gains one extra point whenever you
  gain a level.
* It does not take up any {item_slots}.
* You do not need to make a spellcasting (__charisma__) check when casting from 
  this book.
* If you lose or change this ability, you keep the book as it is, but it starts
  taking up one {item_slot}, and it does not gain any more spell levels or 
  {usage_points}.

//KEY:
*Terror of Demons*: When you attack an demonic creature (such as the various
dungeon guards and dungeon masters), your __attach check__ and __damage roll__
is made with {advantage}, and when you successfully hit a such a creature it
becomes {demoralized} if its level is lower than yours.


//KEY:
*Terror of Mechanoids*: When you attack an mechanoid creature (such as golems
and iron guards), your __attach check__ and __damage roll__ is made with
{advantage}, and when you successfully hit a such a creature it becomes
{demoralized} if its level is lower than yours.


//KEY:
*Terror of Orcs*: When you attack an orcish creature (orc, troll, bugbear,
etc.), your __attach__ __check__ and __damage__ __roll__ is made with
{advantage}, and when you successfully hit a such a creature it becomes
{demoralized} if its level is lower than yours.


//KEY:
*Terror of Undeads*: When you attack an undead creature, your __attack__
__check__ and __damage__ __roll__ is made with {advantage}, and when you
successfully hit a such a creature it becomes {demoralized} if its level is
lower than yours.


//END_SORT


=== Level 5

==== Better Stat
Roll a d20 and increase one of the stats that is lower than what you rolled.
Too bad if you didn't roll higher than any stat.

==== More Hit Points
Increase your {hit_point_total} by 1d8. Roll with {advantage}.

==== New Spellbook
You acquire a __champion's spellbook__; it is already attuned to you, and it
has two {usage_points}. The spell in the book is one that you do not already
posses, it has the <<champion>> property, and its level is no higher than
yours.

=== Level 6: Graduation
It is time for you to move on. You’re no longer just an hero, you’re an Elite.
See how this affects you in the {elites}.

// CHAMPION }}}


// {{{ MAGE
== MAGE

[quote,Feya LeDique]
The mage is clever, mystical, and dangerous.

The mage is a scholar that solely specializes in spellcasting.

=== Level 3

==== More Hit Points
Your {hit_point_total} is increased by 6.

==== Specialization
You may switch two stats.

==== Better Stats
Roll a d20 with {advantage}; if the roll is higher than your __intelligence__
increase that it by one point. Do the same for __wisdom__.

==== Weapon Skills
You are only __skilled__ at using daggers and quarterstaffs, both of which are
__light melee weapons__, even though a quarterstaff is two-handed. You are not
skilled at throwing daggers.

.Rogue Damage Rolls
[%header,cols="8,^2,^2"]
|===
| Weapon Type             | Stat        | Skill     | Damage
//------------------------|-------------|-----------|----------
| Light Melee Weapons     | _strength_  | Unskilled | 1d4
| Quarterstaffs           | _dexterity_ | Skilled   | 1d8
| Daggers                 | _dexterity_ | Skilled   | 1d6
| Ranged Weapons          | _dexterity_ | Unskilled | 1d4
| Unarmed Combat          | _dexterity_ | Unskilled | 1d4
| Heavy Melee Weapons     | _dexterity_ | Unskilled | 1d8
//------------------------|-------------|-----------|----------
|===

==== Armor Skills
You are __skilled__ at using light armor, but not shields.

==== Mage Spellcasting
You can use <<mages_spellbook,mage's spellbooks>> to cast spells much more
efficiently.

[reftext="mage's spellbook"]
[[mages_spellbook]]
*Mage's spellbooks* can contain both {basic} and <<mage>> spells, they can
only be used by mages, and they are more efficient than __basic spellbooks__.

*Spellcasting requirements*:

* You must have a <<mages_spellbook>> with the given spell inscribed in it.
* The spell's level must not be higher than yours.
* The spellbook must have at least one {usage_point}.
* You must be holding the spellbook open in both hands.
* You must be able to see, speak, read, and move your arms, hands, and fingers.
* You must not be {exhausted}, {on_fire}, {prone}, or {restrained}.


*Spellcasting procedure*: You cast the spell and the book loses one
{usage_point}. Unlike __basic spellcasting__, there is no __intelligence
check__ involved.


*Recharging*: You can recharge a <<mages_spellbook>> if the spell's level
isn't higher than yours. Your start by spending one {consumption} of magic
components, and then you perform a 15-minute ritual. When it is complete,
you have recharged the spellbook back to full capacity.


*Mage's Ritual Casting* has the same requirements as basic ritual casting, but
the procedure is the following: you spend 10 minutes chanting and reading from
the spellbook, then you spend one {consumption} of __magic_components__, and
then the spell takes

*Upgrade Basic Spellbooks* takes one hour per spell level and requires one
{consumption} of __magic components__ per spell level. The spell in the
source book must not have a higher level than you.


==== New Spellbook
You acquire a <<mages_spellbook>> with two {usage_points}. The spell in the
book has the <<mage>> property, and its level is no higher than yours.


=== Level 4

==== More Hit Points
Increase your {hit_point_total} by 1d6. Roll with {advantage}.

==== Better Stat
Roll a d20 and increase one of the stats that is lower than what you rolled.
Too bad if you didn't roll higher than any stat.

==== New Spellbook
You acquire a <<mages_spellbook>> with two {usage_points}. The spell in the
book has the <<mage>> property, and its level is no higher than yours.

==== Adventurer's Ability
You may change your {adventurers_ability} if you want.

==== Mage's Ability
You gain one of the abilities below:
//START_SORT //KEY:


//KEY:
*Blood Mage*: When casting a spell, you can chose to sacrifice some of your
life force to improve its effect. You take 5 points of damage, but all checks
you make in conjunction with casting your spells have {advantage}. This
includes damage rolls and any checks some spells require you to make, such as
the __charisma__ check you must make when casting the __Snooze (X)__ spell.


//KEY:
*Collector*: When you become a __collector__,  and every time you gain a level
as a __collector__ you acquire a new <<mages_spellbook>> with a spell on it;
the spell is of your level or less and it has two {usage_points}.


//KEY:
*Efficient Caster*: Whenever you cast a spell you make a roll. If you roll
below your __level__ it is as if you had rolled a {nat1}.


//KEY:
*Librarian*: At any point in time, three of your <<mages_spellbook,mage's
spellbooks>> do not take up any {item_slots}, and you can recharge __mage's__
and __basic__ spellbooks without using __magic components__.


//KEY:
*Savant*: You can attempt to cast any one of your spells directly from memory a
without using its spellbook; You do not even need to have the book on you, but
you must have had it on you sometime in the past __level__ days.

To cast the spell you start by gathering magical energy, causing you to lose a
number of __hit points__ equal to the spell's level, and then you make a
{difficult} __intelligence__ check; if that check succeeds you cast the spell
successfully.


//KEY:
*Scholar*: You acquire a special __mage's spellbook__ with a number of
{usage_points} points__ equal to your level and it contains a spell of your
level or less. As long as you are a __scholar__ the book does not take up any
{item_slots}, its {usage_points} continues to match your level, and you can to
change the spell every time you gain a new level. When changing the spell in
the book you must have some knowledge of the new spell; for instance, you can
change {heal4} into {heal5}, but you cannot change your spell into
<<_money_talks_x,Money Talks 5>> if you haven't used a book with that spell or
one of its multilevel variants before.


//END_SORT


=== Level 5

==== Better Stat
Roll a d20 and increase one of the stats that is lower than what you rolled.
Too bad if you didn't roll higher than any stat.

==== More Hit Points
Increase your {hit_point_total} by 1d6. Roll with {advantage}.

==== New Spellbook
You acquire a <<mages_spellbook>> with two {usage_points}. The spell in the
book has the <<mage>> property, and its level is no higher than yours.


=== Level 6: Graduation
It is time for you to move on. You’re no longer just an hero, you’re an Elite.
See how this affects you in the {elites}.

// MAGE }}}


// {{{ ROGUE
== ROGUE

[quote,Kars LeDique]
The rogue is stealthy, clever, and dangerous.

=== Level 3

==== More Hit Points
Your {hit_point_total} is increased by 8.

==== Specialization
You may switch two stats.

==== Better Stats
Roll a d20 with {advantage}; if the roll is higher than your __wisdom__
increase that it by one point. Do the same for __charisma__.

==== Weapon skills
You are __skilled__ at using light weapons, unarmed combat, as well throwing
daggers.

[%unbreakable]
--
[[adventurer_damage_rolls_table]]
.Rogues's Attack and Damage
[%header,cols="6,^2,^2,^2"]
|===
| Weapon                | Stat        | Skill       | Damage 
//----------------------|-------------|-------------|-------------
| Light Melee Weapons   | _strength_  | Skilled     | 1d6
| Throwing Daggers      | _wisdom_    | Skilled     | 1d6
| Other Ranged Weapons  | _wisdom_    | Unskilled   | 1d4
| Heavy Melee Weapons   | _strength_  | Unskilled   | 1d10
| Unarmed Combat        | _dexterity_ | Unskilled   | 1d4
//----------------------|-------------|-------------|-------------
|===
--

==== Better Stat
Roll a d20 and increase one of the stats that is lower than what you rolled.
Too bad if you didn't roll higher than any stat.

==== Armor Skills
You are __skilled__ at using light armor, but not shields.

==== Adventurer's Ability
You may change your {adventurers_ability} if you want.

==== Rogue's Ability
You gain one of the abilities below.

//START_SORT //KEY:


//KEY:
*Absent*: You have {advantage} on all checks related to sneaking, hiding,
stealth, and camouflage. All attempts to track you are {difficult}; even
animals have trouble finding your scent, and you cannot be marked by someone
with the __tracker__ ability.

If you attack someone who is completely unaware of your presence you have
{advantage} on both your attack check and your damage roll, provided you are
__skilled__ with the weapon you are using.


//KEY:
*Acrobat*: By spending an {action} you can jump up to __dexterity__ meters
horizontally, or up to __level__ meters vertically. You cannot do this if
you're {encumbered}, {exhausted}, or similarly affected. Your acrobatic skills
also enables you to move at full speed in difficult terrain.


//KEY:
*Dagger Master*: You do not need to use any {moves} to ready a dagger as long
as you have one on you, and you are not {encumbered}, {exhausted},
{restrained} or similar. You can spend three {moves} (instead of an
{action}) to make a ranged attack with a dagger, as long as the target is
within __level__ meters of you.


//KEY:
*Lockpicker*: You have {advantage} on all checks (including
{consumption_checks}) when using your lockpicking tools. One of the sets of
lockpicking tools you carry do not take up an {item_slot}. If you do not have a
set of lockpicking tools already, you receive one when you pick this ability.

Using your lockpicking tools you are able to pseudo-jam a lock such that it can
only be opened by you, or by a lockpicker who is at least two levels higher
than you. It cannot even be opened with the key. It takes 10 minutes and one
{consumption} of lockpicking tools to do pseudo-jam a lock.


//KEY:
*Pacifier*: If you don't have a {kosh} when you chose this ability you receive
one. You are __skilled__ at using the {kosh}, and when you use it, the die
you use to determine if the baddie goes unconscious is 1d10, and if the
baddie's level is lower than yours, you roll your d10 with {advantage}. If
you combine this ability with the {shady} {adventurers_ability}, then you
always roll 1d10 with {advantage} to test for unconsciousness regardless of the
level of the baddie.


//KEY:
*Tinkerer*: You have {advantage} on all checks (including {consumption_checks})
when using your tinkering tools, and one of the sets of tinkering tools you
carry do not take up an {item_slot}.

You can repair weapons and armor pieces just as if you had the {armorer}
{adventurers_ability}.

Your attack checks and damage rolls against automatons and mechanoid creatures
are made with {advantage}. You also completely ignore any damage resistances
such creatures might have.

You have {advantage} on all checks involved in detecting traps, certain
hidden doors, and other hidden mechanical installations.

You can make and install simple traps. It takes one hour and one {usage_point}
of tinkering tools to create a simple trap that deals 1d6+__L__ points of
damage, where __L__ is your level. Such traps can be installed on doors, in
alcoves, in chests, and similar places. The trap only deals damage once, and if
someone knows where it is, they can generally avoid (but not disarm) it. In
general, traps created so fast stop working after a number of weeks equal to
your level.


//KEY:
*Tracker*: as an {action} you magically mark a baddie within __charisma__
meters. You can only have one creature marked at a time. You have {advantage}
on all ranged attack checks and damage rolls against that baddie.

As long as the baddie is within __charisma__ kilometers of you, you are able to
sense in which direction it is, and if you make a successful {adversarial}
__wisdom__ check and you are within __charisma__ meters of the "path" of the
baddie, you are able to track the actual path of the target for the next 10
minutes.

[quote]
Some creatures have special abilities that allow them to avoid or remove the
tracker's mark.


//KEY:
*Venom Specialist*: You can make venom from dead monster parts. It requires a
recently deceased monster, a bonfire or similar, one hour of preparation, one
{consumption} of <<_alchemist_tools>>, and one glass bottle to create a bottle of
venom that can coat the business end of a slashing or piercing weapon,
including arrowheads. The bottle has a number of {usage_points} equal to your
level.

It takes three {moves} to apply a readied bottle of venom to a readied weapon,
and it lasts for up to one week one the weapon.

Once you have coated your weapon, you add __L__d6 to the damage of the next
successful attack with that weapon, where __L__ is your level.

[quote]
Some baddies, such as undeads and mechanoids, are immune to poison.

//END_SORT


=== Level 4

==== More Hit Points
Increase your {hit_point_total} by 1d8. Roll with {advantage}.

==== Better Stat
Roll a d20 and increase one of the stats that is lower than what you rolled.
Too bad if you didn't roll higher than any stat.

=== Level 5

==== More Hit Points
Increase your {hit_point_total} by 1d8. Roll with {advantage}.

==== Better Stat
Roll a d20 and increase one of the stats that is lower than what you rolled.
Too bad if you didn't roll higher than any stat.

=== Level 6: Graduation
It is time for you to move on. You’re no longer just an hero, you’re an Elite.
See how this affects you in the {elites}.

// ROGUE }}}


// {{{ WARRIOR
== WARRIOR

=== Level 3

==== More Hit Points
Your {hit_point_total} is increased by 10.

==== Specialization
You may switch two stats.

==== Better Stats
Roll a d20 with {advantage}; if the roll is higher than your __strength__
increase that it by one point. Do the same for __constitution__.

==== Weapon Skills

.Warrior's Attack and Damage
[%header,cols="6,^2,^2,^2"]
|===
| Weapon                | Stat        | Skill       | Damage 
//----------------------|-------------|-------------|-------------
| Light Melee Weapons   | _strength_  | Skilled     | 1d8
| Ranged Weapons        | _wisdom_    | Skilled     | 1d6
| Heavy Melee Weapons   | _strength_  | Skilled     | 1d12
| Unarmed Combat        | _dexterity_ | Unskilled   | 1d4
//----------------------|-------------|-------------|-------------
|===

==== Armor Skills
You are __skilled__ at using light and medium armor, as well as light and
medium shields.

==== Bonus Damage
When you strike with a weapon you're __skilled__ with, you add your __level__
to the damage roll.

==== Adventurer's Ability
You may change your {adventurers_ability} if you want.

==== Warrior Special Ability
Chose one of the abilities below. You may switch this ability every time you
gain a level.

//START_SORT //KEY:


//KEY:
*Basher*: If you have landed a successful hit with a non-broken blunt heavy
melee weapon on a baddie no larger than you, you may push them 2 meters away
from you. If your attack was a {critical_hit} you can push a creature of any
size and weight. Pushing a baddie past or away from an ally with the
{backstabber} ability will trigger their bonus attack, but if __you__ yourself
have that ability, you do not get a bonus attack. When you reach level 6 you
can push a baddie 3 meters away from you, when you reach level 8 the distance
is 4 meters, and a 10th level character with this ability can push an enemy up
to 5 meters.


//KEY:
*Critter*: you only have to roll lower than or equal to your level in order to
get a {critical_hit}


//KEY:
*Hauler*: At any point in time, the three heaviest items you carry do not take
up any {item_slots}.


//KEY:
*Hunter*: Your ranged damage is increased to 1d10, you can attack baddies up to
__wisdom__ meters away with a __normal__ check, and up to 2·__wisdom__ meters
away with {difficult} checks.


//KEY:
*Pugilist*: You are __skilled__ at unarmed combat, your unarmed damage is 1d10,
you are allowed to add the warrior's <<_bonus_damage>>, and you are able to
fully damage creatures with resistance to non-magical attacks. In addition to
these benefits, you are able to use a light or medium shield along with your
unarmed combat, but your damage is only 1d8 if doing so.


//KEY:
*Shield Fighter*: If you failed an attack check with a light melee weapon, and
your are wearing an non-broken shield, you are allowed to make an attack with
your shield. In your hands, a shield is the same as a light melee weapon.

[quote]
If you roll a {nat20} on your shield attack, your shield becomes __broken__,
which means you lose one {move}.


//KEY:
*Tank*: You are __skilled__ at using heavy armor, and one of the armor pieces
you carry does not take up any {item_slots}.

//END_SORT

=== Level 4

==== More Hit Points
Increase your {hit_point_total} by 1d10. Roll with {advantage}.

==== Better Stat
Roll a d20 and increase one of the stats that is lower than what you rolled.
Too bad if you didn't roll higher than any stat.


=== Level 5

==== More Hit Points
Increase your {hit_point_total} by 1d10. Roll with {advantage}.

=== Level 6: Graduation
It is time for you to move on. You’re no longer just an hero, you’re an Elite.
See how this affects you in the {elites}.

==== Better Stat
Roll a d20 and increase one of the stats that is lower than what you rolled.
Too bad if you didn't roll higher than any stat.

// WARRIOR }}}


// {{{ HERO GEAR
== HERO GEAR

=== Alchemist tools
Blaaaaaahahaaahah


// }}}


// {{{ HERO SPELLS
== HERO SPELLS

//START_SORT ===


=== Detect Undead, Major
*<<champion>>, Level 4. Duration: __wisdom__ hours.*

You can feel when one or more undead creatures are within __wisdom__ meters of
you. You can detect undead creatures through most walls, but not it cannot
penetrate more than one meter of rock or one centimeter of lead.

If the undead creature's level is lower than {X}, you are able to ascertain
its direction, otherwise you only know that the creature is present, not where
it might be.


=== Last Rites
*<<champion>>, Level 3. {ritual}*

You touch a corpse that has died within the last __charisma__ hours. This
prevents the corpse from automatically rising as an undead. A sufficiently
powerful necromancer can still turn this corpse into an undead creature.


=== Money Talks (X)
*{basic}, Level 5+*

You chant for {X} minutes and then you touch a pair of gilded clipboards
worth at least 100·{X} gold pieces each. The clipboards become enchanted so
when a piece of paper is placed on top of each board, anything written on
either paper also shows up on its counterpart on the other clipboard.

This only works if the two clipboards are within 10·{X} kilometers of each
other.

The enchantment lasts 100·{X} days, but you can cast this spell on the
clipboards again later, as long as they are both undamaged and close enough to
touch.

Destroying or severely damaging either clipboard breaks the spell.


=== Trauma (X)
*[basic}, Level 6*
You touch a baddie who must roll on the {trauma_table}: 1d100+{X}.

//END_SORT

// SPELLS }}}


// {{{ DICTIONARY
== DICTIONARY

//START_SORT //KEY:


//KEY:
[reftext="champion"]
[[champion]]
*Champion (spell property)*: Spells with this property can only be cast by
<<_champion,champions>>.


//KEY:
[reftext="mage"]
[[mage]]
*Mage (spell property)*: Spells with this property can only be cast by
<<_mage,mages>>.


//END_SORT
// }}}
