This text should remain in place
placeholder text 4
placeholder text 3
placeholder text 2
placeholder text 1

//START_SORT ==

pre placeholder text 4
pre placeholder text 3
pre placeholder text 2
pre placeholder text 1

== Zxx
Z placeholder text 4
Z placeholder text 3
Z placeholder text 2
Z placeholder text 1

== Axx
A placeholder text 4
A placeholder text 3
A placeholder text 2
A placeholder text 1

//END_SORT

This text should remain in place
placeholder text 4
placeholder text 3
placeholder text 2
placeholder text 1


//START_SORT ::

This text should remain in place
pre placeholder text 4
pre placeholder text 3
pre placeholder text 2
pre placeholder text 1

List Item 9::
9 placeholder text 4
9 placeholder text 3
9 placeholder text 2
9 placeholder text 1


List Item 1::
1 placeholder text 4
1 placeholder text 3
1 placeholder text 2
1 placeholder text 1


//END_SORT

This text should remain in place
placeholder text 4
placeholder text 3
placeholder text 2
placeholder text 1



//START_SORT [[]]


This text should remain in place
pre placeholder text 4
pre placeholder text 3
pre placeholder text 2
pre placeholder text 1

[[link_z]]
List Item Z::
9 placeholder text 4
9 placeholder text 3
9 placeholder text 2
9 placeholder text 1


[[link_a]]
List Item A::
1 placeholder text 4
1 placeholder text 3
1 placeholder text 2
1 placeholder text 1

//END_SORT
